use Ocwen;

ALTER TABLE MIGRATION_LOG CHANGE COLUMN MIGRATION_TYPE MIGRATION_TYPE VARCHAR(32) NOT NULL;

ALTER TABLE MIGRATION_LOG ADD COLUMN IMPORT_FILE_NAME VARCHAR(128) NULL DEFAULT NULL AFTER LAST_UPDATED_ON;

ALTER TABLE BATCH_TRANSACTION ADD COLUMN TERMINATE_COUNT BIGINT(20) NULL DEFAULT NULL;

COMMIT;