/*
SQLyog Community v11.01 (32 bit)
MySQL - 5.6.17 : Database - umg_admin
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`umg_admin` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE `umg_admin`;

/*Table structure for table `TENANT_CONFIG` */

DROP TABLE IF EXISTS `TENANT_CONFIG`;

CREATE TABLE `TENANT_CONFIG` (
  `ID` char(36) COLLATE utf8_bin NOT NULL,
  `TENANT_ID` char(36) COLLATE utf8_bin NOT NULL COMMENT 'Tenant where this config parameter belongs to.',
  `SYSTEM_KEY_ID` char(36) COLLATE utf8_bin NOT NULL COMMENT 'Config parameter key.',
  `CONFIG_VALUE` varchar(500) COLLATE utf8_bin DEFAULT NULL COMMENT 'Config parameter value.',
  `CREATED_BY` char(36) COLLATE utf8_bin NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` char(36) COLLATE utf8_bin DEFAULT NULL,
  `LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UN_TENANT_CONFIG_KEY` (`TENANT_ID`,`SYSTEM_KEY_ID`) COMMENT 'Key for a tenant is unique',
  KEY `FK_TENANT_CONFIG_SYSTEM_KEY_idx` (`SYSTEM_KEY_ID`),
  CONSTRAINT `FK_TENANT_CONFIG_SYSTEM_KEY` FOREIGN KEY (`SYSTEM_KEY_ID`) REFERENCES `SYSTEM_KEY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TENANT_CONFIG_TENANT` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
