use `Ocwen`;

ALTER TABLE `MODEL_LIBRARY`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL COMMENT 'Execution environment of the model library' DEFAULT 'Linux' COLLATE 'utf8_bin' AFTER `PACKAGE_NAME`;

ALTER TABLE `MODEL_LIBRARY_AUDIT`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL COMMENT 'Execution environment of the model library' DEFAULT 'Linux' COLLATE 'utf8_bin' AFTER `PACKAGE_NAME`;

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN  `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Execution Environment(Linux/Windows)' COLLATE 'utf8_bin';
ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN  `MODELLING_ENVIRONMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Modelling Environment(R-3.2.1/R-3.3.2/Matlab-7.16)' COLLATE 'utf8_bin';

commit;
