use `Ocwen`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` ADD COLUMN `ACCEPTABLEVALUES_VALIDATION` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Flag to allow acceptable validation' COLLATE 'utf8_bin' AFTER `IS_TEST`;

commit;
