use umg_admin;

SET SQL_SAFE_UPDATES = 0;

ALTER TABLE `POOL_CRITERIA` DROP COLUMN `CRITERIA_PRIORITY`;
	
ALTER TABLE `SYSTEM_PARAMETER`
CHANGE COLUMN `SYS_VALUE` `SYS_VALUE` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `SYS_KEY`;

ALTER TABLE `SYSTEM_PARAMETER_AUDIT` 
CHANGE COLUMN `SYS_VALUE` `SYS_VALUE` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `SYS_KEY`;

ALTER TABLE `MODEL_EXECUTION_ENVIRONMENTS`	DROP INDEX `NAME`;

ALTER TABLE `MODEL_EXEC_PACKAGES` DROP INDEX `UNIQUE_PACKAGE_NAME`;

ALTER TABLE `MODEL_EXEC_PACKAGES` DROP INDEX `PACKAGE_FOLDER_VERSION_CONSTRAINT`;

ALTER TABLE `SYSTEM_PARAMETER_AUDIT` DROP COLUMN `DESCRIPTION`;

ALTER TABLE `SYSTEM_PARAMETER` DROP COLUMN `DESCRIPTION`;

COMMIT;