use umg_admin;

SET SQL_SAFE_UPDATES = 0;

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TENANT', 'tenantCode');

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'ENVIRONMENT_VERSION', 'executionEnvironmentVersion' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'ENVIRONMENT', 'executionEnvironment' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TRANSACTION_TYPE', 'transactionRequestType');

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'MODEL_VERSION', 'modelVersion' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'MODEL', 'modelName' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TRANSACTION_MODE', 'transactionRequestMode' );


UPDATE `MODEL_EXECUTION_ENVIRONMENTS` SET `ENVIRONMENT_VERSION`='3.1.2' WHERE  `NAME`='R-3.2.1';
UPDATE `MODEL_EXECUTION_ENVIRONMENTS` SET `NAME`='R-3.1.2' WHERE  `NAME`='R-3.2.1';
UPDATE `MODEL_EXEC_PACKAGES` SET `MODEL_EXEC_ENV_NAME`='R-3.1.2' WHERE `MODEL_EXEC_ENV_NAME`='R-3.2.1';
UPDATE `MODEL_EXEC_PACKAGES_AUDIT`  SET `MODEL_EXEC_ENV_NAME`='R-3.1.2' WHERE `MODEL_EXEC_ENV_NAME`='R-3.2.1';
UPDATE `POOL_CRITERIA_DEF_MAPPING` p SET p.POOL_CRITERIA_VALUE = REPLACE (POOL_CRITERIA_VALUE, '3.2.1', '3.1.2' );
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=6 WHERE  `NAME`='symanticCheckModelIOXml';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=5 WHERE  `NAME`='validateModelIOXml';

update POOL set MODELET_COUNT = 4 where POOL_NAME = 'MATLAB_DEFAULT';
update POOL set MODELET_COUNT = 2 where POOL_NAME = 'MATLAB_BATCH_POOL';
update POOL set MODELET_COUNT = 2 where POOL_NAME = 'HUBZU_WEEK_N';
update POOL set MODELET_COUNT = 2 where POOL_NAME = 'R_DEFAULT_POOL';
update POOL set MODELET_COUNT = 0 where POOL_NAME = 'HUBZU_WEEK_0';


COMMIT;