USE umg_admin;

ALTER TABLE ADDRESS MODIFY ADDRESS_1 VARCHAR(200) NOT NULL ; 
ALTER TABLE ADDRESS MODIFY ADDRESS_2 VARCHAR(200) ;
ALTER TABLE ADDRESS MODIFY ZIP VARCHAR(6) NOT NULL;

ALTER TABLE `SYSTEM_KEY` ADD UNIQUE INDEX `SYSTEM_KEY` (`SYSTEM_KEY`, `KEY_TYPE`);

DROP TABLE IF EXISTS SYSTEM_MODELETS;

CREATE TABLE `SYSTEM_MODELETS` (
                `HOST_NAME` CHAR(36) NOT NULL,
                `PORT` INT(10) NOT NULL,
                `ENVIRONMENT` VARCHAR(20) NOT NULL,
                `MEMBER_HOST` VARCHAR(36) NOT NULL,
                PRIMARY KEY (`HOST_NAME`, `PORT`)
)
COMMENT='Stores all modelet configurations'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


DROP TABLE IF EXISTS AUTHTOKEN;

CREATE TABLE `AUTHTOKEN` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant ID' COLLATE 'utf8_bin',
	`AUTH_CODE` VARCHAR(64) NOT NULL COLLATE 'utf8_bin',
	`ACTIVE_FROM` BIGINT(20),	
	`ACTIVE_UNTIL` BIGINT(20),
	`STATUS` VARCHAR(100) NOT NULL,
	`COMMENT` VARCHAR(100),
	`CREATED_ON` BIGINT(20) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_AUTHTOKEN_TENANT` (`TENANT_ID`),
	CONSTRAINT `FK_AUTHTOKEN_TENANT` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8_bin'
ENGINE=InnoDB;



SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE TENANT_ROLES_MAPPING CHANGE COLUMN `tenant_code` `tenant_code` VARCHAR(10) NOT NULL COMMENT 'Tenant code used for unique identificaiton' COLLATE 'utf8_bin';
ALTER TABLE TENANT_USER_MAPPING CHANGE COLUMN `tenant_code` `tenant_code` VARCHAR(10) NOT NULL COMMENT 'Tenant code used for unique identificaiton' COLLATE 'utf8_bin';
ALTER TABLE USERS_LOGIN_AUDIT CHANGE COLUMN `tenant_code` `tenant_code` VARCHAR(10) NOT NULL COMMENT 'Tenant code used for unique identificaiton' COLLATE 'utf8_bin';
ALTER TABLE TENANT CHANGE COLUMN `CODE` `CODE` VARCHAR(10) NOT NULL COMMENT 'Tenant code used for unique identificaiton' COLLATE 'utf8_bin';

SET FOREIGN_KEY_CHECKS = 1;

commit;