CREATE TABLE IF NOT EXISTS MODEL (
  ID CHAR(36) NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  DESCRIPTION VARCHAR(255) NULL,
  VERSION INT NOT NULL DEFAULT 0,
  IMPLEMENTATION VARCHAR(45) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID)
);