ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
ADD COLUMN `TEMP_TENANT_INPUT` MEDIUMBLOB NULL AFTER `TENANT_INPUT`;


update UMG_RUNTIME_TRANSACTION set TEMP_TENANT_INPUT=TENANT_INPUT ;


ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
DROP COLUMN `TENANT_INPUT`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
CHANGE COLUMN `TEMP_TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NULL DEFAULT NULL ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
CHANGE COLUMN `TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NOT NULL ;

--
ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
ADD COLUMN `TEMP_MODEL_INPUT` MEDIUMBLOB NULL AFTER `MODEL_INPUT`;

update UMG_RUNTIME_TRANSACTION set TEMP_MODEL_INPUT=MODEL_INPUT ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
DROP COLUMN `MODEL_INPUT`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
CHANGE COLUMN `TEMP_MODEL_INPUT` `MODEL_INPUT` MEDIUMBLOB NOT NULL ;

/*UMG_RUNTIME_TRANSACTION_AUDIT*/

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
ADD COLUMN `TEMP_TENANT_INPUT` MEDIUMBLOB NULL AFTER `TENANT_INPUT`;


update UMG_RUNTIME_TRANSACTION_AUDIT set TEMP_TENANT_INPUT=TENANT_INPUT ;


ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
DROP COLUMN `TENANT_INPUT`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
CHANGE COLUMN `TEMP_TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NULL DEFAULT NULL ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
CHANGE COLUMN `TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NOT NULL ;

--
ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
ADD COLUMN `TEMP_MODEL_INPUT` MEDIUMBLOB NULL AFTER `MODEL_INPUT`;

update UMG_RUNTIME_TRANSACTION_AUDIT set TEMP_MODEL_INPUT=MODEL_INPUT ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
DROP COLUMN `MODEL_INPUT`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
CHANGE COLUMN `TEMP_MODEL_INPUT` `MODEL_INPUT` MEDIUMBLOB NOT NULL ;