ALTER TABLE MAPPING 
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL AFTER `STATUS`;

update MAPPING set TEMP_MODEL_IO=model_io_data ;

ALTER TABLE MAPPING 
DROP COLUMN `MODEL_IO_DATA`;


ALTER TABLE MAPPING 
CHANGE COLUMN `TEMP_MODEL_IO` `MODEL_IO_DATA` MEDIUMBLOB;


ALTER TABLE `MAPPING` 
CHANGE COLUMN `MODEL_IO_DATA` `MODEL_IO_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MODEL_ID`;





ALTER TABLE `MAPPING_AUDIT` 
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL AFTER `STATUS`;

update MAPPING_AUDIT set TEMP_MODEL_IO=model_io_data ;

ALTER TABLE `MAPPING_AUDIT` 
DROP COLUMN `MODEL_IO_DATA`;


ALTER TABLE `MAPPING_AUDIT` 
CHANGE COLUMN `TEMP_MODEL_IO` `MODEL_IO_DATA` MEDIUMBLOB;


ALTER TABLE `MAPPING_AUDIT` 
CHANGE COLUMN `MODEL_IO_DATA` `MODEL_IO_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MODEL_ID`;



ALTER TABLE MAPPING_INPUT 
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL ;

update MAPPING_INPUT set TEMP_MODEL_IO=MAPPING_DATA ;

ALTER TABLE MAPPING_INPUT 
DROP COLUMN `MAPPING_DATA`;


ALTER TABLE MAPPING_INPUT 
CHANGE COLUMN `TEMP_MODEL_IO` `MAPPING_DATA` MEDIUMBLOB;


ALTER TABLE MAPPING_INPUT 
CHANGE COLUMN `MAPPING_DATA` `MAPPING_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MAPPING_ID`;



ALTER TABLE MAPPING_INPUT_AUDIT
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL ;

update MAPPING_INPUT_AUDIT set TEMP_MODEL_IO=MAPPING_DATA ;

ALTER TABLE MAPPING_INPUT_AUDIT 
DROP COLUMN `MAPPING_DATA`;


ALTER TABLE MAPPING_INPUT_AUDIT 
CHANGE COLUMN `TEMP_MODEL_IO` `MAPPING_DATA` MEDIUMBLOB;


ALTER TABLE MAPPING_INPUT_AUDIT 
CHANGE COLUMN `MAPPING_DATA` `MAPPING_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MAPPING_ID`;



ALTER TABLE MAPPING_OUTPUT
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL ;

update MAPPING_OUTPUT set TEMP_MODEL_IO=MAPPING_DATA ;

ALTER TABLE MAPPING_OUTPUT
DROP COLUMN `MAPPING_DATA`;


ALTER TABLE MAPPING_OUTPUT
CHANGE COLUMN `TEMP_MODEL_IO` `MAPPING_DATA` MEDIUMBLOB;


ALTER TABLE MAPPING_OUTPUT
CHANGE COLUMN `MAPPING_DATA` `MAPPING_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MAPPING_ID`;




ALTER TABLE MAPPING_OUTPUT_AUDIT
ADD COLUMN `TEMP_MODEL_IO` MEDIUMBLOB NULL ;

update MAPPING_OUTPUT_AUDIT set TEMP_MODEL_IO=MAPPING_DATA ;

ALTER TABLE MAPPING_OUTPUT_AUDIT
DROP COLUMN `MAPPING_DATA`;


ALTER TABLE MAPPING_OUTPUT_AUDIT
CHANGE COLUMN `TEMP_MODEL_IO` `MAPPING_DATA` MEDIUMBLOB;


ALTER TABLE MAPPING_OUTPUT_AUDIT
CHANGE COLUMN `MAPPING_DATA` `MAPPING_DATA` MEDIUMBLOB NULL DEFAULT NULL AFTER `MAPPING_ID`;

