-- MAPPING_INPUT

ALTER TABLE `MAPPING_INPUT` 
ADD COLUMN `TENANT_TEMP_IO` MEDIUMBLOB NULL AFTER `TENANT_INTF_SYS_DEFINITION`;

update MAPPING_INPUT set TENANT_TEMP_IO=TENANT_INTERFACE_DEFINITION ;

ALTER TABLE `MAPPING_INPUT` 
DROP COLUMN `TENANT_INTERFACE_DEFINITION`;

ALTER TABLE `MAPPING_INPUT` 
CHANGE COLUMN `TENANT_TEMP_IO` `TENANT_INTERFACE_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;

ALTER TABLE `MAPPING_INPUT` 
CHANGE COLUMN `TENANT_INTERFACE_DEFINITION` `TENANT_INTERFACE_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL AFTER `MAPPING_DATA`;

--
ALTER TABLE `MAPPING_INPUT` 
ADD COLUMN `TENANT_TEMP_SYS_DEF` MEDIUMBLOB NULL AFTER `TENANT_INTF_SYS_DEFINITION`;

update MAPPING_INPUT set TENANT_TEMP_SYS_DEF=TENANT_INTF_SYS_DEFINITION ;

ALTER TABLE MAPPING_INPUT
DROP COLUMN `TENANT_INTF_SYS_DEFINITION`;

ALTER TABLE `MAPPING_INPUT` 
CHANGE COLUMN `TENANT_TEMP_SYS_DEF` `TENANT_INTF_SYS_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;

-- MAPPING_INPUT_AUDIT

ALTER TABLE `MAPPING_INPUT_AUDIT` 
ADD COLUMN `TENANT_TEMP_IO` MEDIUMBLOB NULL AFTER `TENANT_INTERFACE_DEFINITION`;

update MAPPING_INPUT_AUDIT set TENANT_TEMP_IO=TENANT_INTERFACE_DEFINITION ;

ALTER TABLE `MAPPING_INPUT_AUDIT` 
DROP COLUMN `TENANT_INTERFACE_DEFINITION`;

ALTER TABLE `MAPPING_INPUT_AUDIT` 
CHANGE COLUMN `TENANT_TEMP_IO` `TENANT_INTERFACE_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;


--

ALTER TABLE `MAPPING_INPUT_AUDIT` 
ADD COLUMN `TENANT_TEMP_SYS_DEF` MEDIUMBLOB NULL AFTER `TENANT_INTF_SYS_DEFINITION`;

update MAPPING_INPUT_AUDIT set TENANT_TEMP_SYS_DEF=TENANT_INTF_SYS_DEFINITION ;

ALTER TABLE `MAPPING_INPUT_AUDIT` 
DROP COLUMN `TENANT_INTF_SYS_DEFINITION`;

ALTER TABLE `MAPPING_INPUT_AUDIT` 
CHANGE COLUMN `TENANT_TEMP_SYS_DEF` `TENANT_INTF_SYS_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;


-- MAPPING_OUTPUT

ALTER TABLE `MAPPING_OUTPUT` 
ADD COLUMN `TENANT_TEMP_IO` MEDIUMBLOB NULL AFTER `TENANT_INTERFACE_DEFINITION`;


update MAPPING_OUTPUT set TENANT_TEMP_IO=TENANT_INTERFACE_DEFINITION ;


ALTER TABLE `MAPPING_OUTPUT` 
DROP COLUMN `TENANT_INTERFACE_DEFINITION`;

ALTER TABLE `MAPPING_OUTPUT` 
CHANGE COLUMN `TENANT_TEMP_IO` `TENANT_INTERFACE_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;


-- MAPPING_OUTPUT_AUDIT


ALTER TABLE `MAPPING_OUTPUT_AUDIT` 
ADD COLUMN `TENANT_TEMP_IO` MEDIUMBLOB NULL AFTER `TENANT_INTERFACE_DEFINITION`;


update MAPPING_OUTPUT_AUDIT set TENANT_TEMP_IO=TENANT_INTERFACE_DEFINITION ;


ALTER TABLE `MAPPING_OUTPUT_AUDIT` 
DROP COLUMN `TENANT_INTERFACE_DEFINITION`;

ALTER TABLE `MAPPING_OUTPUT_AUDIT` 
CHANGE COLUMN `TENANT_TEMP_IO` `TENANT_INTERFACE_DEFINITION` MEDIUMBLOB NULL DEFAULT NULL ;


























