ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
ADD COLUMN `TEMP_ERROR_DESCRIPTION` BLOB NULL AFTER `ERROR_DESCRIPTION`;

update `UMG_RUNTIME_TRANSACTION` set TEMP_ERROR_DESCRIPTION=ERROR_DESCRIPTION ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` DROP COLUMN `ERROR_DESCRIPTION`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
CHANGE COLUMN `TEMP_ERROR_DESCRIPTION` `ERROR_DESCRIPTION` BLOB NULL DEFAULT NULL ;



ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
ADD COLUMN `TEMP_ERROR_DESCRIPTION` BLOB NULL AFTER `ERROR_DESCRIPTION`;

update `UMG_RUNTIME_TRANSACTION_AUDIT` set TEMP_ERROR_DESCRIPTION = ERROR_DESCRIPTION ;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` DROP COLUMN `ERROR_DESCRIPTION`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT` 
CHANGE COLUMN `TEMP_ERROR_DESCRIPTION` `ERROR_DESCRIPTION` BLOB NULL DEFAULT NULL ;