ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `PRIOR_RECOMMENDED` CHAR(1) NULL AFTER `PROP_SOLD_DATE_DT`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` ADD COLUMN `PRIOR_RECOMMENDED` VARCHAR(50) NULL AFTER `LP_DOLLAR_ADJUSTMENT_REC`;

INSERT INTO `RA_TNT_SYSTEM_PARAMETERS` (`ID`, `SYS_KEY`, `SYS_VALUE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), 'weekn.days.before.selected.date', '14', 'Fetch days count.', 'SYSTEM', NOW(), NULL, NULL);