use umg_admin;

DROP TABLE IF EXISTS NOTIFICATION_TYPE;

CREATE TABLE NOTIFICATION_TYPE (
	ID CHAR(36) NOT NULL,
	TYPE VARCHAR(50) NOT NULL COMMENT 'Mail or SMS',
	DESCRIPTION VARCHAR(255) NULL DEFAULT NULL,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY VARCHAR(32) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE NOTIFICATION_TYPE  ADD UNIQUE INDEX TYPE_UNIQUE (TYPE ASC);


DROP TABLE IF EXISTS NOTIFICATION_EVENT;

CREATE TABLE NOTIFICATION_EVENT (
	ID CHAR(36) NOT NULL,
	NAME VARCHAR(45) NOT NULL COMMENT 'Model Publishing Success event',
	DESCRIPTION VARCHAR(255) NOT NULL DEFAULT '',
	CLASSIFICATION VARCHAR(64) NOT NULL,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY VARCHAR(32) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE NOTIFICATION_EVENT ADD UNIQUE INDEX NAME_UNIQUE (NAME ASC);


DROP TABLE IF EXISTS NOTIFICATION_EMAIL_TEMPLATE;

CREATE TABLE NOTIFICATION_EMAIL_TEMPLATE (
	ID CHAR(36) NOT NULL,
	NOTIFICATION_EVENT_ID CHAR(36) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NOT NULL DEFAULT '',
	BODY_DEFINITION MEDIUMBLOB NOT NULL COMMENT 'Mail Template Definition',
	SUBJECT_DEFINITION VARCHAR(256) NOT NULL,
    IS_ACTIVE INT(10) NOT NULL DEFAULT '1',
	MAJOR_VERSION INT(11) NOT NULL DEFAULT '1',
	MAIL_CONTENT_TYPE VARCHAR(64) NOT NULL COMMENT 'MIME Message Types',
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY VARCHAR(32) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS NOTIFICATION_SMS_TEMPLATE;

CREATE TABLE NOTIFICATION_SMS_TEMPLATE (
	ID CHAR(36) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NOT NULL DEFAULT '',
	SMS_DEFINITION BLOB NOT NULL COMMENT 'Model Publishing Success Template',
	IS_ACTIVE INT(10) NOT NULL DEFAULT '1',
	MAJOR_VERSION INT(11) NOT NULL DEFAULT '1',
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY VARCHAR(32) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS NOTIFICATION_EVENT_TEMPLATE_MAPPING;

CREATE TABLE NOTIFICATION_EVENT_TEMPLATE_MAPPING (
	ID CHAR(36) NOT NULL,
	NAME VARCHAR(45) NOT NULL, 	
	NOTIFICATION_EVENT_ID CHAR(36) NOT NULL,
	NOTIFICATION_TEMPLATE_ID CHAR(36) NOT NULL,
	NOTIFICATION_TYPE_ID CHAR(36) NOT NULL,
	TENANT_ID VARCHAR(45) NOT NULL,
	TO_ADDRESS VARCHAR(1500) NULL DEFAULT NULL,
	FROM_ADDRESS VARCHAR(256) NULL DEFAULT NULL,
	CC_ADDRESS VARCHAR(256) NULL DEFAULT NULL,
	BCC_ADDRESS VARCHAR(256) NULL DEFAULT NULL,
	MOBILE BIGINT(20) NULL DEFAULT NULL,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY VARCHAR(32) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
);


COMMIT;