UPDATE DP_SOP_WEEK0_PRCS_STATUS set LAST_UPDATED_BY = 'SYSTEM', LAST_UPDATED_ON = CREATED_ON where status = 'DATA_LOAD';

UPDATE DP_SOP_WEEKN_PRCS_STATUS set LAST_UPDATED_BY = 'SYSTEM', LAST_UPDATED_ON = CREATED_ON where status = 'DATA_LOAD';