UPDATE DP_SOP_WEEK0_PRCS_STATUS set LAST_UPDATED_BY = null, LAST_UPDATED_ON = null where status = 'DATA_LOAD'

UPDATE DP_SOP_WEEKN_PRCS_STATUS set LAST_UPDATED_BY = null, LAST_UPDATED_ON = null where status = 'DATA_LOAD'
