

ALTER TABLE `DP_WEEKN_PRCS_STATUS`
	CHANGE COLUMN `INPUT_FILE_NAME` `INPUT_FILE_NAME` VARCHAR(100) NOT NULL DEFAULT '' AFTER `ID`,
	CHANGE COLUMN `SYS_GNRTD_INPUT_FILE_NAME` `SYS_GNRTD_INPUT_FILE_NAME` VARCHAR(50) NOT NULL DEFAULT '' AFTER `INPUT_FILE_NAME`,
	CHANGE COLUMN `OCN_OUTPUT_FILE_NAME` `OCN_OUTPUT_FILE_NAME` VARCHAR(100) NULL DEFAULT NULL AFTER `SYS_GNRTD_INPUT_FILE_NAME`,
	CHANGE COLUMN `NRZ_OUTPUT_FILE_NAME` `NRZ_OUTPUT_FILE_NAME` VARCHAR(100) NULL DEFAULT NULL AFTER `OCN_OUTPUT_FILE_NAME`;
