
SET @PROCESS = 'QA_REPORT';

DELETE FROM `COMMAND` WHERE `PROCESS` = @PROCESS AND `NAME` = 'qaReportFetchData';
DELETE FROM `COMMAND` WHERE `PROCESS` = @PROCESS AND `NAME` = 'qaReportAssignmentFilter';
DELETE FROM `COMMAND` WHERE `PROCESS` = @PROCESS AND `NAME` = 'qaReportPast12CyclesFilter';
DELETE FROM `COMMAND` WHERE `PROCESS` = @PROCESS AND `NAME` = 'qaReportStateFilter';
DELETE FROM `COMMAND` WHERE `PROCESS` = @PROCESS AND `NAME` = 'qaReportSSPmiFilter';