

ALTER TABLE `DP_SOP_WEEK0_PARAMS` DROP COLUMN `ASSIGNMENT`;
ALTER TABLE `DP_SOP_WEEK0_PARAMS` DROP COLUMN `ASSIGNMENT_DATE`;
ALTER TABLE `DP_SOP_WEEK0_PARAMS` DROP COLUMN `UPLOAD_FLAG`;
ALTER TABLE `DP_SOP_WEEK0_PARAMS_ORIGINAL` DROP COLUMN `ASSIGNMENT`;


DELETE FROM `COMMAND` WHERE `PROCESS`='SOP_WEEK0_OCN';
DELETE FROM `COMMAND` WHERE `PROCESS`='SOP_WEEK0_NRZ';