/*
SQLyog Community v11.01 (32 bit)
MySQL - 5.6.17 : Database - umg_admin
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/umg_admin /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE umg_admin;

DROP TABLE IF EXISTS SYNDICATED_DATA;

CREATE table SYNDICATED_DATA(
	ID char(36) COLLATE utf8_bin NOT NULL,
	CONTAINER_NAME varchar(50) COLLATE utf8_bin NOT NULL, 
	DESCRIPTION varchar(200) COLLATE utf8_bin NOT NULL, 
	VERSION_ID bigint(4) COLLATE utf8_bin, 
	VERSION_NAME VARCHAR(50) NOT NULL COLLATE utf8_bin,
	VERSION_DESCRIPTION VARCHAR(200) NOT NULL COLLATE utf8_bin,
	TABLE_NAME varchar(200) COLLATE utf8_bin,
	VALID_FROM bigint(20) COLLATE utf8_bin, 
	VALID_TO bigint(20) COLLATE utf8_bin, 
	CREATED_BY char(100) COLLATE utf8_bin NOT NULL,
	CREATED_ON bigint(20) NOT NULL,
	LAST_UPDATED_BY char(100) COLLATE utf8_bin DEFAULT NULL,
	LAST_UPDATED_ON bigint(20) DEFAULT NULL,
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS SYNDICATED_DATA_AUDIT;

CREATE TABLE SYNDICATED_DATA_AUDIT(
	ID CHARACTER(36),
	CONTAINER_NAME VARCHAR(50), 
	DESCRIPTION VARCHAR(200),
	VERSION_NAME VARCHAR(50),
	VERSION_DESCRIPTION VARCHAR(200),
	VERSION_ID BIGINT, 
	TABLE_NAME VARCHAR(200),
	VALID_FROM BIGINT, 
	VALID_TO BIGINT,
	CREATED_BY VARCHAR(100) NULL DEFAULT NULL,
	CREATED_ON BIGINT(20) NULL DEFAULT NULL,
	LAST_UPDATED_BY VARCHAR(100) NULL DEFAULT NULL,
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	REV INTEGER NOT NULL,
	REVTYPE INTEGER,
	PRIMARY KEY (ID,REV),
  	CONSTRAINT FK_SYNDICATED_DATA_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

create index INDEX_CINTAINER_NAME on SYNDICATED_DATA(CONTAINER_NAME);