
SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

-- SOP WEEKN command
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'sopWeekNFetchData', 'Duplicate Asset', 1, 'SOP_WEEKN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

-- SOP WEEKN OCN command
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNAssignmentFilter', 'Benchmark', 1, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 2, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNActiveListingsFilter', 'Active Listing', 3, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNPast12CyclesFilter', 'Past 12 Cycles', 4, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNOddListingsFilter', 'Odd Listing', 5, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNZipStateFilter', 'Unsupported State/Zip', 6, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNSSPmiFilter', 'SS & PMI', 7, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNSOPFilter', 'SOP', 8, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNRAIntegrarion', 'Model Failure', 9, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'ocnSOPWeekNOutputFileCreate', 'WEEKN_OUTPUT_FILE', 10, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

-- SOP WEEKN NRZ command
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNAssignmentFilter', 'Benchmark', 1, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 2, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNActiveListingsFilter', 'Active Listing', 3, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNPast12CyclesFilter', 'Past 12 Cycles', 4, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNOddListingsFilter', 'Odd Listing', 5, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNZipStateFilter', 'Unsupported State/Zip', 6, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNSSPmiFilter', 'SS & PMI', 7, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNSOPFilter', 'SOP', 8, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNRAIntegrarion', 'Model Failure', 9, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'nrzSOPWeekNOutputFileCreate', 'WEEKN_OUTPUT_FILE', 10, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

-- SOP WEEKN PHH command
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNAssignmentFilter', 'Benchmark', 1, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 2, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNActiveListingsFilter', 'Active Listing', 3, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNPast12CyclesFilter', 'Past 12 Cycles', 4, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNOddListingsFilter', 'Odd Listing', 5, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNZipStateFilter', 'Unsupported State/Zip', 6, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNSSPmiFilter', 'SS & PMI', 7, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNSOPFilter', 'SOP', 8, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNRAIntegrarion', 'Model Failure', 9, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
	VALUES (UUID(), 'phhSOPWeekNOutputFileCreate', 'WEEKN_OUTPUT_FILE', 10, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
