
DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_PHH';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_NRZ';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_OCN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN';
