CREATE TABLE COMMAND (
  ID CHAR(36) NOT NULL,
  NAME VARCHAR(100) NOT NULL COMMENT 'Name of the command',
  DESCRIPTION VARCHAR(200) NULL COMMENT 'Description of the command',
  EXECUTION_SEQUENCE INT(36) NOT NULL COMMENT 'Command sequence id',
  PROCESS VARCHAR(100) NOT NULL COMMENT 'Name of the command',
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UN_COMMAND_SEQUENCE (NAME,PROCESS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('15c27bfe-4491-41a8-98d5-276735f36bc9', 'createModel', 'Create model definition.', 5, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('22d294bf-85b9-4d60-8e0f-ed0d8a36da2a', 'symanticCheckModelIOXml', 'Symantic validation of uploaded model definiition file.', 4, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('28483ea2-740d-4b3c-b858-27afd0326944', 'createModelLibrary', 'Create model library command.', 2, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('46d54377-5e5e-4cdf-a0cd-4b11ef5c096b', 'testVersion', 'Test version.', 9, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('5c6c2228-5e25-4d6b-b989-0e41b00c4eec', 'generateTestInput', 'Generate test input json.', 8, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('5eb9aede-1c06-40ea-bd33-bd436b314816', 'createMapping', 'Create default Mapping.', 6, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('640f5323-1f7d-4d33-98c2-b753291fc375', 'createVersion', 'Create default version.', 7, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('9f7a95a9-dfad-489b-a1bd-420bf589c743', 'validateLibraryChecksum', 'Validate checksum of the uploaded model library jar file.', 1, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('ebfed01f-30a8-460c-95fc-3f7215df2f65', 'validateModelIOXml', 'Valiadate uploaded model definition file..', 3, 'CREATE', 'SYSTEM', 12354856456, NULL, NULL);
