use ocwen;

ALTER TABLE MIGRATION_LOG CHANGE COLUMN MIGRATION_TYPE MIGRATION_TYPE VARCHAR(32) NOT NULL;

ALTER TABLE MIGRATION_LOG ADD COLUMN IMPORT_FILE_NAME VARCHAR(128) NULL DEFAULT NULL AFTER LAST_UPDATED_ON;

COMMIT;