

UPDATE `COMMAND` SET `DESCRIPTION`='RR_CLASSIFICATION_DB' WHERE `NAME`='week0RRClassification';
UPDATE `COMMAND` SET `DESCRIPTION`='DUPLICATE_FILTERING' WHERE `NAME`='week0DuplicateFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='INVESTOR_CODE_FILTERING' WHERE `NAME`='week0InvestorCodeFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='ASSET_VALUE_FILTERING' WHERE `NAME`='week0AssetValueFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='RR_RTNG_CALL' WHERE `NAME`='week0RRRtngAggregator';
UPDATE `COMMAND` SET `DESCRIPTION`='PROPERTY_TYPE_FILTERING' WHERE `NAME`='week0PropertyTypeFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='RA_CALL' WHERE `NAME`='week0RAInputPayload';

UPDATE `COMMAND` SET `DESCRIPTION`='DB_CALLS_FAILED_FILTER' WHERE `NAME`='weekNFetchData';
UPDATE `COMMAND` SET `DESCRIPTION`='ACTIVE_LISTINGS_FILTERING' WHERE `NAME`='weekNActiveListingsFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='PAST12_CYCLES_FILTERING' WHERE `NAME`='weekNPast12CyclesFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='ODD_LISTINGS_FILTERING' WHERE `NAME`='weekNOddListingsFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='ASSIGNMENT_FILTERING' WHERE `NAME`='weekNAssignmentFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='ZIP_STATE_FILTERING' WHERE `NAME`='weekNZipStateFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='SS_PMI_FILTERING' WHERE `NAME`='weekNSSPmiFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='SOP_FILTERING' WHERE `NAME`='weekNSOPFilter';
UPDATE `COMMAND` SET `DESCRIPTION`='WEEKN_RA_CALL' WHERE `NAME`='weekNRAIntegrarion';
