
ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	ADD COLUMN `OLD_PROP_ID` VARCHAR(55) NULL DEFAULT NULL AFTER `RBID_PROP_ID_VC_PK`,
	ADD COLUMN `OLD_LOAN_NUMBER` VARCHAR(55) NULL DEFAULT NULL AFTER `OLD_PROP_ID`;
	
ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	CHANGE COLUMN `PREVIOUS_LIST_END_DATE` `PREVIOUS_LIST_END_DATE` DATE NULL DEFAULT NULL AFTER `PREVIOUS_LIST_STRT_DATE`,
	CHANGE COLUMN `CURRENT_LIST_END_DATE` `CURRENT_LIST_END_DATE` DATE NULL DEFAULT NULL AFTER `CURRENT_LIST_STRT_DATE`;

ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	ADD COLUMN `PREVIOUS_LIST_START_DATE` DATE NULL DEFAULT NULL AFTER `LIST_TYPE_ID_VC_FK`;
ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	ADD COLUMN `CURRENT_LIST_START_DATE` DATE NULL DEFAULT NULL AFTER `PREVIOUS_LIST_PRICE`;
	
UPDATE `WEEKN_DAILY_QA_REPORT` SET `PREVIOUS_LIST_START_DATE` = `PREVIOUS_LIST_STRT_DATE`;
UPDATE `WEEKN_DAILY_QA_REPORT` SET `CURRENT_LIST_START_DATE` = `CURRENT_LIST_STRT_DATE`;
	
ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	DROP COLUMN `PREVIOUS_LIST_STRT_DATE`;
ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	DROP COLUMN `CURRENT_LIST_STRT_DATE`;

