CREATE TABLE MIGRATION_LOG (
  ID CHAR(36) NOT NULL,
  VERSION_ID CHAR(36) NOT NULL,
  MIGRATION_TYPE VARCHAR(10) NOT NULL,
  VERSION_DATA BLOB,
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE REVINFO (
	REV INTEGER IDENTITY NOT NULL,
	REVTSTMP BIGINT,
	REVBY VARCHAR(100)
);

-- Model management tables start
CREATE TABLE MODEL_LIBRARY (
	ID CHARACTER(36) NOT NULL,
	TENANT_ID VARCHAR(45) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	UMG_NAME VARCHAR(100) NOT NULL,
	EXECUTION_LANGUAGE VARCHAR(25) NOT NULL, 
	EXECUTION_TYPE VARCHAR(20), 
	JAR_NAME VARCHAR(100) NOT NULL,
	CHECKSUM_TYPE VARCHAR(20) NOT NULL,
	CHECKSUM_VALUE VARCHAR(100) NOT NULL ,
	CREATED_BY CHAR(36) NOT NULL, 
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MODEL_LIBRARY_AUD(
	ID CHARACTER(36) NOT NULL,
	TENANT_ID VARCHAR(45) NULL,
	NAME VARCHAR(50) NULL,
	DESCRIPTION VARCHAR(200) NULL,
	UMG_NAME VARCHAR(100) NULL,
	EXECUTION_LANGUAGE VARCHAR(25) NULL, 
	EXECUTION_TYPE VARCHAR(20) NULL, 
	JAR_NAME VARCHAR(100) NULL,
	CHECKSUM_TYPE VARCHAR(20) NULL,
	CHECKSUM_VALUE VARCHAR(100) NULL ,
	REV INTEGER NOT NULL,
	REVTYPE INTEGER,
	CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	PRIMARY KEY (ID,REV)
);

CREATE TABLE MODEL (
	ID CHARACTER(36) NOT NULL,
	TENANT_ID VARCHAR(45) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	UMG_NAME VARCHAR(100) NOT NULL,
	IO_DEFINITION_NAME VARCHAR(100) NOT NULL,
	DOC_NAME VARCHAR(100) NOT NULL,
	ALLOW_NULL TINYINT DEFAULT 0 NOT NULL,
	CREATED_BY CHARACTER(36) NOT NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHARACTER(36),
	LAST_UPDATED_ON BIGINT,
	PRIMARY KEY (ID),
	CONSTRAINT UK_MODEL_UMG_NAME UNIQUE (UMG_NAME)
);

CREATE TABLE MODEL_AUD (
	ID CHARACTER(36) NOT NULL,
	TENANT_ID VARCHAR(45) NULL,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	UMG_NAME VARCHAR(100),
	IO_DEFINITION_NAME VARCHAR(100),
	DOC_NAME VARCHAR(100),
	ALLOW_NULL TINYINT,
	REV INTEGER NOT NULL,
	REVTYPE INTEGER,
	CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	PRIMARY KEY (ID,REV)
);

ALTER TABLE MODEL_AUD
	ADD FOREIGN KEY (REV) 
	REFERENCES REVINFO (REV);

CREATE TABLE MODEL_DEFINITION(
	ID CHAR(36) NOT NULL, 
	TENANT_ID VARCHAR(45) NOT NULL,
	IO_TYPE VARCHAR(50) NOT NULL, 
	IO_DEFINITION BLOB NOT NULL,
	MODEL_ID CHAR(36) NOT NULL, 
	CREATED_BY CHAR(36) NOT NULL, 
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES MODEL (ID)
);

CREATE TABLE MODEL_DEFINITION_AUD(
	ID CHAR(36) NOT NULL, 
	TENANT_ID VARCHAR(45) NULL,
	IO_TYPE VARCHAR(50), 
	IO_DEFINITION BLOB,
	MODEL_ID CHAR(36), 
	CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	REV INTEGER NOT NULL,
  	REVTYPE INTEGER,
	PRIMARY KEY (ID,REV),
	CONSTRAINT FK_MODEL_DEFN_AUDIT FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE SYNDICATED_DATA(
	ID CHARACTER(36) NOT NULL,
	CONTAINER_NAME VARCHAR(50) NOT NULL, 
	DESCRIPTION VARCHAR(200) NOT NULL, 
	VERSION_ID BIGINT, 
	VERSION_NAME VARCHAR(50) NOT NULL,
	VERSION_DESCRIPTION VARCHAR(200) NOT NULL,
	TABLE_NAME VARCHAR(200),
	VALID_FROM BIGINT, 
	VALID_TO BIGINT, 
	CREATED_BY VARCHAR(36) NOT NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY VARCHAR(36),
	LAST_UPDATED_ON BIGINT
);

CREATE TABLE SYNDICATED_DATA_AUD(
	ID CHARACTER(36),
	CONTAINER_NAME VARCHAR(50), 
	DESCRIPTION VARCHAR(200), 
	VERSION_ID BIGINT, 
	VERSION_NAME VARCHAR(50) ,
	VERSION_DESCRIPTION VARCHAR(200),
	TABLE_NAME VARCHAR(200),
	VALID_FROM BIGINT, 
	VALID_TO BIGINT,
	CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
	REV INTEGER,
	REVTYPE INTEGER,
	PRIMARY KEY (ID,REV),
  	CONSTRAINT FK_SYNDICATED_DATA_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- mapping tables


CREATE TABLE MAPPING (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(200),
  MODEL_ID CHAR(36) NOT NULL,
  MODEL_IO_DATA BLOB NOT NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36),
  LAST_UPDATED_ON BIGINT,
  STATUS VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UK_MAPPING_NAME UNIQUE (NAME),
  CONSTRAINT FK_MAPPING_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODEL(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MAPPING_AUD(
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(200),
  MODEL_ID CHAR(36) NULL,
  MODEL_IO_DATA BLOB NULL,
  STATUS VARCHAR(20) NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_MAPPING_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE MAPPING_INPUT (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  MAPPING_ID CHAR(36) NOT NULL,
  MAPPING_DATA BLOB NOT NULL,
  TENANT_INTERFACE_DEFINITION BLOB NOT NULL,
  TENANT_INTF_SYS_DEFINITION BLOB,
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT  UN_MAPPING_INPUT UNIQUE (MAPPING_ID),
  CONSTRAINT FK_MAPPING_INPUT_MAPPING FOREIGN KEY (MAPPING_ID) REFERENCES MAPPING(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE MAPPING_INPUT_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  MAPPING_ID CHAR(36),
  MAPPING_DATA BLOB,
  TENANT_INTERFACE_DEFINITION BLOB,
  TENANT_INTF_SYS_DEFINITION BLOB,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_MAPPING_INPUT_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE MAPPING_OUTPUT (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  MAPPING_ID CHAR(36) NOT NULL,
  MAPPING_DATA	BLOB NOT NULL,
  TENANT_INTERFACE_DEFINITION BLOB NOT NULL,
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UN_MAPPING_OUTPUT UNIQUE (MAPPING_ID),
  CONSTRAINT FK_MAPPING_OUTPUT_MAPPING FOREIGN KEY (MAPPING_ID) REFERENCES MAPPING(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MAPPING_OUTPUT_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  MAPPING_ID CHAR(36),
  MAPPING_DATA	BLOB,
  TENANT_INTERFACE_DEFINITION BLOB,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_MAPPING_OUTPUT_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE SYNDICATE_DATA_QUERY (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  MAPPING_ID CHAR(36),
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(200),
  EXEC_SEQUENCE INT NOT NULL,
  SELECT_COMPONENT VARCHAR(500) NOT NULL,
  FROM_COMPONENT VARCHAR(200) NOT NULL,
  WHERE_COMPONENT VARCHAR(500) NULL,
  ORDER_BY_COMPONENT VARCHAR(100) NULL,
  EXEC_QUERY VARCHAR(500) NOT NULL,
  MAPPING_TYPE VARCHAR(6) NOT NULL,
  ROW_TYPE VARCHAR(8) NOT NULL,
  DATA_TYPE VARCHAR(20) NOT NULL,
  CREATED_BY CHAR(36) NOT NULL, 
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL, 
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_MAPPING FOREIGN KEY(MAPPING_ID) REFERENCES MAPPING(ID)
  );
  --CONSTRAINT FK_QUERY_RESULT_TYPES FOREIGN KEY (SYNDICATE_DATA_QUERY_RESULT_TYPES_TYPE) REFERENCES SYNDICATE_DATA_QUERY_RESULT_TYPES(TYPE_NAME));
  
CREATE TABLE  SYNDICATE_DATA_QUERY_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  MAPPING_ID CHAR(36) NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  EXEC_SEQUENCE INT NOT NULL,
  SELECT_COMPONENT VARCHAR(500) NOT NULL,
  FROM_COMPONENT VARCHAR(200) NOT NULL,
  WHERE_COMPONENT VARCHAR(500) NULL,
  ORDER_BY_COMPONENT VARCHAR(100) NULL,
  EXEC_QUERY VARCHAR(500) NOT NULL,
  MAPPING_TYPE VARCHAR(6) NULL,
  ROW_TYPE VARCHAR(8) NOT NULL,
  DATA_TYPE VARCHAR(6) NOT NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV));

CREATE TABLE  SYNDICATE_DATA_QUERY_INPUTS (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  SYNDICATE_DATA_QUERY_ID CHAR(36) NOT NULL,
  NAME VARCHAR(50) NULL,
  DATA_TYPE VARCHAR(25) NOT NULL,
  SAMPLE_VALUE VARCHAR(50) NULL,
  CREATED_BY CHAR(36) NOT NULL, 
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL, 
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_INPUTS_QUERYS FOREIGN KEY (SYNDICATE_DATA_QUERY_ID) REFERENCES SYNDICATE_DATA_QUERY(ID));
  
CREATE TABLE  SYNDICATE_DATA_QUERY_INPUTS_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  SYNDICATE_DATA_QUERY_ID CHAR(36) NOT NULL,
  NAME VARCHAR(50) NULL,
  DATA_TYPE VARCHAR(25) NULL,
  SAMPLE_VALUE VARCHAR(50) NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_INPUTS_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV));

CREATE TABLE  SYNDICATE_DATA_QUERY_OUTPUTS (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NULL,
  SYNDICATE_DATA_QUERY_ID CHAR(36) NOT NULL,
  NAME VARCHAR(50) NULL,
  DATA_TYPE VARCHAR(25) NULL,
  SEQUENCE INTEGER NOT NULL,
  CREATED_BY CHAR(36) NOT NULL, 
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL, 
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_OUTPUTS_QUERYS FOREIGN KEY (SYNDICATE_DATA_QUERY_ID) REFERENCES SYNDICATE_DATA_QUERY(ID)); 
  
CREATE TABLE  SYNDICATE_DATA_QUERY_OUTPUTS_AUD (
  ID CHAR(36) NOT NULL ,
  TENANT_ID VARCHAR(45) NULL ,
  SYNDICATE_DATA_QUERY_ID CHAR(36) NOT NULL ,
  NAME VARCHAR(50) NULL ,
  DATA_TYPE VARCHAR(25) NULL ,
  SEQUENCE INTEGER NOT NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV));
  
CREATE TABLE UMG_VERSION (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  MAJOR_VERSION INTEGER NOT NULL,
  MINOR_VERSION INTEGER NOT NULL,
  MAPPING_ID CHAR(36) NOT NULL,
  MODEL_LIBRARY_ID CHAR(36) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  VERSION_DESCRIPTION VARCHAR(200) NOT NULL,
  PUBLISHED_ON BIGINT,
  PUBLISHED_BY CHAR(36),
  DEACTIVATED_ON BIGINT,
  DEACTIVATED_BY CHAR(36),
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL
);

CREATE TABLE UMG_VERSION_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(200),
  MAJOR_VERSION INTEGER,
  MINOR_VERSION INTEGER,
  MAPPING_ID CHAR(36),
  MODEL_LIBRARY_ID CHAR(36),
  STATUS VARCHAR(20),
  VERSION_DESCRIPTION VARCHAR(200),
  PUBLISHED_ON BIGINT,
  PUBLISHED_BY CHAR(36),
  DEACTIVATED_ON BIGINT,
  DEACTIVATED_BY CHAR(36),
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID,REV),
  CONSTRAINT FK_UMG_VERSION_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
  
CREATE TABLE UMG_RUNTIME_TRANSACTION (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(36) NOT NULL,
  CLIENT_TRANSACTION_ID VARCHAR(50) NOT NULL,
  LIBRARY_NAME VARCHAR(50) NOT NULL,
  VERSION_NAME VARCHAR(100) NOT NULL,
  MAJOR_VERSION INTEGER NOT NULL,
  MINOR_VERSION INTEGER NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  TENANT_INPUT BLOB NULL,
  TENANT_OUTPUT BLOB NULL,
  MODEL_INPUT BLOB NULL,
  MODEL_OUTPUT BLOB NULL,
  RUN_AS_OF_DATE BIGINT NOT NULL,
  RUNTIME_CALL_START BIGINT,
  RUNTIME_CALL_END BIGINT,
  MODEL_CALL_START BIGINT,
  MODEL_CALL_END BIGINT,
  IS_TEST TINYINT NOT NULL,
  ERROR_CODE CHAR(10),
  ERROR_DESCRIPTION  BLOB NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE UMG_RUNTIME_TRANSACTION_AUD (
  ID CHAR(36) NOT NULL,
  TENANT_ID CHAR(36),
  CLIENT_TRANSACTION_ID VARCHAR(50),
  LIBRARY_NAME VARCHAR(50),
  VERSION_NAME VARCHAR(100),
  MAJOR_VERSION INTEGER,
  MINOR_VERSION INTEGER,
  STATUS VARCHAR(10),
  TENANT_INPUT BLOB,
  TENANT_OUTPUT BLOB,
  MODEL_INPUT BLOB,
  MODEL_OUTPUT BLOB,
  RUN_AS_OF_DATE BIGINT,
  RUNTIME_CALL_START BIGINT,
  RUNTIME_CALL_END BIGINT,
  MODEL_CALL_START BIGINT,
  MODEL_CALL_END BIGINT,
  IS_TEST TINYINT,
  ERROR_CODE CHAR(10),
  ERROR_DESCRIPTION  BLOB NULL,
  CREATED_BY CHAR(36), 
	CREATED_ON BIGINT,
	LAST_UPDATED_BY CHAR(36) NULL, 
	LAST_UPDATED_ON BIGINT NULL,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_UMG_RUNTIME_TRANSACTION_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE table BATCH_TRANSACTION (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(50) NOT NULL,
  BATCH_INPUT_FILE VARCHAR(100) NOT NULL,
  BATCH_OUTPUT_FILE VARCHAR(100) NULL,
  STATUS VARCHAR(25) NOT NULL,
  IS_TEST TINYINT NULL, 
  START_TIME BIGINT NULL, 
  END_TIME BIGINT NULL, 
  TOTAL_RECORDS BIGINT NULL,
  SUCCESS_COUNT BIGINT NULL,
  FAIL_COUNT BIGINT NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS BATCH_TXN_RUNTIME_TXN_MAPPING (
  ID CHAR(36) NOT NULL,
  BATCH_ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(50) NOT NULL,
  TRANSACTION_ID CHAR(36) NOT NULL,
  STATUS VARCHAR(50) NULL,
  ERROR VARCHAR(50) NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  CONSTRAINT FK_BATCH_RUNTIME_TXN_MAPPING_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCH_TRANSACTION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS TRANSPORT_PARAMETER_VALUES (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  TRANSPORT_NAME VARCHAR(45) NOT NULL,
  PARAMETER_NAME VARCHAR(45) NULL,
  PARAMETER_VALUE VARCHAR(45) NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TRANSPORT_TYPES (
  ID CHAR(36) NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID));
  
  CREATE TABLE IF NOT EXISTS TRANSPORT_PARAMETERS (
  ID CHAR(36) NOT NULL,
  TRANSPORT_TYPE_ID VARCHAR(45) NOT NULL,
  PARAMETER_NAME VARCHAR(45) NOT NULL,
  DEFAULT_VALUE VARCHAR(45) NULL,
  CREATED_BY CHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_TRANSPORT_PARAMETERS_TRANSPORT_TYPE FOREIGN KEY (TRANSPORT_TYPE_ID) REFERENCES TRANSPORT_TYPES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION  
  );
  