USE `Ocwen`;

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL DEFAULT Null COMMENT 'Execution Environment(Linux/Windows)' AFTER `MODEL_VERSION`;

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN `MODELLING_ENVIRONMENT` VARCHAR(50) NULL DEFAULT Null COMMENT 'Modelling Environment(R-3.2.1/R-3.3.2/Matlab-7.16)' ;

UPDATE BATCH_TRANSACTION set EXECUTION_ENVIRONMENT='Linux';

UPDATE BATCH_TRANSACTION set MODELLING_ENVIRONMENT='Matlab-7.16' WHERE  MODEL_NAME IN(SELECT NAME FROM MODEL_LIBRARY WHERE MODEL_EXEC_ENV_NAME like 'Matlab%');

UPDATE BATCH_TRANSACTION set MODELLING_ENVIRONMENT='R-3.2.1' WHERE  MODEL_NAME IN(SELECT NAME FROM MODEL_LIBRARY WHERE MODEL_EXEC_ENV_NAME like 'R%');

COMMIT;