USE `umg_admin`;

ALTER TABLE `POOL`
CHANGE COLUMN `EXECUTION_LANGUAGE` `ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT 'Execution language of modelet' COLLATE 'utf8_bin' AFTER `IS_DEFAULT_POOL`,

ALTER TABLE `POOL` DROP COLUMN `EXECUTION_ENVIRONMENT`;


DELETE FROM POOL_CRITERIA WHERE  CRITERIA_NAME='EXECUTION_ENVIRONMENT';

UPDATE POOL_CRITERIA set CRITERIA_NAME = 'ENVIRONMENT' WHERE CRITERIA_NAME = 'EXECUTION_LANGUAGE';
UPDATE POOL_CRITERIA set CRITERIA_NAME = 'ENVIRONMENT_VERSION' WHERE CRITERIA_NAME = 'EXECUTION_LANGUAGE_VERSION';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 3 WHERE CRITERIA_NAME = 'MODEL';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 4 WHERE CRITERIA_NAME = 'MODEL_VERSION';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 5 WHERE CRITERIA_NAME = 'TENANT';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 6 WHERE CRITERIA_NAME = 'TRANSACTION_MODE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 7 WHERE CRITERIA_NAME = 'TRANSACTION_TYPE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 8 WHERE CRITERIA_NAME = 'CHANNEL';

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = TRIM(REPLACE(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE,' & #EXECUTION_ENVIRONMENT# = Linux', ''));

update POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'EXECUTION_LANGUAGE','ENVIRONMENT');

COMMIT;