USE `umg_admin`;

ALTER TABLE `POOL`
CHANGE COLUMN `ENVIRONMENT` `EXECUTION_LANGUAGE` VARCHAR(32) NOT NULL COMMENT 'Execution language of modelet' COLLATE 'utf8_bin' AFTER `IS_DEFAULT_POOL`,
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT 'Execution environment' DEFAULT 'Linux'  AFTER `EXECUTION_LANGUAGE`;

UPDATE POOL_CRITERIA set CRITERIA_NAME = 'EXECUTION_LANGUAGE' WHERE CRITERIA_NAME = 'ENVIRONMENT';
UPDATE POOL_CRITERIA set CRITERIA_NAME = 'EXECUTION_LANGUAGE_VERSION' WHERE CRITERIA_NAME = 'ENVIRONMENT_VERSION';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 4 WHERE CRITERIA_NAME = 'MODEL';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 5 WHERE CRITERIA_NAME = 'MODEL_VERSION';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 6 WHERE CRITERIA_NAME = 'TENANT';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 7 WHERE CRITERIA_NAME = 'TRANSACTION_MODE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 8 WHERE CRITERIA_NAME = 'TRANSACTION_TYPE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 9 WHERE CRITERIA_NAME = 'CHANNEL';

INSERT INTO `POOL_CRITERIA` (`ID`, `CRITERIA_NAME`, `CRITERIA_PRIORITY`) VALUES ('9', 'EXECUTION_ENVIRONMENT', 3);

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'ENVIRONMENT','EXECUTION_LANGUAGE');

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = CONCAT(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE, ' & #EXECUTION_ENVIRONMENT# = Linux');

INSERT INTO `SYSTEM_PARAMETER` (`id`, `sys_key`, `DESCRIPTION`, `SYS_VALUE`, `is_active`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`) 
VALUES ('EE9E19F3-AB0A-4FBC-8935-ACD677A7348F', 'R_MODELET_STARTUP_SCRIPT_WINDOWS', 'modelet script for windows os', 'export LD_LIBRARY_PATH=/usr/lib64/R/library/rJava/jri:/usr/lib64/R/lib:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.85.x86_64/jre/lib/amd64/server; export JAVA_HOME=/usr/bin/java; export R_HOME=/usr/lib64/R/; nohup java -XX:MaxPermSize=256m -Xmx1024m  -Druntime=MATLAB -Dlogroot=#port# -Dloglevel=#port# -Dport=#port# -DserverType=#serverType# -DsanPath=/sanpath -Dworkspace=/opt/umg/matlab_workspace -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -DisThreadContextMapInheritable=true   -Dlog4j.configurationFile=file:/opt/raconf/log4j2.xml -Dhazelcast.config=/opt/raconf/hazelcast-config.xml -DhttpConnectionPooling.properties=file:/opt/raconf/httpConnectionPooling.properties -DrunMatlab=#runMatlab# -DrunR=#runR# -DexecutionEnvironment=Windows -jar /opt/umg/modelet.one-jar.jar > /opt/umg/#port#.out 2>&1 & ', 'Y', NULL, NULL, NULL, NULL);


UPDATE POOL SET `POOL_NAME`='R-Linux-Default' WHERE  `POOL_NAME`='R-Default';

set @POOL_ID :=UUID();
set @priority :=(SELECT MAX(PRIORITY) FROM POOL)+1;

INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `EXECUTION_LANGUAGE`, `EXECUTION_ENVIRONMENT`, `POOL_STATUS`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`, `WAIT_TIMEOUT`) 
VALUES (@POOL_ID, 'R-Windows-Default', 'Windows Default', 1, 'R', 'Windows', NULL, 1, '4GB - Windows 64 bit', @priority, 60000);

INSERT INTO `POOL_CRITERIA_DEF_MAPPING` (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) 
VALUES ('UUID();', @POOL_ID, '#TENANT# = Any & #EXECUTION_LANGUAGE# = R & #EXECUTION_LANGUAGE_VERSION# = 3.2.1& #TRANSACTION_TYPE# = Any & #MODEL# = Any & #MODEL_VERSION# = Any & #TRANSACTION_MODE# = Any & #CHANNEL# = Any & #EXECUTION_ENVIRONMENT# = Windows');

INSERT INTO `POOL_USAGE_ORDER` (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) 
VALUES (@POOL_ID, @POOL_ID, @POOL_ID, 1);

COMMIT;