USE `umg_admin`;

ALTER TABLE `SYSTEM_MODELETS` ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT 'Execution environment' DEFAULT 'Linux'  AFTER `MEMBER_HOST`;

UPDATE POOL SET `POOL_DESCRIPTION`='POOL OF R-Linux-Default' WHERE  `POOL_NAME`='R-Default';
UPDATE POOL SET `POOL_NAME`='R-Linux-Default' WHERE  `POOL_NAME`='R-Default';

UPDATE POOL SET `POOL_DESCRIPTION`='POOL ; Matlab-Linux-Default' WHERE  `POOL_NAME`='Matlab-Default';
UPDATE POOL SET `POOL_NAME`='Matlab-Linux-Default' WHERE  `POOL_NAME`='Matlab-Default';

ALTER TABLE `POOL` DROP INDEX  `UNIQUE_POOL_PRIORITY`;
ALTER TABLE `POOL` ADD UNIQUE INDEX  UNIQUE_POOL_PRIORITY(`PRIORITY`,`EXECUTION_LANGUAGE`,`EXECUTION_ENVIRONMENT`);

SET @ID :=UUID();
INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS` (`ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`, `NAME`) 
VALUES (@ID, 'Excel', '2013', 'sujay.mandal', 1479990810, 'sujay.mandal', 1479990810, 'Excel-2013');

SET @POOL_ID :=UUID();
INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `EXECUTION_LANGUAGE`, `EXECUTION_ENVIRONMENT`, `POOL_STATUS`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`, `WAIT_TIMEOUT`) 
VALUES (@POOL_ID, 'R-Windows-Default', 'POOL OF R-Windows-Default', 1, 'R', 'Windows', NULL, 1, '4GB - Windows 64 bit', 1, 60000);

INSERT INTO `POOL_CRITERIA_DEF_MAPPING` (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) 
VALUES (@POOL_ID, @POOL_ID, '#TENANT# = Any & #EXECUTION_LANGUAGE# = R & #EXECUTION_LANGUAGE_VERSION# = 3.2.1 & #TRANSACTION_TYPE# = Any & #MODEL# = Any & #MODEL_VERSION# = Any & #TRANSACTION_MODE# = Any & #CHANNEL# = Any & #EXECUTION_ENVIRONMENT# = Windows');

INSERT INTO `POOL_USAGE_ORDER` (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) 
VALUES (@POOL_ID, @POOL_ID, @POOL_ID, 1);

SET @POOL_ID :=UUID();
INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `EXECUTION_LANGUAGE`, `EXECUTION_ENVIRONMENT`, `POOL_STATUS`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`, `WAIT_TIMEOUT`) 
VALUES (@POOL_ID, 'Excel-Windows-Default', 'POOL OF Excel-Windows-Default', 1, 'Excel', 'Windows', NULL, 1, '1GB - Windows 64 bit', 1, 60000);

INSERT INTO `POOL_CRITERIA_DEF_MAPPING` (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) 
VALUES (@POOL_ID, @POOL_ID, '#TENANT# = Any & #EXECUTION_LANGUAGE# = Excel & #EXECUTION_LANGUAGE_VERSION# = 2013 & #TRANSACTION_TYPE# = Any & #MODEL# = Any & #MODEL_VERSION# = Any & #TRANSACTION_MODE# = Any & #CHANNEL# = Any & #EXECUTION_ENVIRONMENT# = Windows');

INSERT INTO `POOL_USAGE_ORDER` (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) 
VALUES (@POOL_ID, @POOL_ID, @POOL_ID, 1);

COMMIT;