USE `umg_admin`;

ALTER TABLE `SYSTEM_MODELETS` DROP COLUMN `EXECUTION_ENVIRONMENT`;

UPDATE POOL SET `POOL_NAME`='R-Default' WHERE  `POOL_NAME`='R-Linux-Default';
UPDATE POOL SET `POOL_DESCRIPTION`='POOL OF R-Default' WHERE  `POOL_NAME`='R-Default';

UPDATE POOL SET `POOL_NAME`='Matlab-Default' WHERE  `POOL_NAME`='Matlab-Linux-Default';
UPDATE POOL SET `POOL_DESCRIPTION`='POOL OF Matlab-Default' WHERE  `POOL_NAME`='Matlab-Default';

DELETE FROM `MODEL_EXECUTION_ENVIRONMENTS` WHERE `EXECUTION_ENVIRONMENT` = 'Excel' AND `ENVIRONMENT_VERSION` = '14.0';

DELETE FROM `POOL_USAGE_ORDER` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default');
DELETE FROM `POOL_CRITERIA_DEF_MAPPING` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default');
DELETE FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default';

DELETE FROM `POOL_USAGE_ORDER` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default');
DELETE FROM `POOL_CRITERIA_DEF_MAPPING` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default');
DELETE FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default';

ALTER TABLE `POOL` DROP INDEX  `UNIQUE_POOL_PRIORITY`;
ALTER TABLE `POOL` ADD UNIQUE INDEX  UNIQUE_POOL_PRIORITY(`PRIORITY`,`EXECUTION_LANGUAGE`);

COMMIT;