use `umg_admin`;

ALTER TABLE `SYSTEM_MODELETS` ADD PRIMARY KEY (`HOST_NAME`);
	
ALTER TABLE `SYSTEM_MODELETS` ALTER `EXEC_LANGUAGE` DROP DEFAULT;

ALTER TABLE `SYSTEM_MODELETS`CHANGE COLUMN `EXEC_LANGUAGE` `ENVIRONMENT` VARCHAR(20) NOT NULL AFTER `PORT`,	
DROP COLUMN `POOL_NAME`;