use `umg_admin`;

ALTER TABLE `MODEL_EXEC_PACKAGES`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL DEFAULT 'Linux' AFTER `LAST_UPDATED_ON`;

ALTER TABLE `MODEL_EXEC_PACKAGES_AUDIT`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL DEFAULT 'Linux' AFTER `LAST_UPDATED_ON`;

ALTER TABLE MODEL_EXEC_PACKAGES DROP INDEX  `PACKAGE_FOLDER_VERSION_CONSTRAINT`;

ALTER TABLE MODEL_EXEC_PACKAGES ADD UNIQUE INDEX  PACKAGE_FOLDER_VERSION_ENV_CONSTRAINT(`PACKAGE_FOLDER`,`PACKAGE_VERSION`,`EXECUTION_ENVIRONMENT`);