

DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'dp.email.output.file.smtp.server';
DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'dp.email.output.file.smtp.host';
DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'ra.report.url';
DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'ra.admin.base.url';
DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'ra.admin.url';
DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'ra.runtime.url';