use Ocwen;
delete from UMG_RUNTIME_TRANSACTION where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from UMG_RUNTIME_TRANSACTION_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_REPORT_STATUS where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_REPORT_TEMPLATE_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_REPORT_TEMPLATE where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from UMG_VERSION_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from UMG_VERSION where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY_INPUTS where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY_INPUTS_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY_OUTPUTS where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from SYNDICATE_DATA_QUERY_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MAPPING_INPUT_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MAPPING_INPUT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MAPPING_OUTPUT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MAPPING_OUTPUT_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MAPPING where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
DELETE from MAPPING_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_LIBRARY where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_LIBRARY_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_DEFINITION where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_DEFINITION_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from MODEL_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from BATCH_TXN_RUNTIME_TXN_MAPPING where TENANT_ID NOT IN ('demo','hubzu','automation','denverr');
delete from BATCH_TRANSACTION where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MEDIATE_MODEL_LIBRARY where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MEDIATE_MODEL_LIBRARY_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MIGRATION_LOG where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_EXECUTION_ENVIRONMENTS_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_EXECUTION_ENVIRONMENTS where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_EXEC_PACKAGES_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_EXEC_PACKAGES where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_LIB_EXEC_PKG_MAPPING_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_LIB_EXEC_PKG_MAPPING where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_REPORT_STATUS where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_REPORT_TEMPLATE where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_REPORT_TEMPLATE_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_SUPPORT_PACKAGE_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from MODEL_SUPPORT_PACKAGE where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from SYNDICATE_DATA_QUERY_RESULT_TYPES where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from UMG_RUNTIME_TRANSACTION_AUDIT where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from UMG_RUNTIME_TRANSACTION where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
delete from USAGE_SEARCH_REQUEST_CANCEL where TENANT_ID NOT IN ('demo','hubzu','automation','denverr') ;
