USE umg_admin;

DROP TABLE IF EXISTS POOL_USAGE_ORDER;
DROP TABLE IF EXISTS POOL_CRITERIA_DEF_MAPPING;
DROP TABLE IF EXISTS POOL;
DROP TABLE IF EXISTS POOL_CRITERIA;


CREATE TABLE POOL (
  ID varchar(50) NOT NULL COMMENT 'Pool id',
  POOL_NAME varchar(50) NOT NULL COMMENT 'Priority Pool Name',
  POOL_DESCRIPTION varchar(100) DEFAULT NULL COMMENT 'Priority Pool Description',
  IS_BATCH_POOL boolean DEFAULT false COMMENT 'Flag to indicate whether it is for batch pool or not',
  BATCH_STATUS varchar(25) DEFAULT NULL COMMENT 'Batch Status like SUCCESS, ERROR etc',
  PRIMARY KEY (ID)
);


INSERT INTO POOL (ID, POOL_NAME, IS_BATCH_POOL, POOL_DESCRIPTION) VALUES
	('1', 'ONLINE_POOL', false, 'POOL OF MODELETS FOR ONLINE REQUETS'),
	('2', 'BATCH_POOL', true, 'POOL OF MODELETS FOR BATCH REQUETS'),
	('3', 'DEFAULT_POOL', false, 'POOL OF DEFAULT MODELETS');


CREATE TABLE POOL_CRITERIA (
  ID varchar(50) NOT NULL COMMENT 'pool criteria id',
  CRITERIA_NAME varchar(100) NOT NULL COMMENT 'pool criteria name',
  CRITERIA_ORDER int(10) NOT NULL COMMENT 'criteria order',
  PRIMARY KEY (ID)
) COMMENT='Priority pool criterias';


INSERT INTO POOL_CRITERIA (ID, CRITERIA_NAME, CRITERIA_ORDER) VALUES
	('1', 'TENANT', 1),
	('2', 'ENVIRONMENT', 2),
	('3', 'ENVIRONMENT_VERSION', 3),
	('4', 'TRANSACTION_TYPE', 4);


CREATE TABLE POOL_CRITERIA_DEF_MAPPING (
  ID varchar(50) NOT NULL,
  POOL_ID varchar(50) NOT NULL,
  POOL_CRITERIA_VALUE varchar(200) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY FK_UNIQUE_CRITERIA (POOL_ID,POOL_CRITERIA_VALUE),
  CONSTRAINT FK_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES POOL (ID)
);

INSERT INTO POOL_CRITERIA_DEF_MAPPING (ID, POOL_ID, POOL_CRITERIA_VALUE) VALUES
    ('1', '1', 'TENANT = OCWEN AND ENVIRONMENT = MATLAB AND ENVIRONMENT_VERSION = 7.16 AND TRANSACTION_TYPE = ONLINE'),
	('2', '2', 'TENANT = OCWEN AND ENVIRONMENT = MATLAB AND ENVIRONMENT_VERSION = 7.16 AND TRANSACTION_TYPE = BATCH'),
	('3', '1', 'TENANT = ocwen AND ENVIRONMENT = R AND ENVIRONMENT_VERSION = 3.1.2 AND TRANSACTION_TYPE = ONLINE'),
	('4', '2', 'TENANT = ocwen AND ENVIRONMENT = R AND ENVIRONMENT_VERSION = 3.1.2 AND TRANSACTION_TYPE = BATCH');


CREATE TABLE IF NOT EXISTS POOL_USAGE_ORDER (
  ID varchar(50) NOT NULL,
  POOL_ID varchar(50) NOT NULL,
  POOL_USAGE_ID varchar(50) NOT NULL,
  POOL_TRY_ORDER int(10) NOT NULL,
  PRIMARY KEY (ID),
  KEY FKPOOL_ID (POOL_ID),
  CONSTRAINT FKPOOL_ID FOREIGN KEY (POOL_ID) REFERENCES POOL (ID)
);

INSERT INTO POOL_USAGE_ORDER (ID, POOL_ID, POOL_USAGE_ID, POOL_TRY_ORDER) VALUES
	('1', '1', '1', 1),
	('2', '1', '2', 2),
	('3', '1', '3', 3),

	('4', '2', '2', 1),
	('5', '2', '3', 2);

COMMIT;