

SELECT ID from `RA_TNT_APPS` WHERE `NAME` = 'DPA' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'ocn.dp.auth.token', 'hubzu.3a281db3-55bd-4a63-9666-d496bfc6ca42', 'OCN', 'SYSTEM', NOW());
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'nrz.dp.auth.token', 'hubzu.3a281db3-55bd-4a63-9666-d496bfc6ca42', 'NRZ', 'SYSTEM', NOW());
