
ALTER TABLE `DP_WEEKN_PARAMS`
	ADD COLUMN `DATE_OF_LAST_REDUCTION` VARCHAR(50) NULL DEFAULT NULL AFTER `LIST_STTS_DTLS_VC`;
	
ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL`
	ADD COLUMN `DATE_OF_LAST_REDUCTION` VARCHAR(50) NULL DEFAULT NULL AFTER `LIST_STTS_DTLS_VC`;
