use Ocwen;

CREATE TABLE MODEL_REPORT_TEMPLATE (
  `ID` CHAR(36) NOT NULL,
  `UMG_VERSION_ID` CHAR(36) NOT NULL,
  `TENANT_ID` CHAR(36) NOT NULL,
  `NAME` VARCHAR(128) NULL,
  `DESCRIPTION` VARCHAR(256) NULL,
  `IS_ACTIVE` INT(11) NOT NULL,
  `TEMPLATE_FILE_NAME` VARCHAR(256) NOT NULL,
  `TEMPLATE_DEFINATION` MEDIUMBLOB NOT NULL,
  `COMPILED_DEFINATION` MEDIUMBLOB NULL,
  `MAJOR_VERSION` INT NULL,
  `REPORT_TYPE` VARCHAR(45) NOT NULL,
  `REPORT_ENGINE` VARCHAR(45) NOT NULL,
  `CREATED_BY` VARCHAR(126) NOT NULL,
  `CREATED_ON` BIGINT(20) NOT NULL,
  `LAST_UPDATED_BY` VARCHAR(126) NOT NULL,
  `LAST_UPDATED_ON` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `VERSION_INDEX` (`TENANT_ID` ASC, `UMG_VERSION_ID` ASC))
COMMENT = 'Stores report template for each model';

CREATE TABLE MODEL_REPORT_TEMPLATE_AUDIT (
  `ID` CHAR(36) NOT NULL,
  `UMG_VERSION_ID` CHAR(36) NOT NULL,
  `TENANT_ID` CHAR(36) NOT NULL,
  `NAME` VARCHAR(128) NULL,
  `DESCRIPTION` VARCHAR(256) NULL,
  `IS_ACTIVE` INT(11) NOT NULL,	
  `TEMPLATE_FILE_NAME` VARCHAR(256) NOT NULL,
  `TEMPLATE_DEFINATION` MEDIUMBLOB NOT NULL,
  `COMPILED_DEFINATION` MEDIUMBLOB NULL,
  `MAJOR_VERSION` INT NULL,
  `REPORT_TYPE` VARCHAR(45) NULL,
  `REPORT_ENGINE` VARCHAR(45) NOT NULL,
  `CREATED_BY` VARCHAR(126) NOT NULL,
  `CREATED_ON` BIGINT(20) NOT NULL,
  `LAST_UPDATED_BY` VARCHAR(126) NOT NULL,
  `LAST_UPDATED_ON` BIGINT(20) NOT NULL,
  `REV` INT(11),
  `REVTYPE` TINYINT(4), 
  PRIMARY KEY (`ID`, `REV`),
  INDEX `VERSION_INDEX` (`TENANT_ID` ASC, `UMG_VERSION_ID` ASC))
COMMENT = 'Audit table to stores report template for each model';

CREATE TABLE MODEL_REPORT_STATUS (
  `ID` CHAR(36) NOT NULL,
  `REPORT_TEMPLATE_ID` CHAR(36) NOT NULL,
  `UMG_TRANSACTION_ID` CHAR(36) NOT NULL,
  `TENANT_ID` CHAR(36) NOT NULL,
  `REPORT_URL` VARCHAR(256) NOT NULL,
  `REPORT_LOCATION` VARCHAR(256) NOT NULL,
  `REPORT_FILE_NAME` VARCHAR(256),
  `EXECUTION_STATUS` VARCHAR(45) NOT NULL,
  `CREATED_BY` VARCHAR(126) NOT NULL,
  `CREATED_ON` BIGINT(20) NOT NULL,
  `LAST_UPDATED_BY` VARCHAR(126) NOT NULL,
  `LAST_UPDATED_ON` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TRANSACTION_INDEX` (`TENANT_ID` ASC, `UMG_TRANSACTION_ID` ASC),
  INDEX `REPORT_TEMPLATE_INDXE` (`REPORT_TEMPLATE_ID` ASC))
 COMMENT = 'Table to store details of generated report';
 
COMMIT;