-- USE 'tenant schema';
USE ocwen;

ALTER TABLE MODEL_LIBRARY ADD COLUMN `R_MANIFEST_FILE_NAME` VARCHAR(200) NULL COMMENT 'R Manifest file name' COLLATE 'utf8_bin';

ALTER TABLE MODEL_LIBRARY_AUDIT ADD COLUMN `R_MANIFEST_FILE_NAME` VARCHAR(200) NULL COMMENT 'R Manifest file name' COLLATE 'utf8_bin';

ALTER TABLE `MODEL_LIBRARY` ADD COLUMN `PACKAGE_NAME` VARCHAR(200) NULL;

ALTER TABLE `MODEL_LIBRARY_AUDIT` ADD COLUMN `PACKAGE_NAME` VARCHAR(200) NULL;

ALTER TABLE MODEL ADD IO_DEF_EXCEL_NAME VARCHAR(100) NULL COMMENT 'Name of the Excel file uploaded. Useed to show on UI.' COLLATE 'utf8_bin';

ALTER TABLE MODEL_AUDIT ADD IO_DEF_EXCEL_NAME VARCHAR(100) NULL COMMENT 'Name of the Excel file uploaded. Useed to show on UI.' COLLATE 'utf8_bin';


CREATE TABLE `MODEL_EXECUTION_ENVIRONMENTS` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL COMMENT 'Model execution environment.' COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(50) NOT NULL COMMENT 'Version of the execution environment.' COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UN_TENANT_ID_EXEC_ENV_VERSION` (`TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`)
)
COMMENT='Table to store Model execution environment and version'
COLLATE='utf8_bin'
ENGINE=InnoDB;

CREATE TABLE `MODEL_EXECUTION_ENVIRONMENTS_AUDIT` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NULL DEFAULT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`EXECUTION_ENVIRONMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Model execution environment.' COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Version of the execution environment.' COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_MODEL_EXEC_ENV_REV_ID` (`REV`),
	CONSTRAINT `FK_MODEL_EXEC_ENV_REV_ID` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
)
COMMENT='Table to store Model execution language and descriptions'
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;

CREATE TABLE `MODEL_EXEC_PACKAGES` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_EXEC_ENV_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(200) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(200) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_VERSION` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_TYPE` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`COMPILED_OS` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `TENANT_ID_MODEL_EXEC_ENV_ID_PKG_VERSION` (`TENANT_ID`, `MODEL_EXEC_ENV_ID`, `PACKAGE_FOLDER`, `PACKAGE_VERSION`),
	INDEX `FK_MODEL_EXECUTION_ENV_ID` (`MODEL_EXEC_ENV_ID`),
	CONSTRAINT `FK_MODEL_EXEC_ENV_ID` FOREIGN KEY (`MODEL_EXEC_ENV_ID`) REFERENCES `MODEL_EXECUTION_ENVIRONMENTS` (`ID`)
)
COMMENT='Table to store model execution environment base packages'
COLLATE='utf8_bin'
ENGINE=InnoDB;


CREATE TABLE `MODEL_EXEC_PACKAGES_AUDIT` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NULL DEFAULT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_VERSION` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_TYPE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`COMPILED_OS` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	`CREATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FKMODEL_EXEC_ENV_REV` (`REV`),
	CONSTRAINT `FKMODEL_EXEC_ENV_REV` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
)
COMMENT='Table to store model execution environment base packages'
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;


SELECT @tenantcode_ocwen:=(SELECT CODE FROM umg_admin.TENANT WHERE CODE='ocwen');

INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS` (`ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('C7642E72-DE1B-4E5B-B1B1-0C70E1B3BCA6', @tenantcode_ocwen, 'Matlab', '7.16', 'nagamani.basa', 1433246416, 'nagamani.basa', 1433246416);
INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS` (`ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('F6ACD2A3-D78D-4E36-A2D8-7420F7CF7537', @tenantcode_ocwen, 'R', '3.1.2', 'nagamani.basa', 1433246416, 'nagamani.basa', 1433246416);



SELECT @MAXREV:=(select max(REV) from REVINFO)+1;
INSERT INTO `REVINFO` (`REV`, `REVTSTMP`, `REVBY`) VALUES (@MAXREV, 1418730666011, 'nagamani.basa');

INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS_AUDIT` (`ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`, `REV`, `REVTYPE`) VALUES ('C7642E72-DE1B-4E5B-B1B1-0C70E1B3BCA6', @tenantcode_ocwen, 'Matlab', '7.16', 'nagamani.basa', 1433246416, 'nagamani.basa', 1433246416, @MAXREV, 0);

SELECT @MAXREV:=(select max(REV) from REVINFO)+1;
INSERT INTO `REVINFO` (`REV`, `REVTSTMP`, `REVBY`) VALUES (@MAXREV, 1418730666011, 'nagamani.basa');

INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS_AUDIT` (`ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`, `REV`, `REVTYPE`) VALUES ('F6ACD2A3-D78D-4E36-A2D8-7420F7CF7537', @tenantcode_ocwen, 'R', '3.1.2', 'nagamani.basa', 1433246416, 'nagamani.basa', 1433246416, @MAXREV, 0);


CREATE TABLE `MODEL_LIB_EXEC_PKG_MAPPING` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_LIBRARY_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_PKG_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`EXEC_SEQUENCE` INT(11) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_MODEL_EXEC_PKG_ID` (`MODEL_EXEC_PKG_ID`),
	INDEX `FK_MODEL_LIBRARY_ID` (`MODEL_LIBRARY_ID`),
	CONSTRAINT `FK_MODEL_EXEC_PKG_ID` FOREIGN KEY (`MODEL_EXEC_PKG_ID`) REFERENCES `MODEL_EXEC_PACKAGES` (`ID`),
	CONSTRAINT `FK_MODEL_LIBRARY_ID` FOREIGN KEY (`MODEL_LIBRARY_ID`) REFERENCES `MODEL_LIBRARY` (`ID`)
)
COMMENT='Mapping table to hold model library and execution package'
COLLATE='utf8_bin'
ENGINE=InnoDB;



CREATE TABLE `MODEL_LIB_EXEC_PKG_MAPPING_AUDIT` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NULL DEFAULT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_LIBRARY_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_PKG_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`EXEC_SEQUENCE` INT(11) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_MODEL_LIB_EXEC_PKG_REV` (`REV`),
	CONSTRAINT `FK_MODEL_LIB_EXEC_PKG_REV` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
)
COMMENT='Mapping table to hold model library and execution package'
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;

ALTER TABLE `MODEL_LIBRARY`
ADD COLUMN `MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL AFTER `LAST_UPDATED_ON`,
ADD CONSTRAINT `FKMODEL_EXEC_ENV_ID` FOREIGN KEY (`MODEL_EXEC_ENV_ID`) REFERENCES `MODEL_EXECUTION_ENVIRONMENTS` (`ID`);

UPDATE `MODEL_LIBRARY` SET MODEL_EXEC_ENV_ID = (SELECT ID FROM MODEL_EXECUTION_ENVIRONMENTS WHERE EXECUTION_ENVIRONMENT = 'Matlab' AND ENVIRONMENT_VERSION = '7.16') WHERE EXECUTION_LANGUAGE = 'Matlab';
UPDATE `MODEL_LIBRARY` SET MODEL_EXEC_ENV_ID = (SELECT ID FROM MODEL_EXECUTION_ENVIRONMENTS WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION = '3.1.2') WHERE EXECUTION_LANGUAGE = 'R';

ALTER TABLE `MODEL_LIBRARY_AUDIT`
ADD COLUMN `MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL AFTER `REVTYPE`;

commit;