use umg_admin;

DELETE COMMAND WHERE NAME='validateRManifestFile';
DELETE COMMAND WHERE NAME='convertExcelToXml';

UPDATE COMMAND SET EXECUTION_SEQUENCE=3 WHERE NAME='validateModelIOXml';
UPDATE COMMAND SET EXECUTION_SEQUENCE=4 WHERE NAME='symanticCheckModelIOXml';
UPDATE COMMAND SET EXECUTION_SEQUENCE=5 WHERE NAME='createModel';
UPDATE COMMAND SET EXECUTION_SEQUENCE=6 WHERE NAME='createMapping';
UPDATE COMMAND SET EXECUTION_SEQUENCE=7 WHERE NAME='createVersion';
UPDATE COMMAND SET EXECUTION_SEQUENCE=8 WHERE NAME='generateTestInput';
UPDATE COMMAND SET EXECUTION_SEQUENCE=9 WHERE NAME='testVersion';
UPDATE COMMAND SET EXECUTION_SEQUENCE=1 WHERE NAME='validateLibraryChecksum';
UPDATE COMMAND SET EXECUTION_SEQUENCE=2 WHERE NAME='createModelLibrary';

commit;
