use Ocwen;

ALTER TABLE MIGRATION_LOG CHANGE COLUMN MIGRATION_TYPE MIGRATION_TYPE VARCHAR(10) NOT NULL;

ALTER TABLE MIGRATION_LOG DROP COLUMN IMPORT_FILE_NAME;

ALTER TABLE BATCH_TRANSACTION DROP COLUMN TERMINATE_COUNT;

COMMIT;