use `Ocwen`;

ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN TRANSACTION_MODE; 
ALTER TABLE UMG_RUNTIME_TRANSACTION_AUDIT DROP COLUMN TRANSACTION_MODE;

ALTER TABLE UMG_VERSION DROP COLUMN MODEL_TYPE;
ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN MODEL_TYPE;

ALTER TABLE BATCH_TRANSACTION DROP COLUMN TRANSACTION_MODE;

commit;
