ALTER TABLE MODEL_LIBRARY_AUDIT 
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE MAPPING_AUDIT 
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_INPUTS_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_LIBRARY_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_DEFINITION_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MAPPING_OUTPUT_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MAPPING_INPUT_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  UMG_RUNTIME_TRANSACTION_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  UMG_VERSION_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;