/*The following scripts need to execute in ocwen schema also.*/
ALTER TABLE MAPPING_INPUT modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING_INPUT modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MAPPING modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING_OUTPUT modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL_DEFINITION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL_LIBRARY modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE UMG_RUNTIME_TRANSACTION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE UMG_VERSION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MAPPING_OUTPUT modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL_DEFINITION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL_LIBRARY modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE UMG_RUNTIME_TRANSACTION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE UMG_VERSION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;