

SELECT ID from RA_TNT_APPS WHERE LOWER(code) = 'dpa' INTO @APP_ID;
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'RR_REODATE_QUERY', 'SELECT LOAN_NUM, REO_DT, UPB FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE PROP_TEMP = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY', NULL, 'SYSTEM', NOW()); 
