

CREATE TABLE `DP_SOP_WEEK0_PRCS_STATUS` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '',
	`STATUS` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEK0_PARAMS_ORIGINAL` (
	`ID` CHAR(36) NOT NULL,
	`ASSET_NUMBER` VARCHAR(100) NULL DEFAULT NULL,
	`STATE` VARCHAR(2) NULL DEFAULT NULL,
	`PROPERTY_TYPE` VARCHAR(10) NULL DEFAULT NULL,
	`STATUS` VARCHAR(50) NULL DEFAULT NULL,
	`ASSET_VALUE` DECIMAL(10,0) NULL DEFAULT NULL,
	`AV_SET_DATE` VARCHAR(10) NULL DEFAULT NULL,
	`REO_DATE` VARCHAR(10) NOT NULL,
	`LIST_PRICE` DECIMAL(19,2) NULL DEFAULT NULL,
	`CLASSIFICATION` VARCHAR(10) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEK0_PARAMS` (
	`ID` CHAR(36) NOT NULL,
	`DP_SOP_WEEK0_FILE_ID` CHAR(36) NOT NULL,
	`ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`STATE` VARCHAR(2) NOT NULL,
	`PROPERTY_TYPE` VARCHAR(10) NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	`ASSET_VALUE` DECIMAL(10,0) NOT NULL,
	`AV_SET_DATE` VARCHAR(10) NOT NULL,
	`REO_DATE` VARCHAR(10) NOT NULL,
	`LIST_PRICE` DECIMAL(10,0) NOT NULL,
	`CLASSIFICATION` VARCHAR(10) NOT NULL,
	`ELIGIBLE` VARCHAR(100) NULL DEFAULT NULL,
	`NOTES` VARCHAR(500) NULL DEFAULT NULL,
	`ERROR_DETAIL` VARCHAR(1000) NULL DEFAULT NULL,
	`SOP_WEEK0_ORIGINAL_ID` CHAR(36) NULL DEFAULT NULL,
	`FAILED_STEP_COMMAND_ID` CHAR(36) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `DP_SOP_INPUT_FILE_ID_FK` FOREIGN KEY (`DP_SOP_WEEK0_FILE_ID`) REFERENCES `DP_SOP_WEEK0_PRCS_STATUS` (`ID`),
	CONSTRAINT `FAILED_STEP_COMMAND_ID_FK` FOREIGN KEY (`FAILED_STEP_COMMAND_ID`) REFERENCES `COMMAND` (`ID`),
	CONSTRAINT `SOP_WEEK0_ID_FK` FOREIGN KEY (`SOP_WEEK0_ORIGINAL_ID`) REFERENCES `DP_SOP_WEEK0_PARAMS_ORIGINAL` (`ID`)
)ENGINE=InnoDB;