CREATE TABLE MODEL_DEFINITION (
	ID CHAR(36) NOT NULL, 
	TENANT_ID CHAR(36) NULL COMMENT 'Tenant code for the record',
	IO_TYPE VARCHAR(50) NOT NULL COMMENT 'Type of model definition text/xml or application/json',
	IO_DEFINITION BLOB NOT NULL COMMENT 'The actual input output defintion for the model.', 
	MODEL_ID CHAR(36) NOT NULL COMMENT 'The model to which this definition belongs.',
	CREATED_BY CHAR(36) NOT NULL, 
	CREATED_ON BIGINT(20) NOT NULL,
	LAST_UPDATED_BY CHAR(36) NULL DEFAULT NULL, 
	LAST_UPDATED_ON BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	INDEX IDX_MODEL_ID (MODEL_ID),
	CONSTRAINT FK_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODEL (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COMMENT='The table which contains the individual model definitions'
DEFAULT CHARSET=utf8
COLLATE='utf8_bin'
ENGINE=InnoDB;