

UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=2 WHERE  `NAME`='weekNZipStateFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=3 WHERE  `NAME`='weekNSSPmiFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=4 WHERE  `NAME`='weekNSOPFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=5 WHERE  `NAME`='weekNRAIntegrarion';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=6 WHERE  `NAME`='weekNOutputFileCreate';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=7 WHERE  `NAME`='weekNEmailIntegration';

DELETE FROM `COMMAND` WHERE `NAME` = 'weekNAssignmentFilter';