

SELECT ID from RA_TNT_APPS WHERE LOWER(code) = 'dpa' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'RR_MIGRATION_QUERY', 'SELECT LOAN_NUM, OLD_RR_LOAN_NUM, PROP_TEMP FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE LOAN_NUM = ? OR OLD_RR_LOAN_NUM = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY', NULL, 'SYSTEM', NOW(), 'SYSTEM', NOW());