ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `OLD_ASSET_NUMBER` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` ADD COLUMN `OLD_ASSET_NUMBER` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS` ADD COLUMN `OLD_ASSET_NUMBER` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS_ORIGINAL` ADD COLUMN `OLD_ASSET_NUMBER` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_AUDIT_REPORTS` ADD COLUMN `OLD_LOAN_NUMBER` VARCHAR(36) NULL DEFAULT NULL AFTER `LOAN_NUMBER`;

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT LOAN_NUM,  AS_OF_DT,  FC_INVENTORY_FLAG,  NRZ_ACQUISITION_DT, SPECIAL_SERVICING_FLAG, PMI_FLAG, PROP_TEMP, NEW_MSP_LOAN_NUM, CLIENT_ID  FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE PROP_TEMP = ? OR NEW_MSP_LOAN_NUM = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY' WHERE  `ATTR_KEY`='RR_CLASSIFICATION_QUERY';

DROP TABLE IF EXISTS `DP_MIGRATION_MAP`;
CREATE TABLE IF NOT EXISTS `DP_MIGRATION_MAP` (
  `ID` char(36) NOT NULL,
  `LOAN_NUMBER` char(36) NOT NULL,
  `NEW_LOAN_NUMBER` char(36) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY LOAN (LOAN_NUMBER),
  UNIQUE KEY NEW_LOAN (NEW_LOAN_NUMBER)
  ) ENGINE=InnoDB;
  
UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST, RRRBPMMS_PROP OT WHERE (RBID_PROP_ID_VC_FK, TO_DATE(LIST_STRT_DATE_DT_NN)) IN (SELECT RBID_PROP_ID_VC_FK, MAX(TO_DATE(LIST_STRT_DATE_DT_NN)) FROM RRRBPMTX_PROP_LIST WHERE TO_DATE(LIST_STRT_DATE_DT_NN) BETWEEN TO_DATE(?) AND TO_DATE(?) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) GROUP BY RBID_PROP_ID_VC_FK) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) AND LIST_TYPE_ID_VC_FK = \'AUCN\' AND OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND TO_DATE(LIST_END_DATE_DT_NN) < TO_DATE(?) AND RBID_PROP_ID_VC_FK = OT.RBID_PROP_ID_VC_PK AND OT.PROP_STTS_ID_VC_FK != \'DELETED\'' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY';