UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST WHERE (RBID_PROP_ID_VC_FK, TO_DATE(LIST_STRT_DATE_DT_NN)) IN (SELECT RBID_PROP_ID_VC_FK, MAX(TO_DATE(LIST_STRT_DATE_DT_NN)) FROM RRRBPMTX_PROP_LIST WHERE TO_DATE(LIST_STRT_DATE_DT_NN) BETWEEN TO_DATE(?) AND TO_DATE(?) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) GROUP BY RBID_PROP_ID_VC_FK) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) AND LIST_TYPE_ID_VC_FK = \'AUCN\' AND OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND TO_DATE(LIST_END_DATE_DT_NN) < TO_DATE(?)' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY';

DROP TABLE IF EXISTS `DP_MIGRATION_MAP`;

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='select fc_inventory_flag, nrz_acquisition_dt from shahmayu.reo_portfolio_master where prop_temp = ? and nrz_acquisition_dt is not null and fc_inventory_flag in (1,2)' WHERE  `ATTR_KEY`='RR_CLASSIFICATION_QUERY';

ALTER TABLE `DP_WEEKN_PARAMS` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS_ORIGINAL` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_AUDIT_REPORTS` DROP COLUMN `OLD_LOAN_NUMBER`;