DROP TABLE IF EXISTS UMG_VERSION_AUDIT;
DROP TABLE IF EXISTS UMG_VERSION;

DROP TABLE IF EXISTS MAPPING_INPUT_AUDIT;
DROP TABLE IF EXISTS MAPPING_INPUT;

DROP TABLE IF EXISTS MAPPING_OUTPUT_AUDIT;
DROP TABLE IF EXISTS MAPPING_OUTPUT;

DROP TABLE IF EXISTS MAPPING_AUDIT;
DROP TABLE IF EXISTS MAPPING;

DROP TABLE IF EXISTS MODEL_DEFINITION_AUDIT;
DROP TABLE IF EXISTS MODEL_DEFINITION;

DROP TABLE IF EXISTS MODEL_AUDIT;
DROP TABLE IF EXISTS MODEL;

DROP TABLE IF EXISTS MODEL_LIBRARY_AUDIT;
DROP TABLE IF EXISTS MODEL_LIBRARY;

DROP TABLE IF EXISTS UMG_RUNTIME_TRANSACTION_AUDIT;
DROP TABLE IF EXISTS UMG_RUNTIME_TRANSACTION;

DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_INPUTS_AUDIT ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_AUDIT ;

DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_RESULT_TYPES ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_OUTPUTS ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY_INPUTS ;
DROP TABLE IF EXISTS SYNDICATE_DATA_QUERY ;

DROP TABLE IF EXISTS REVINFO;

source tables/REVINFO.sql;

source tables/MODEL_LIBRARY/MODEL_LIBRARY.sql;
source tables/MODEL_LIBRARY/MODEL_LIBRARY_AUDIT.sql;

source tables/MODEL/MODEL.sql;
source tables/MODEL/MODEL_AUDIT.sql;

source tables/MODEL_DEFINITION/MODEL_DEFINITION.sql;
source tables/MODEL_DEFINITION/MODEL_DEFINITION_AUDIT.sql;

source tables/MAPPING/MAPPING.sql;
source tables/MAPPING/MAPPING_AUDIT.sql;

source tables/MAPPING_INPUT/MAPPING_INPUT.sql;
source tables/MAPPING_INPUT/MAPPING_INPUT_AUDIT.sql;

source tables/MAPPING_OUTPUT/MAPPING_OUTPUT.sql;
source tables/MAPPING_OUTPUT/MAPPING_OUTPUT_AUDIT.sql;

source tables/SYNDICATE_DATA_QUERY/QUERY.sql;
source tables/SYNDICATE_DATA_QUERY/QUERY_AUDIT.sql;

source tables/UMG_RUNTIME_TRANSACTION/UMG_RUNTIME_TRANSACTION.sql;
source tables/UMG_RUNTIME_TRANSACTION/UMG_RUNTIME_TRANSACTION_AUDIT.sql;

source tables/UMG_VERSION/UMG_VERSION.sql;
source tables/UMG_VERSION/UMG_VERSION_AUDIT.sql;

source data/all_delete.sql;
source data/system_data.sql;