ALTER TABLE MODEL ADD COLUMN `ALLOW_NULL` TINYINT(4) NOT NULL DEFAULT 1
COMMENT 'Flag to know whether to allow nulls or not' AFTER DOC_NAME;

ALTER TABLE MODEL_AUDIT ADD COLUMN `ALLOW_NULL` TINYINT(4) NOT NULL AFTER DOC_NAME;

