

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'SS_PMI_HUBZU_QUERY', 'SELECT SELR_PROP_ID_VC_NN, CLNT_CODE_VC FROM RRRBPMMS_PROP WHERE RBID_PROP_ID_VC_PK IN (:idList)', 'SYSTEM', NOW());

DELETE FROM `RA_TNT_APP_PARAMS` WHERE  `ATTR_KEY`='SS_RR_QUERY';
