USE umg_admin;
	
ALTER TABLE `POOL_CRITERIA` DROP COLUMN `CRITERIA_PRIORITY`;
	
UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TENANT', 'tenantCode');

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'ENVIRONMENT_VERSION', 'executionEnvironmentVersion' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'ENVIRONMENT', 'executionEnvironment' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TRANSACTION_TYPE', 'transactionRequestType');

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'MODEL_VERSION', 'modelVersion' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'MODEL', 'modelName' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'TRANSACTION_MODE', 'transactionRequestMode' );
	
COMMIT;