USE umg_admin;

DROP TABLE IF EXISTS `POOL_CRITERIA`;
CREATE TABLE IF NOT EXISTS `POOL_CRITERIA` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'pool criteria id',
  `CRITERIA_NAME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT 'pool criteria name',
  `CRITERIA_PRIORITY` int(11) NOT NULL COMMENT 'citeria priority used in sorting the pool definition for selection',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_POOL_CRITERIA` (`CRITERIA_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Priority pool criterias';

INSERT INTO `POOL_CRITERIA` (`ID`, `CRITERIA_NAME`, `CRITERIA_PRIORITY`) VALUES
	('1', 'TENANT', 5),
	('2', 'ENVIRONMENT', 1),
	('3', 'ENVIRONMENT_VERSION', 2),
	('4', 'TRANSACTION_TYPE', 6),
	('5', 'TRANSACTION_MODE', 7),
	('6', 'MODEL', 3),
	('7', 'MODEL_VERSION', 4);
	
UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'tenantCode', 'TENANT' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'executionEnvironmentVersion', 'ENVIRONMENT_VERSION' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'executionEnvironment', 'ENVIRONMENT' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'transactionRequestType', 'TRANSACTION_TYPE' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'modelName', 'MODEL' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'modelVersion', 'MODEL_VERSION' );

UPDATE `POOL_CRITERIA_DEF_MAPPING` p
SET p.POOL_CRITERIA_VALUE = 
REPLACE (POOL_CRITERIA_VALUE, 'transactionRequestMode', 'TRANSACTION_MODE' );
	
COMMIT;