package com.fa.dp.business.validation.file.header.constant.qaReports;

/**
 * @author misprakh
 * QA Reports input file Header column values
 */
public enum DPQAReportHeader {

	SELR_PROP_ID_VC_NN("SELR_PROP_ID_VC_NN"),
	RBID_PROP_ID_VC_PK("RBID_PROP_ID_VC_PK"),
	REO_PROP_STTS_VC("REO_PROP_STTS_VC"),
	PROP_SOLD_DATE_DT("PROP_SOLD_DATE_DT"),
	PROP_STTS_ID_VC_FK("PROP_STTS_ID_VC_FK"),
	RBID_PROP_LIST_ID_VC_PK("RBID_PROP_LIST_ID_VC_PK"),
	LIST_TYPE_ID_VC_FK("LIST_TYPE_ID_VC_FK"),
	PREVIOUS_LIST_STRT_DATE("PREVIOUS_LIST_STRT_DATE"),
	PREVIOUS_LIST_END_DATE("PREVIOUS_LIST_END_DATE"),
	PREVIOUS_LIST_PRICE("PREVIOUS_LIST_PRICE"),
	CURRENT_LIST_STRT_DATE("CURRENT_LIST_STRT_DATE"),
	CURRENT_LIST_END_DATE("CURRENT_LIST_END_DATE"),
	LIST_STTS_DTLS_VC("LIST_STTS_DTLS_VC"),
	OCCPNCY_STTS_AT_LST_CREATN("OCCPNCY_STTS_AT_LST_CREATN"),
	ACTUAL_LIST_CYCLE("ACTUAL_LIST_CYCLE"),
	WEEKN_RECOMMENDED_LIST_PRICE_REDUCTION("WEEKN_RECOMMENDED_LIST_PRICE_REDUCTION"),
	WEEKN_RECOMMENDED_DATE("WEEKN_RECOMMENDED_DATE"),
	WEEKN_EXCLUSION_REASON("WEEKN_EXCLUSION_REASON"),
	PCT_PRICE_CHANGE_FRM_LAST_LIST("PCT_PRICE_CHANGE_FRM_LAST_LIST"),
	RULE_VIOLATION("RULE_VIOLATION"),
	WEEKN_MISSINGREPORT("WEEKN_MISSINGREPORT"),
	CLASSIFICATION("CLASSIFICATION");

	private DPQAReportHeader(String value) {
		this.value = value;
	}

	private String value;

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}
