use `umg_admin`;

ALTER TABLE `POOL`
CHANGE COLUMN `ENVIRONMENT` `EXECUTION_LANGUAGE` VARCHAR(32) NOT NULL COMMENT 'Execution language of modelet' COLLATE 'utf8_bin' AFTER `IS_DEFAULT_POOL`,
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT 'Execution environment' DEFAULT 'Linux'  AFTER `EXECUTION_LANGUAGE`;

ALTER TABLE `MODEL_EXEC_PACKAGES`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL DEFAULT 'Linux' AFTER `LAST_UPDATED_ON`;

ALTER TABLE `MODEL_EXEC_PACKAGES_AUDIT`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL DEFAULT 'Linux' AFTER `LAST_UPDATED_ON`;

ALTER TABLE MODEL_EXEC_PACKAGES DROP INDEX  `PACKAGE_FOLDER_VERSION_CONSTRAINT`;

ALTER TABLE MODEL_EXEC_PACKAGES ADD UNIQUE INDEX  PACKAGE_FOLDER_VERSION_ENV_CONSTRAINT(`PACKAGE_FOLDER`,`PACKAGE_VERSION`,`EXECUTION_ENVIRONMENT`);

ALTER TABLE `SYSTEM_MODELETS` ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT 'Execution environment' DEFAULT 'Linux'  AFTER `MEMBER_HOST`;

ALTER TABLE `POOL` DROP INDEX  `UNIQUE_POOL_PRIORITY`;
ALTER TABLE `POOL` ADD UNIQUE INDEX  UNIQUE_POOL_PRIORITY(`PRIORITY`,`EXECUTION_LANGUAGE`,`EXECUTION_ENVIRONMENT`);

ALTER TABLE `SYSTEM_MODELETS` ALTER `ENVIRONMENT` DROP DEFAULT;

ALTER TABLE `SYSTEM_MODELETS` CHANGE COLUMN `ENVIRONMENT` `EXEC_LANGUAGE` VARCHAR(20) NOT NULL AFTER `PORT`,
ADD COLUMN `POOL_NAME` VARCHAR(100) NOT NULL AFTER `EXECUTION_ENVIRONMENT`;

commit;
