use `Ocwen`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` ADD COLUMN `ACCEPTABLEVALUES_VALIDATION` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Flag to allow acceptable validation' COLLATE 'utf8_bin' AFTER `IS_TEST`;

ALTER TABLE `MODEL_LIBRARY`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL COMMENT 'Execution environment of the model library' DEFAULT 'Linux' COLLATE 'utf8_bin' AFTER `PACKAGE_NAME`;

ALTER TABLE `MODEL_LIBRARY_AUDIT`
ADD COLUMN `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL COMMENT 'Execution environment of the model library' DEFAULT 'Linux' COLLATE 'utf8_bin' AFTER `PACKAGE_NAME`;

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN  `EXECUTION_ENVIRONMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Execution Environment(Linux/Windows)' COLLATE 'utf8_bin';

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN  `MODELLING_ENVIRONMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Modelling Environment(R-3.2.1/R-3.3.2/Matlab-7.16)' COLLATE 'utf8_bin';

ALTER TABLE `UMG_RUNTIME_TRANSACTION` CHANGE COLUMN `CLIENT_TRANSACTION_ID` `CLIENT_TRANSACTION_ID` VARCHAR(250) NOT NULL COMMENT 'Transaction Number' COLLATE 'utf8_bin' AFTER `TENANT_ID`;

commit;
