use `Ocwen`;

UPDATE BATCH_TRANSACTION set EXECUTION_ENVIRONMENT='Linux';

UPDATE BATCH_TRANSACTION set MODELLING_ENVIRONMENT='Matlab-7.16' WHERE  MODEL_NAME IN(SELECT NAME FROM MODEL_LIBRARY WHERE MODEL_EXEC_ENV_NAME like 'Matlab%');

UPDATE BATCH_TRANSACTION set MODELLING_ENVIRONMENT='R-3.2.1' WHERE  MODEL_NAME IN(SELECT NAME FROM MODEL_LIBRARY WHERE MODEL_EXEC_ENV_NAME like 'R%');

commit;
