

ALTER TABLE `DP_WEEK0_PARAMS`
	DROP FOREIGN KEY `WEEK0_ID_FK`,
	DROP COLUMN `WEEK0_ID`;
	
	
ALTER TABLE `DP_WEEK0_PARAMS`
	CHANGE COLUMN `FAILED_STEP_COMMAND_ID` `FAILED_STEP_COMMAND_ID` char(36) DEFAULT NULL AFTER `LAST_UPDATED_ON`;

DROP TABLE IF EXISTS `DP_WEEK0_PARAMS_ORIGINAL`;

INSERT INTO `RA_TNT_MODEL_DETAIL` (`ID`, `NAME`, `MAJOR_VERSION`, `MINOR_VERSION`, `TENANT_ID`, `DESCRIPTION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('1', 'hubzu_week_0', 22, 0, '25258d15-737d-11e7-bd9f-0050568756f9', 'aa', 'yogeshku', 123456, 'asda', 111111);
INSERT INTO `RA_TNT_MODEL_DETAIL` (`ID`, `NAME`, `MAJOR_VERSION`, `MINOR_VERSION`, `TENANT_ID`, `DESCRIPTION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('44f658f5-f620-11e7-94e4-a44cc82e487c', 'nrzweek0', 1, 0, 'f0080a14-d9a3-11e7-b11f-005056875889', NULL, 'system', 20180111131046, NULL, NULL);

CREATE TABLE IF NOT EXISTS `RA_TNT_AD_GROUP_MODEL` (
  `ID` char(36) NOT NULL,
  `AD_GROUP_ID` char(36) NOT NULL,
  `MODEL_ID` char(36) NOT NULL,
  `CREATED_BY` varchar(100) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` varchar(100) DEFAULT NULL,
  `LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `RA_TNT_AD_GROUP_ID_FK` (`AD_GROUP_ID`),
  KEY `RA_TNT_MODEL_ID_FK` (`MODEL_ID`),
  CONSTRAINT `RA_TNT_MODEL_ID_FK` FOREIGN KEY (`MODEL_ID`) REFERENCES `RA_TNT_MODEL_DETAIL` (`ID`),
  CONSTRAINT `RA_TNT_AD_GROUP_ID_FK` FOREIGN KEY (`AD_GROUP_ID`) REFERENCES `RA_TNT_AD_GROUP` (`ID`)
);