

DROP TABLE IF EXISTS `DYNAMIC_PRICING_INTG_AUDITS`;
DROP TABLE IF EXISTS `DP_WEEK0_PARAMS`;
DROP TABLE IF EXISTS `DYNAMIC_PRICING_FILE_PRCS_STATUS`;
DROP TABLE IF EXISTS `DP_WEEKN_INTG_AUDITS`;
DROP TABLE IF EXISTS `DP_WEEKN_STATES`;
DROP TABLE IF EXISTS `DP_WEEKN_PARAMS`;
DROP TABLE IF EXISTS `DP_WEEKN_PRCS_STATUS`;
DROP TABLE IF EXISTS `DP_WEEKN_HOLIDAYS`;
DROP TABLE IF EXISTS `COMMAND`;
DROP TABLE IF EXISTS `TEST_TABLE`