

DROP TABLE IF EXISTS `AD_GROUP_APP_MAPPING`;
DROP TABLE IF EXISTS `RA_TNT_TRANSACTION_IO`;
DROP TABLE IF EXISTS `RA_TNT_AD_GROUP_MODEL`;
DROP TABLE IF EXISTS `RA_TNT_APP_PARAMS`;
DROP TABLE IF EXISTS `RA_TNT_APPS`;
DROP TABLE IF EXISTS `SPCL_SERVICING_INVESTORS`;
DROP TABLE IF EXISTS `SPCL_SERVICING_INVESTOR_FILES`;
DROP TABLE IF EXISTS `RA_TNT_SYSTEM_PARAMETERS`;
DROP TABLE IF EXISTS `RA_TNT_TRANSACTIONS`;
DROP TABLE IF EXISTS `RA_TNT_AD_GROUP`;
DROP TABLE IF EXISTS `RA_TNT_MODEL_DETAIL`;
DROP TABLE IF EXISTS `RA_TNT_TENANT`;