

ALTER TABLE `DP_WEEKN_PARAMS`
	DROP COLUMN `STATE`,
	DROP COLUMN `ZIPCODE`,
	DROP COLUMN `CLIENT_CODE`;
	
ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL`
	DROP COLUMN `STATE`,
	DROP COLUMN `ZIPCODE`,
	DROP COLUMN `CLIENT_CODE`;