

DROP TABLE IF EXISTS `DP_MIGRATION_MAP`;
CREATE TABLE IF NOT EXISTS `DP_MIGRATION_MAP` (
  `ID` char(36) NOT NULL,
  `LOAN_NUMBER` char(36) NOT NULL,
  `NEW_LOAN_NUMBER` char(36) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY LOAN (LOAN_NUMBER),
  UNIQUE KEY NEW_LOAN (NEW_LOAN_NUMBER)
  ) ENGINE=InnoDB;