

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE` = 'SELECT SELR_PROP_ID_VC_NN, CLNT_CODE_VC, IS_SPCL_HNDL_PROP_VC FROM RRRBPMMS_PROP WHERE SELR_PROP_ID_VC_NN IN (:idList)' WHERE `ATTR_KEY` = 'SS_PMI_HUBZU_QUERY';

SELECT ID from `RA_TNT_APPS` WHERE LOWER(code) = 'dpa' INTO @APP_ID;
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'PMI_FLAG_RR_QUERY', 'SELECT PROP_TEMP, PMI_FLAG FROM ENT_REPOS.ER_PROPS WHERE PROP_TEMP IN (:idList)', 'SYSTEM', UNIX_TIMESTAMP(NOW()));
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'PMI_INSC_ARLT_QUERY', 'SELECT AA.LOANNUMBER, AA.INSCID FROM ARLT.ARLT_INSPOLCY AA, ARLT.ARLT_PROPERTY BB WHERE AA.LOANNUMBER=BB.LOANNUMBER AND AA.INSTYP IN (\'41\',\'42\',\'44\') AND BB.UNPAIDPRINBAL > \'10\' AND AA.LOANNUMBER IN (:idList)', 'SYSTEM', UNIX_TIMESTAMP(NOW())); 
