

ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` DROP INDEX idx_inptFileName;
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` DROP INDEX idx_status;
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` DROP INDEX idx_upldTimeStmp;
ALTER TABLE `DP_WEEKN_PRCS_STATUS` DROP INDEX idx_status;
ALTER TABLE `DP_WEEKN_PRCS_STATUS` DROP INDEX idx_fetchDate;

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'RR_CLASSIFICATION_QUERY';

