use umg_admin;

DELETE FROM WHERE SYSTEM_KEY`= 'ModelOutput_Validation' AND  `KEY_TYPE` = 'TENANT';

DELETE FROM POOL_CRITERIA WHERE  CRITERIA_NAME='CHANNEL';

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = TRIM(REPLACE(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE, '& #CHANNEL# = Any', ''));
	

update POOL_CRITERIA_DEF_MAPPING
set POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'TRANSACTION_TYPE','TRANSACTIONTYPE');

update POOL_CRITERIA_DEF_MAPPING
set POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'TRANSACTION_MODE','TRANSACTIONMODE');


update POOL_CRITERIA_DEF_MAPPING
set POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'TRANSACTIONTYPE','TRANSACTION_MODE');

update POOL_CRITERIA_DEF_MAPPING
set POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'TRANSACTIONMODE','TRANSACTION_TYPE');


SELECT @criteria_priority_type:= CRITERIA_PRIORITY FROM POOL_CRITERIA WHERE CRITERIA_NAME='TRANSACTION_TYPE';

SELECT @criteria_priority_mode:= CRITERIA_PRIORITY FROM POOL_CRITERIA WHERE CRITERIA_NAME='TRANSACTION_MODE';

UPDATE POOL_CRITERIA SET CRITERIA_PRIORITY=@criteria_priority_type WHERE CRITERIA_NAME='TRANSACTION_MODE';

UPDATE POOL_CRITERIA SET CRITERIA_PRIORITY=@criteria_priority_mode WHERE  CRITERIA_NAME= 'TRANSACTION_TYPE';

commit;