ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	CHANGE COLUMN `OLD_ASSET_NUMBER` `OLD_ASSET_NUMBER` VARCHAR(100) NULL DEFAULT NULL AFTER `ASSET_NUMBER`,
	CHANGE COLUMN `PROP_TEMP` `PROP_TEMP` VARCHAR(100) NULL DEFAULT NULL AFTER `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	CHANGE COLUMN `OLD_ASSET_NUMBER` `OLD_ASSET_NUMBER` VARCHAR(100) NULL DEFAULT NULL AFTER `ASSET_NUMBER`,
	CHANGE COLUMN `PROP_TEMP` `PROP_TEMP` VARCHAR(100) NULL DEFAULT NULL AFTER `OLD_ASSET_NUMBER`;
	
SELECT ID from RA_TNT_APPS WHERE LOWER(code) = 'dpa' INTO @APP_ID;

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` IN ('phh.av.upper.slab','phh.av.lower.slab') AND `RA_TNT_APP_ID` = @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'phh.av.upper.slab', '4', 'SYSTEM', NOW());

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'phh.av.lower.slab', '1', 'SYSTEM', NOW());


	
