USE umg_admin; 

UPDATE `MODEL_EXECUTION_ENVIRONMENTS` SET IS_ACTIVE = 'T' WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION= '3.3.2';

DELETE FROM `MODEL_EXECUTION_ENVIRONMENTS` WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION= '3.5.2';

COMMIT;
