USE umg_admin;

SET @CREATED_BY = 'SYSTEM';
SET @CREATED_ON =  UNIX_TIMESTAMP();

UPDATE `MODEL_EXECUTION_ENVIRONMENTS` SET IS_ACTIVE = 'F' WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION= '3.3.2';
UPDATE `MODEL_EXECUTION_ENVIRONMENTS` SET IS_ACTIVE = 'F' WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION= '3.2.1';

INSERT INTO `MODEL_EXECUTION_ENVIRONMENTS` (`ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`, `NAME`, `IS_ACTIVE`) VALUES (UUID(), 'R', '3.5.2', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON, 'R-3.5.2', 'T');

COMMIT;