use umg_admin;

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('A37E5EFF-9CBF-4FC0-8F25-B71C5318FB21', 'deleteRModelArtifacts', 'delete R Model from temp path and DB', 12, 'CREATE', 'SYSTEM', 0, NULL, NULL);

INSERT INTO `SYSTEM_PARAMETER` (`ID`, `SYS_KEY`, `SYS_VALUE`, `IS_ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('951BFFFE-89D6-4701-9241-29C64B90EA5E', 'uploadFileTempPath', 'temp', 'Y', 'system', 1435816777, 'system', 1435816787);

INSERT INTO `SYSTEM_PARAMETER` (`id`, `sys_key`, `sys_value`, `is_active`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`) VALUES ('FFB80A23-2AF8-4E2F-B3A3-57D3B324B882', 'max-wait-time-primary-search', '10000', 'Y', 'system', 1417439330020, 'system', 1427197136815);

INSERT INTO `SYSTEM_PARAMETER` (`id`, `sys_key`, `sys_value`, `is_active`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`) VALUES ('67577854-0203-4404-843B-0E7F90E67F2', 'max-wait-time-advance-search', '30000', 'Y', 'system', 1417439330020, 'system', 1427197136815);

ALTER TABLE MODEL_EXECUTION_ENVIRONMENTS DROP COLUMN TENANT_ID;

ALTER TABLE MODEL_EXECUTION_ENVIRONMENTS ADD COLUMN `NAME` VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin';

UPDATE MODEL_EXECUTION_ENVIRONMENTS SET NAME='Matlab-7.16' where EXECUTION_ENVIRONMENT='Matlab' and ENVIRONMENT_VERSION='7.16';

UPDATE MODEL_EXECUTION_ENVIRONMENTS SET NAME='R-3.1.2' where EXECUTION_ENVIRONMENT='R' and ENVIRONMENT_VERSION='3.1.2';

ALTER TABLE MODEL_EXEC_PACKAGES DROP COLUMN  TENANT_ID;

ALTER TABLE MODEL_EXEC_PACKAGES DROP COLUMN  MODEL_EXEC_ENV_ID;

ALTER TABLE MODEL_EXEC_PACKAGES ADD COLUMN MODEL_EXEC_ENV_NAME VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin';

ALTER TABLE MODEL_EXEC_PACKAGES_AUDIT DROP COLUMN  TENANT_ID;

ALTER TABLE MODEL_EXEC_PACKAGES_AUDIT DROP COLUMN  MODEL_EXEC_ENV_ID;

ALTER TABLE MODEL_EXEC_PACKAGES_AUDIT ADD COLUMN MODEL_EXEC_ENV_NAME VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin';

UPDATE MODEL_EXEC_PACKAGES SET MODEL_EXEC_ENV_NAME='R-3.1.2';

UPDATE MODEL_EXEC_PACKAGES_AUDIT SET MODEL_EXEC_ENV_NAME='R-3.1.2';

DROP TABLE IF EXISTS `POOL_CRITERIA`;
DROP TABLE IF EXISTS `POOL_CRITERIA_DEF_MAPPING`;
DROP TABLE IF EXISTS `POOL_USAGE_ORDER`;
DROP TABLE IF EXISTS `POOL`;
CREATE TABLE IF NOT EXISTS `POOL` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'Pool id',
  `POOL_NAME` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'Priority Pool Name',
  `POOL_DESCRIPTION` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'Priority Pool Description',
  `IS_BATCH_POOL` tinyint(1) DEFAULT '0' COMMENT 'Flag to indicate whether it is for batch pool or not',
  `BATCH_STATUS` varchar(25) COLLATE utf8_bin DEFAULT NULL COMMENT 'Batch Status like SUCCESS, ERROR etc',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELETE FROM `POOL`;

INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_BATCH_POOL`, `BATCH_STATUS`) VALUES
	('1', 'ONLINE_POOL', 'POOL OF MODELETS FOR ONLINE REQUETS', 0, NULL),
	('2', 'BATCH_POOL', 'POOL OF MODELETS FOR BATCH REQUETS', 1, NULL),
	('3', 'DEFAULT_POOL', 'POOL OF DEFAULT MODELETS', 0, NULL),
	('4', 'R_POOL', 'POOL OF MODELETS FOR R', 0, NULL);

CREATE TABLE IF NOT EXISTS `POOL` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'Pool id',
  `POOL_NAME` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'Priority Pool Name',
  `POOL_DESCRIPTION` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'Priority Pool Description',
  `IS_BATCH_POOL` tinyint(1) DEFAULT '0' COMMENT 'Flag to indicate whether it is for batch pool or not',
  `BATCH_STATUS` varchar(25) COLLATE utf8_bin DEFAULT NULL COMMENT 'Batch Status like SUCCESS, ERROR etc',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELETE FROM `POOL`;
/*!40000 ALTER TABLE `POOL` DISABLE KEYS */;
INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_BATCH_POOL`, `BATCH_STATUS`) VALUES
	('1', 'ONLINE_POOL', 'POOL OF MODELETS FOR ONLINE REQUETS', 0, NULL),
	('2', 'BATCH_POOL', 'POOL OF MODELETS FOR BATCH REQUETS', 1, NULL),
	('3', 'DEFAULT_POOL', 'POOL OF DEFAULT MODELETS', 0, NULL),
	('4', 'R_POOL', 'POOL OF MODELETS FOR R', 0, NULL);

CREATE TABLE IF NOT EXISTS `POOL_CRITERIA` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL COMMENT 'pool criteria id',
  `CRITERIA_NAME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT 'pool criteria name',
  `CRITERIA_ORDER` int(10) NOT NULL COMMENT 'criteria order',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Priority pool criterias';

DELETE FROM `POOL_CRITERIA`;
/*!40000 ALTER TABLE `POOL_CRITERIA` DISABLE KEYS */;
INSERT INTO `POOL_CRITERIA` (`ID`, `CRITERIA_NAME`, `CRITERIA_ORDER`) VALUES
	('1', 'TENANT', 1),
	('2', 'ENVIRONMENT', 2),
	('3', 'ENVIRONMENT_VERSION', 3),
	('4', 'TRANSACTION_TYPE', 4);
/*!40000 ALTER TABLE `POOL_CRITERIA` ENABLE KEYS */;


CREATE TABLE IF NOT EXISTS `POOL_CRITERIA_DEF_MAPPING` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL,
  `POOL_ID` varchar(50) COLLATE utf8_bin NOT NULL,
  `POOL_CRITERIA_VALUE` varchar(200) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FK_UNIQUE_CRITERIA` (`POOL_ID`,`POOL_CRITERIA_VALUE`),
  CONSTRAINT `FK_POOL_ID` FOREIGN KEY (`POOL_ID`) REFERENCES `POOL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELETE FROM `POOL_CRITERIA_DEF_MAPPING`;

INSERT INTO `POOL_CRITERIA_DEF_MAPPING` (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) VALUES
	('1', '1', 'TENANT = OCWEN AND ENVIRONMENT = MATLAB AND ENVIRONMENT_VERSION = 7.16 AND TRANSACTION_TYPE = ONLINE'),
	('2', '2', 'TENANT = OCWEN AND ENVIRONMENT = MATLAB AND ENVIRONMENT_VERSION = 7.16 AND TRANSACTION_TYPE = BATCH'),
	('4', '3', 'TENANT = OCWEN AND ENVIRONMENT = R AND ENVIRONMENT_VERSION = 3.1.2 AND TRANSACTION_TYPE = BATCH'),
	('3', '4', 'TENANT = OCWEN AND ENVIRONMENT = R AND ENVIRONMENT_VERSION = 3.1.2 AND TRANSACTION_TYPE = ONLINE');



CREATE TABLE IF NOT EXISTS `POOL_USAGE_ORDER` (
  `ID` varchar(50) COLLATE utf8_bin NOT NULL,
  `POOL_ID` varchar(50) COLLATE utf8_bin NOT NULL,
  `POOL_USAGE_ID` varchar(50) COLLATE utf8_bin NOT NULL,
  `POOL_TRY_ORDER` int(10) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKPOOL_ID` (`POOL_ID`),
  CONSTRAINT `FKPOOL_ID` FOREIGN KEY (`POOL_ID`) REFERENCES `POOL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DELETE FROM `POOL_USAGE_ORDER`;
/*!40000 ALTER TABLE `POOL_USAGE_ORDER` DISABLE KEYS */;
INSERT INTO `POOL_USAGE_ORDER` (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) VALUES
	('1', '1', '1', 1),
	('2', '1', '2', 2),
	('3', '1', '3', 3),
	('4', '2', '2', 1),
	('5', '2', '3', 2),
	('6', '4', '4', 1),
	('7', '3', '3', 1);

commit;
