use equator;
-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.6.17 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             8.3.0.4694
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table localhost.mediate_model_library
CREATE TABLE IF NOT EXISTS `MEDIATE_MODEL_LIBRARY` (
  `ID` char(36) NOT NULL,
  `TAR_NAME` varchar(100) NOT NULL,
  `CHECKSUM_VALUE` varchar(100) NOT NULL,
  `CHECKSUM_TYPE` varchar(45) NOT NULL,
  `TENANT_ID` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Tenant code for the record',
  `MODEL_EXEC_ENV_NAME` VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin',
  `CREATED_BY` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LAST_UPDATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping structure for table localhost.mediate_model_library_audit
CREATE TABLE IF NOT EXISTS `MEDIATE_MODEL_LIBRARY_AUDIT` (
  `ID` char(36) NOT NULL,
  `TAR_NAME` varchar(100) NOT NULL,
  `CHECKSUM_VALUE` varchar(100) NOT NULL,
  `CHECKSUM_TYPE` varchar(100) NOT NULL,
  `MODEL_EXEC_ENV_NAME` VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin',
  `TENANT_ID` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'Tenant code for the record',
  `REV` int(11) NOT NULL,
  `CREATED_BY` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LAST_UPDATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK_REV` (`REV`),
  CONSTRAINT `FK_REV` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA`='umg_admin' AND `TABLE_NAME`='MODEL_EXECUTION_ENVIRONMENTS';
CREATE TABLE `umg_admin`.`MODEL_EXECUTION_ENVIRONMENTS` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`EXECUTION_ENVIRONMENT` VARCHAR(50) NOT NULL COMMENT 'Model execution environment.' COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(50) NOT NULL COMMENT 'Version of the execution environment.' COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL
)
 COLLATE 'utf8_bin' ENGINE=InnoDB ROW_FORMAT=Compact COMMENT='Table to store Model execution environment and version';
INSERT INTO `umg_admin`.`MODEL_EXECUTION_ENVIRONMENTS` (`ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) SELECT `ID`, `TENANT_ID`, `EXECUTION_ENVIRONMENT`, `ENVIRONMENT_VERSION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON` FROM `MODEL_EXECUTION_ENVIRONMENTS`;


SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA`='umg_admin' AND `TABLE_NAME`='MODEL_EXEC_PACKAGES';
CREATE TABLE `umg_admin`.`MODEL_EXEC_PACKAGES` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_EXEC_ENV_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(200) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(200) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_VERSION` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_TYPE` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`COMPILED_OS` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL
)
 COLLATE 'utf8_bin' ENGINE=InnoDB ROW_FORMAT=Compact COMMENT='Table to store model execution environment base packages';
INSERT INTO `umg_admin`.`MODEL_EXEC_PACKAGES` (`ID`, `TENANT_ID`, `MODEL_EXEC_ENV_ID`, `PACKAGE_NAME`, `PACKAGE_FOLDER`, `PACKAGE_VERSION`, `PACKAGE_TYPE`, `COMPILED_OS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) SELECT `ID`, `TENANT_ID`, `MODEL_EXEC_ENV_ID`, `PACKAGE_NAME`, `PACKAGE_FOLDER`, `PACKAGE_VERSION`, `PACKAGE_TYPE`, `COMPILED_OS`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON` FROM `MODEL_EXEC_PACKAGES`;

SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA`='umg_admin' AND `TABLE_NAME`='MODEL_EXEC_PACKAGES_AUDIT';
CREATE TABLE `umg_admin`.`MODEL_EXEC_PACKAGES_AUDIT` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NULL DEFAULT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_VERSION` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`PACKAGE_TYPE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`COMPILED_OS` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	`CREATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL
)
 COLLATE 'utf8_bin' ENGINE=InnoDB ROW_FORMAT=Compact COMMENT='Table to store model execution environment base packages';
INSERT INTO `umg_admin`.`MODEL_EXEC_PACKAGES_AUDIT` (`ID`, `MODEL_EXEC_ENV_ID`, `TENANT_ID`, `PACKAGE_NAME`, `PACKAGE_FOLDER`, `PACKAGE_VERSION`, `PACKAGE_TYPE`, `COMPILED_OS`, `REV`, `REVTYPE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) SELECT `ID`, `MODEL_EXEC_ENV_ID`, `TENANT_ID`, `PACKAGE_NAME`, `PACKAGE_FOLDER`, `PACKAGE_VERSION`, `PACKAGE_TYPE`, `COMPILED_OS`, `REV`, `REVTYPE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON` FROM `MODEL_EXEC_PACKAGES_AUDIT`;

ALTER TABLE MODEL_LIBRARY ADD COLUMN MODEL_EXEC_ENV_NAME VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin';

ALTER TABLE `MODEL_LIBRARY`	DROP INDEX `FKMODEL_EXEC_ENV_ID`,	DROP FOREIGN KEY `FKMODEL_EXEC_ENV_ID`;

ALTER TABLE MODEL_LIBRARY DROP COLUMN  MODEL_EXEC_ENV_ID;

ALTER TABLE MODEL_LIBRARY_AUDIT ADD COLUMN MODEL_EXEC_ENV_NAME VARCHAR(50) NOT NULL COMMENT 'Language name and version' COLLATE 'utf8_bin';

ALTER TABLE MODEL_LIBRARY_AUDIT DROP COLUMN  MODEL_EXEC_ENV_ID;

UPDATE MODEL_LIBRARY SET MODEL_EXEC_ENV_NAME='Matlab-7.16' where EXECUTION_LANGUAGE='Matlab';

UPDATE MODEL_LIBRARY SET MODEL_EXEC_ENV_NAME='Matlab-7.16' where EXECUTION_LANGUAGE='MATLAB';

UPDATE MODEL_LIBRARY SET MODEL_EXEC_ENV_NAME='R-3.1.2' where EXECUTION_LANGUAGE='R';

ALTER TABLE `MODEL_LIB_EXEC_PKG_MAPPING` DROP FOREIGN KEY `FK_MODEL_EXEC_PKG_ID`;
	
ALTER TABLE `MODEL_LIB_EXEC_PKG_MAPPING` DROP INDEX `FK_MODEL_EXEC_PKG_ID`;

commit;

