use umg_admin;

ALTER TABLE ADDRESS modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE ADDRESS modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL_IMPLEMENTATION_TYPE modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL_IMPLEMENTATION_TYPE modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE SYNDICATED_DATA modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE SYNDICATED_DATA modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE SYSTEM_KEY modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE SYSTEM_KEY modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE TENANT modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE TENANT modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE TENANT_CONFIG modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE TENANT_CONFIG modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;

DROP TABLE IF EXISTS USERS ;
SHOW WARNINGS;
CREATE TABLE USERS (
USERNAME VARCHAR(50) NOT NULL ,
PASSWORD VARCHAR(100) NOT NULL ,
ENABLED TINYINT NOT NULL DEFAULT 1 ,
PRIMARY KEY (USERNAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS USER_ROLES ;
SHOW WARNINGS;
CREATE TABLE USER_ROLES (
USER_ROLE_ID INT(11) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
ROLE VARCHAR(25) NOT NULL,
PRIMARY KEY (USER_ROLE_ID),
UNIQUE KEY uni_USERNAME_role (ROLE,USERNAME),
KEY fk_USERNAME_idx (USERNAME),
CONSTRAINT fk_USERNAME FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

commit;