

ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `PROP_TEMP` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` ADD COLUMN `PROP_TEMP` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS` ADD COLUMN `PROP_TEMP` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS_ORIGINAL` ADD COLUMN `PROP_TEMP` VARCHAR(36) NULL DEFAULT NULL AFTER `ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_AUDIT_REPORTS` ADD COLUMN `PROP_TEMP` VARCHAR(36) NULL DEFAULT NULL AFTER `LOAN_NUMBER`;