

ALTER TABLE `DP_WEEKN_PARAMS` DROP COLUMN `PROP_TEMP`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` DROP COLUMN `PROP_TEMP`;

ALTER TABLE `DP_WEEK0_PARAMS` DROP COLUMN `PROP_TEMP`;

ALTER TABLE `DP_WEEK0_PARAMS_ORIGINAL` DROP COLUMN `PROP_TEMP`;

ALTER TABLE `DP_WEEKN_AUDIT_REPORTS` DROP COLUMN `PROP_TEMP`;