
SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

SET @HUBZU_ALL_ROOWS_QUERY = 'SELECT OT1.SELR_PROP_ID_VC_NN,OT1.RBID_PROP_ID_VC_PK,t1.RBID_PROP_ID_VC_FK,OT1.REO_PROP_STTS_VC ,OT1.PROP_SOLD_DATE_DT,OT1.PROP_STTS_ID_VC_FK,T1.RBID_PROP_ID_VC_FK,T1.RBID_PROP_LIST_ID_VC_PK,T1.LIST_TYPE_ID_VC_FK,T1.LIST_PRCE_NT,T1.LIST_STRT_DATE_DT_NN,T1.LIST_END_DATE_DT_NN,T1.LIST_STTS_DTLS_VC,T1.OCCPNCY_STTS_AT_LST_CREATN FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK  IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') AND (SELECT COUNT(*) FROM RRRBPMMS_PROP OT2 WHERE OT2.SELR_PROP_ID_VC_NN = OT1.SELR_PROP_ID_VC_NN AND OT1.PROP_SOLD_DATE_DT IS NULL AND OT2.PROP_SOLD_DATE_DT IS NOT NULL)=0 ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC';

UPDATE `RA_TNT_APP_PARAMS` SET ATTR_VALUE = @HUBZU_ALL_ROOWS_QUERY WHERE ATTR_KEY = 'hubzu.daily.qa.report.all.rows';

ALTER TABLE `WEEKN_DAILY_RUN_STATUS`
	ADD COLUMN `FETCH_START_DATE` DATE NULL DEFAULT NULL AFTER `LAST_RUN_DATE`,
	ADD COLUMN `FETCH_END_DATE` DATE NULL DEFAULT NULL AFTER `FETCH_START_DATE`;

DELETE FROM `WEEKN_DAILY_QA_REPORT`;

DELETE FROM `WEEKN_DAILY_RUN_STATUS`;

INSERT INTO `WEEKN_DAILY_RUN_STATUS` (`ID`, `LAST_RUN_DATE`, `FETCH_START_DATE`, `FETCH_END_DATE`, `TOTAL_RECORD`, `REPORT_TYPE`, `START_TIME`, `END_TIME`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`)
    VALUES (UUID(), '2019-07-17 00:00:00', '2019-06-01', '2019-06-30', 1, 'QA-REPORT', 0, 0, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

