use umg_admin;


UPDATE POOL SET `MODELET_COUNT`=4 WHERE ID=15;



INSERT INTO POOL (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `ENVIRONMENT`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`) VALUES ('7', 'SOP_WEEK_0', 'SOP WEEK 0 ', '0', 'R', '1', '4GB - Linux 64 bit', '7');

INSERT INTO POOL_CRITERIA_DEF_MAPPING (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) VALUES ('7', '7', '#TENANT# = HUBZU & #ENVIRONMENT# = R & #ENVIRONMENT_VERSION# = 3.2.1 & #TRANSACTION_TYPE# = ANY & #MODEL# = SOP_Week_0 & #MODEL_VERSION# = ANY & #TRANSACTION_MODE# = ANY');

INSERT INTO POOL_USAGE_ORDER (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) VALUES ('7', '7', '7', '1');




INSERT INTO POOL (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `ENVIRONMENT`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`) VALUES ('8', 'SOP_WEEK_N', 'SOP WEEK N ', '0', 'R', '1', '4GB - Linux 64 bit', '8');

INSERT INTO POOL_CRITERIA_DEF_MAPPING (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) VALUES ('8', '8', '#TENANT# = HUBZU & #ENVIRONMENT# = R & #ENVIRONMENT_VERSION# = 3.2.1 & #TRANSACTION_TYPE# = ANY & #MODEL# = SOP_Week_n & #MODEL_VERSION# = ANY & #TRANSACTION_MODE# = ANY');

INSERT INTO POOL_USAGE_ORDER (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`) VALUES ('8', '8', '8', '1');



commit;