UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, OT1.SELR_ACNT_ID_VC_FK, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, T1.LIST_TYPE_ID_VC_FK, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\') ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='FUTURE_REDUCTION_SEARCH_QUERY';

ALTER TABLE `DP_WEEKN_PARAMS` DROP COLUMN `PRIOR_RECOMMENDED`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` DROP COLUMN `PRIOR_RECOMMENDED`;

DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'weekn.days.before.selected.date';

-- Rollback Commands to exclude PHH Loans --
DELETE FROM `COMMAND` WHERE `PROCESS` = 'WEEKN_PHH';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.dp.auth.token';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.minor.version';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.major.version';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.tenant.code';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.model.name';

-- Rollback for DP-407 to remove PHH Loans from Hubzu Queries --
UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK, OT1.PROP_STTS_ID_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK  IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\') AND OT1.PROP_SOLD_DATE_DT IS NULL AND (SELECT COUNT(*) FROM RRRBPMMS_PROP OT2 WHERE OT2.SELR_PROP_ID_VC_NN = OT1.SELR_PROP_ID_VC_NN AND OT1.PROP_SOLD_DATE_DT IS NULL AND OT2.PROP_SOLD_DATE_DT IS NOT NULL)=0 ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY_ALL_ROWS';

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE OT1.SELR_PROP_ID_VC_NN IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\') ORDER BY TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='SUCCESS_UNDERREVIEW_HUBZU_QUERY';

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT LOAN_NUM, INSURANCE_COMPANY_ID, AS_OF_DT, FC_INVENTORY_FLAG,  NRZ_ACQUISITION_DT, SPECIAL_SERVICING_FLAG, PMI_FLAG, PROP_TEMP, OLD_RR_LOAN_NUM, CLIENT_ID FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE PROP_TEMP = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY' WHERE  `ATTR_KEY`='RR_CLASSIFICATION_QUERY';

-- Rollback to Newly Added Column into DP_WEEKN_PRCS_STATUS  Table for PHH Loan Output File --
ALTER TABLE `DP_WEEKN_PRCS_STATUS`	DROP COLUMN `PHH_OUTPUT_FILE_NAME`;

-- Rollback to Newly Added Column into DYNAMIC_PRICING_FILE_PRCS_STATUS  Table for PHH Loan Output File --
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS`	DROP COLUMN `PHH_OUTPUT_FILE_NAME`;

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.minimum.asset.value';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.maximum.asset.value';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.dp.auth.token';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.pricemode.input';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.minor.version';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.major.version';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.tenant.code';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'phh.week0Vacant.model.name';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'WEEK0_PHH';
