SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0DuplicateFilter', 'Duplicate Asset', 2, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0InvestorCodeFilter', 'SS Investor', 3, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0AssetValueFilter', 'Unsupported Asset Value', 4, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0RRRtngAggregator', 'Failed Data Fetch', 5, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0PropertyTypeFilter', 'Unsupported Property Type', 6, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0CAIntegration', 'CA_INTEGRATION', 7, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0ModeledBenchmarkCriteria', 'RULE_80_20', 8, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0RAInputPayload', 'Model Failure', 9, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0OutputFileCreate', 'WEEK0_OUTPUT_FILE', 10, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0EmailIntegration', 'WEEK0_EMAIL_INTEGRATION', 11, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

SELECT ID from `RA_TNT_APPS` WHERE `NAME` = 'DPA' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.model.name', 'HUBZU_WEEK_0', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.tenant.code', 'hubzu', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.major.version', '24', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.minor.version', '', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.pricemode.input', NULL, 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.dp.auth.token', 'k+oRDQ7tYuD5oyq6HubRAbFrReewznGAzQFfQwPxZdMarkkvK5mO5sobLwRsW4H4', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.maximum.asset.value', '750000', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.minimum.asset.value', '10000', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

-- Adding Column into DYNAMIC_PRICING_FILE_PRCS_STATUS  Table for PHH Loan Output File --
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS`	ADD COLUMN `PHH_OUTPUT_FILE_NAME` VARCHAR(200) NULL DEFAULT NULL AFTER `NRZ_OUTPUT_FILE_NAME`;

SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;
-- Insert Commands to include and process  PHH Loans --
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNAssignmentFilter', 'Benchmark', 2, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 3, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNActiveListingsFilter', 'Active Listing', 4, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNPast12CyclesFilter', 'Past 12 Cycles', 5, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNOddListingsFilter', 'Odd Listing', 6, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNZipStateFilter', 'Unsupported State/Zip', 7, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNSSPmiFilter', 'SS & PMI', 8, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNSOPFilter', 'SOP', 9, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNRAIntegrarion', 'Model Failure', 10, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNOutputFileCreate', 'WEEKN_OUTPUT_FILE', 11, 'WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'weekNEmailIntegration', 'WEEKN_EMAIL_INTEGRATION', 12, 'WEEKN_PHH', FALSE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

SELECT ID from `RA_TNT_APPS` WHERE `NAME` = 'DPA' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.weekNVacant.model.name', 'hubzuweekn', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.weekNVacant.tenant.code', 'hubzu', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.weekNVacant.major.version', '1', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.weekNVacant.minor.version', '', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.weekN.dp.auth.token', 'k+oRDQ7tYuD5oyq6HubRAbFrReewznGAzQFfQwPxZdMarkkvK5mO5sobLwRsW4H4', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);


-- Update for Hubzu Queries to include PHH Loans --
UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK, OT1.PROP_STTS_ID_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK  IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') AND OT1.PROP_SOLD_DATE_DT IS NULL AND (SELECT COUNT(*) FROM RRRBPMMS_PROP OT2 WHERE OT2.SELR_PROP_ID_VC_NN = OT1.SELR_PROP_ID_VC_NN AND OT1.PROP_SOLD_DATE_DT IS NULL AND OT2.PROP_SOLD_DATE_DT IS NOT NULL)=0 ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY_ALL_ROWS';

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE OT1.SELR_PROP_ID_VC_NN IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') ORDER BY TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='SUCCESS_UNDERREVIEW_HUBZU_QUERY';

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT LOAN_NUM, INSURANCE_COMPANY_ID, AS_OF_DT, FC_INVENTORY_FLAG,  NRZ_ACQUISITION_DT, SPECIAL_SERVICING_FLAG, PMI_FLAG, PROP_TEMP, OLD_RR_LOAN_NUM, CLIENT_ID, PHH_FLAG FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE PROP_TEMP = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY' WHERE  `ATTR_KEY`='RR_CLASSIFICATION_QUERY';

-- Adding Column into DP_WEEKN_PRCS_STATUS  Table for PHH Loan Output File --
ALTER TABLE `DP_WEEKN_PRCS_STATUS`	ADD COLUMN `PHH_OUTPUT_FILE_NAME` VARCHAR(200) NULL DEFAULT NULL AFTER `NRZ_OUTPUT_FILE_NAME`;

ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `PRIOR_RECOMMENDED` CHAR(1) NULL AFTER `PROP_SOLD_DATE_DT`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` ADD COLUMN `PRIOR_RECOMMENDED` VARCHAR(50) NULL AFTER `LP_DOLLAR_ADJUSTMENT_REC`;

INSERT INTO `RA_TNT_SYSTEM_PARAMETERS` (`ID`, `SYS_KEY`, `SYS_VALUE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), 'weekn.days.before.selected.date', '14', 'Fetch days count.', 'SYSTEM', NOW(), NULL, NULL);

-- Update for Hubzu Queries to include PHH Loans --
UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT T1.RBID_PROP_ID_VC_FK, OT1.SELR_ACNT_ID_VC_FK, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, T1.LIST_TYPE_ID_VC_FK, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC' WHERE  `ATTR_KEY`='FUTURE_REDUCTION_SEARCH_QUERY';