ALTER TABLE `UMG_RUNTIME_TRANSACTION`
ADD COLUMN `MODEL_EXECUTION_TIME` bigint(20) default null;

ALTER TABLE `UMG_RUNTIME_TRANSACTION`
ADD COLUMN `MODELET_EXECUTION_TIME` bigint(20) default null;

ALTER TABLE `UMG_RUNTIME_TRANSACTION`
ADD COLUMN `ME2_WAITING_TIME` bigint(20) default null;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT`
ADD COLUMN `MODEL_EXECUTION_TIME` bigint(20) default null;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT`
ADD COLUMN `MODELET_EXECUTION_TIME` bigint(20) default null;

ALTER TABLE `UMG_RUNTIME_TRANSACTION_AUDIT`
ADD COLUMN `ME2_WAITING_TIME` bigint(20) default null;