-- USE 'tenant schema';

ALTER TABLE `BATCH_TRANSACTION`
	CHANGE COLUMN `BATCH_FILE_NAME` `BATCH_INPUT_FILE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin' AFTER `TENANT_ID`,
	ADD COLUMN `BATCH_OUTPUT_FILE` VARCHAR(100) NULL AFTER `BATCH_INPUT_FILE`,
	ADD COLUMN `IS_TEST` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'Indicates whether the upload is from test bed' AFTER `STATUS`;

ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	ADD COLUMN `STATUS` VARCHAR(50) NULL AFTER `TRANSACTION_ID`,
	ADD COLUMN `ERROR` VARCHAR(50) NULL AFTER `STATUS`;
	
ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	DROP INDEX `FK_BATCH_RUNTIME_TXN_MAPPING_TRANSACTION`,
	DROP FOREIGN KEY `FK_BATCH_RUNTIME_TXN_MAPPING_TRANSACTION`;

COMMIT;

