-- USE 'tenant schema';

CREATE TABLE MODEL_SUPPORT_PACKAGE (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(50) NOT NULL COMMENT 'Group Name of the model library support package, given by user as TAG.' COLLATE 'utf8_bin',
	`ENVIRONMENT` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(30) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(100) NOT NULL COMMENT 'The name of the SUPPORT PACKAGE FILE uploaded' COLLATE 'utf8_bin',
	`CHECKSUM_TYPE` VARCHAR(45) NOT NULL COLLATE 'utf8_bin',
	`CHECKSUM_VALUE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `MODEL_SUPP_PKG_PACKAGE_NAME` (`PACKAGE_NAME`)
)
COMMENT='The table which contains the individual model library suppport package definitions'
COLLATE='utf8_bin'
ENGINE=InnoDB;

CREATE TABLE MODEL_SUPPORT_PACKAGE_AUDIT (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(50) NOT NULL COMMENT 'Group Name of the model library support package, given by user as TAG.' COLLATE 'utf8_bin',
	`ENVIRONMENT` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(100) NOT NULL COMMENT 'The name of the SUPPORT PACKAGE FILE uploaded' COLLATE 'utf8_bin',
	`CHECKSUM_TYPE` VARCHAR(64) NOT NULL COLLATE 'utf8_bin',
	`CHECKSUM_VALUE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`, `REV`),
	INDEX `IDX_MODEL_SUPPORT_PACKAGE_AUDIT_REVINFO` (`REV`),
	CONSTRAINT `FK_MODEL_SUPPORT_PACKAGE_AUDIT_REVINFO` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;

ALTER TABLE UMG_RUNTIME_TRANSACTION
CHANGE COLUMN `TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NULL AFTER `STATUS`,
CHANGE COLUMN `TENANT_OUTPUT` `TENANT_OUTPUT` MEDIUMBLOB NULL COMMENT 'The actual tenant output.' AFTER `TENANT_INPUT`,
CHANGE COLUMN `MODEL_INPUT` `MODEL_INPUT` MEDIUMBLOB NULL AFTER `TENANT_OUTPUT`,
CHANGE COLUMN `MODEL_OUTPUT` `MODEL_OUTPUT` MEDIUMBLOB NULL COMMENT 'The actual output from the model.' AFTER `MODEL_INPUT`;

create index batch_txn_runtime_txn_mapping_index_2 USING BTREE ON `BATCH_TXN_RUNTIME_TXN_MAPPING` (TRANSACTION_ID);
create index umg_version_index_1 USING BTREE ON `UMG_VERSION` (MODEL_LIBRARY_ID);

ALTER TABLE SYNDICATE_DATA_QUERY_INPUTS ADD COLUMN DATATYPE_FORMAT VARCHAR(50) NULL DEFAULT NULL COMMENT 'The format of the type if applicable' AFTER SAMPLE_VALUE ;
ALTER TABLE SYNDICATE_DATA_QUERY_INPUTS_AUDIT ADD COLUMN DATATYPE_FORMAT VARCHAR(50) NULL DEFAULT NULL COMMENT 'The format of the type if applicable' AFTER SAMPLE_VALUE;
ALTER TABLE SYNDICATE_DATA_QUERY_OUTPUTS ADD COLUMN DATATYPE_FORMAT VARCHAR(50) NULL DEFAULT NULL COMMENT 'The format of the type if applicable' AFTER DATA_TYPE;
ALTER TABLE SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT ADD COLUMN DATATYPE_FORMAT VARCHAR(50) NULL DEFAULT NULL COMMENT 'The format of the type if applicable' AFTER DATA_TYPE;


