package com.fa.dp.business.util;

public enum IntegrationType {
	
	RR_INTEGRATION("RR-INTEGRATION"),
	RTNG_INTEGRATION("RTNG-INTEGRATION"),
	CA_INTEGRATION("CA-INTEGRATION"),
	RA_INTEGRATION("RA-INTEGRATION"),
	HUBZU_RA_INTEGRATION("HUBZU-RA-INTEGRATION"),
	HUBZU_SOP_INTEGRATION("HUBZU-SOP-INTEGRATION"),
	HUBZU_INITIAL_INTEGRATION("HUBZU-INITIAL-INTEGRATION"),
	HUBZU_INITIAL_ALL_ROWS_INTEGRATION("HUBZU-INITIAL-ALL-ROWS-INTEGRATION"),
	FUTURE_REDUCTION_SEARCH_QUERY("FUTURE_REDUCTION_SEARCH_QUERY"),
	HUBZU_RECENT_STATUS_INTEGRATION("HUBZU-RECENT-STATUS-INTEGRATION"),
	STAGE5_INTEGRATION("STAGE5-INTEGRATION"),
	PMI_RR_INTEGRATION("PMI_RR_INTEGRATION"),
	PMI_ARLT_INTEGRATION("PMI_ARLT_INTEGRATION"),
	SS_ENT_REPOS_INTEGRATION("SS_ENT_REPOS_INTEGRATION"),
	SOP_WEEKN_HUBZU_TOP_ROWS_INTEGRATION("SOP-WEEKN-HUBZU-TOP-ROWS-INTEGRATION"),
	SOP_WEEKN_HUBZU_ALL_ROWS_INTEGRATION("SOP-WEEKN-HUBZU-ALL-ROWS-INTEGRATION");
	
	private String integrationType;

	private IntegrationType(String integrationType) {
		this.integrationType = integrationType;
	}

	public String getIntegrationType() {
		return integrationType;
	}

}
