use Ocwen ;

ALTER TABLE UMG_RUNTIME_TRANSACTION
ADD COLUMN `CPU_USAGE` DOUBLE NULL DEFAULT '1',
ADD COLUMN `FREE_MEMOREY` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin',
ADD COLUMN `FREE_MEMOREY_AT_START` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin',
ADD COLUMN `CPU_USAGE_AT_START` DOUBLE NULL DEFAULT '0',
ADD COLUMN `IP_AND_PORT` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
ADD COLUMN `POOL_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',

ALTER TABLE `UMG_RUNTIME_TRANSACTION`
	CHANGE COLUMN `FREE_MEMOREY` `FREE_MEMORY` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin' AFTER `CPU_USAGE`,
	CHANGE COLUMN `FREE_MEMOREY_AT_START` `FREE_MEMORY_AT_START` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin' AFTER `FREE_MEMORY`;


ALTER TABLE `UMG_RUNTIME_TRANSACTION`
	ADD COLUMN `NO_OF_ATTMEMPS` INT(2) NULL DEFAULT NULL AFTER `POOL_NAME`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` 
	CHANGE COLUMN `NO_OF_ATTMEMPS` `NO_OF_ATTEMPTS` INT(2) NULL DEFAULT NULL AFTER `POOL_NAME`;

commit;

