use localhost;

ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `REQUESTED_BY`;
ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `REQUESTED_ON`;
ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `EMAIL_APPRROVAL`;

ALTER TABLE UMG_VERSION DROP COLUMN `REQUESTED_BY`;
ALTER TABLE UMG_VERSION DROP COLUMN `REQUESTED_ON`;
ALTER TABLE UMG_VERSION DROP COLUMN `EMAIL_APPRROVAL`;

commit;