use localhost;

ALTER TABLE UMG_VERSION CHANGE COLUMN `PUBLISHED_BY` `PUBLISHED_BY` VARCHAR(516) NULL DEFAULT NULL COMMENT 'User who published the umg version';

ALTER TABLE UMG_VERSION_AUDIT CHANGE COLUMN `PUBLISHED_BY` `PUBLISHED_BY` VARCHAR(516) NULL DEFAULT NULL COMMENT 'User who published the umg version';

ALTER TABLE UMG_VERSION 
ADD COLUMN `REQUESTED_BY` VARCHAR(512) NULL DEFAULT NULL,
ADD COLUMN `REQUESTED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `EMAIL_APPRROVAL` SMALLINT NULL DEFAULT 0;

ALTER TABLE UMG_VERSION_AUDIT 
ADD COLUMN `REQUESTED_BY` VARCHAR(512) NULL DEFAULT NULL,
ADD COLUMN `REQUESTED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `EMAIL_APPRROVAL` SMALLINT NULL DEFAULT 0;

commit;