use Ocwen;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `USER` VARCHAR(200) NULL DEFAULT null COMMENT 'user name ' COLLATE 'utf8_bin' AFTER `TRANSACTION_MODE`;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `MODEL_NAME` VARCHAR(200) NULL DEFAULT null COMMENT 'model name' COLLATE 'utf8_bin' AFTER `USER`;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `MODEL_VERSION` DOUBLE NULL DEFAULT null COMMENT 'model version' AFTER `MODEL_NAME`;
