/*UMG-1038*/
ALTER TABLE MODEL_LIBRARY
ADD COLUMN `CHECKSUM_TYPE` VARCHAR(45) NOT NULL AFTER `JAR_NAME`,
ADD COLUMN `CHECKSUM_VALUE` VARCHAR(100) NOT NULL AFTER `CHECKSUM_TYPE`;

ALTER TABLE MODEL_LIBRARY_AUDIT 
ADD COLUMN `CHECKSUM_TYPE` VARCHAR(45) NULL DEFAULT NULL AFTER `JAR_NAME`,
ADD COLUMN `CHECKSUM_VALUE` VARCHAR(100) NULL DEFAULT NULL AFTER `CHECKSUM_TYPE`;

/*UMG-1039*/
ALTER TABLE MAPPING
ADD COLUMN `STATUS` VARCHAR(20) NOT NULL;

ALTER TABLE MAPPING_AUDIT 
ADD COLUMN `STATUS` VARCHAR(20) NULL;

/*UMG-1053*/
ALTER TABLE `SYNDICATE_DATA_QUERY_INPUTS` DROP COLUMN MANDATORY;
ALTER TABLE `SYNDICATE_DATA_QUERY_INPUTS_AUDIT` DROP COLUMN MANDATORY;
ALTER TABLE `SYNDICATE_DATA_QUERY_OUTPUTS` DROP COLUMN MANDATORY;
ALTER TABLE `SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT` DROP COLUMN MANDATORY;

alter table MAPPING_INPUT add TENANT_INTF_SYS_DEFINITION BLOB;
alter table MAPPING_INPUT_AUDIT add TENANT_INTF_SYS_DEFINITION BLOB;

/*UMG-1052*/
ALTER TABLE MAPPING_INPUT modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING_INPUT modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MAPPING modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING_OUTPUT modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL_DEFINITION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MODEL_LIBRARY modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE UMG_RUNTIME_TRANSACTION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE UMG_VERSION modify COLUMN CREATED_BY VARCHAR(100)  COLLATE utf8_bin NOT NULL;
ALTER TABLE MAPPING modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MAPPING_OUTPUT modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL_DEFINITION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE MODEL_LIBRARY modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE UMG_RUNTIME_TRANSACTION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE UMG_VERSION modify COLUMN LAST_UPDATED_BY VARCHAR(100)   COLLATE utf8_bin DEFAULT NULL;

ALTER TABLE MODEL_LIBRARY_AUDIT 
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE MAPPING_AUDIT 
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_INPUTS_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_LIBRARY_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_DEFINITION_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MODEL_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MAPPING_OUTPUT_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  MAPPING_INPUT_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  UMG_RUNTIME_TRANSACTION_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE  UMG_VERSION_AUDIT
MODIFY COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
MODIFY COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;




