

DELETE FROM `COMMAND` WHERE `NAME` = 'weekNActiveListingsFilter';

UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 2 WHERE  `NAME`='weekNPast12CyclesFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 3 WHERE  `NAME`='weekNOddListingsFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 4 WHERE  `NAME`='weekNAssignmentFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 5 WHERE  `NAME`='weekNZipStateFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 6 WHERE  `NAME`='weekNSSPmiFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 7 WHERE  `NAME`='weekNSOPFilter';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 8 WHERE  `NAME`='weekNRAIntegrarion';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 9 WHERE  `NAME`='weekNOutputFileCreate';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`= 10 WHERE `NAME`='weekNEmailIntegration';