USE localhost;

ALTER TABLE MODEL_LIBRARY ADD COLUMN `R_MANIFEST_FILE_NAME` VARCHAR(200) NULL COMMENT 'R Manifest file name' COLLATE 'utf8_bin';

ALTER TABLE MODEL_LIBRARY_AUDIT ADD COLUMN `R_MANIFEST_FILE_NAME` VARCHAR(200) NULL COMMENT 'R Manifest file name' COLLATE 'utf8_bin';

ALTER TABLE `MODEL_LIBRARY` ADD COLUMN `PACKAGE_NAME` VARCHAR(200) NULL;

ALTER TABLE `MODEL_LIBRARY_AUDIT` ADD COLUMN `PACKAGE_NAME` VARCHAR(200) NULL;