ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	ADD COLUMN `STATUS` VARCHAR(50) NULL AFTER `TRANSACTION_ID`,
	ADD COLUMN `ERROR` VARCHAR(50) NULL AFTER `STATUS`;
	
ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	DROP FOREIGN KEY `FK_BATCH_RUNTIME_TXN_MAPPING_BATCH`,
	DROP INDEX `FK_BATCH_RUNTIME_TXN_MAPPING_BATCH`;
	
ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	DROP INDEX `FK_BATCH_RUNTIME_TXN_MAPPING_TRANSACTION`,
	DROP FOREIGN KEY `FK_BATCH_RUNTIME_TXN_MAPPING_TRANSACTION`;
	
ALTER TABLE `BATCH_TXN_RUNTIME_TXN_MAPPING`
	ADD CONSTRAINT `FK_BATCH_RUNTIME_TXN_MAPPING_BATCH` FOREIGN KEY (`BATCH_ID`) REFERENCES `BATCH_TRANSACTION` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;	