use `Ocwen`;

ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `TERMINATE_COUNT`;

ALTER TABLE `BATCH_TRANSACTION` ADD COLUMN `STORE_RLOGS` VARCHAR(10) NOT NULL DEFAULT 'FALSE' AFTER `MODELLING_ENVIRONMENT`;

commit;