SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY_RESULT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_RESULT_TYPES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_RESULT_TYPES` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `TYPE_NAME` VARCHAR(50) NOT NULL ,
  `CREATED_BY` CHAR(36) NOT NULL, 
  `CREATED_ON` BIGINT NOT NULL,
  `LAST_UPDATED_BY` CHAR(36) NULL, 
  `LAST_UPDATED_ON` BIGINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TYPE_NAME_IDX` (TYPE_NAME))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `MAPPING_ID` CHAR(36) NOT NULL ,
  `NAME` VARCHAR(50) NOT NULL ,
  `DESCRIPTION` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL ,
  `EXEC_SEQUENCE` INT NOT NULL ,
  `SELECT_COMPONENT` VARCHAR(500) NOT NULL ,
  `FROM_COMPONENT` VARCHAR(200) NOT NULL ,
  `WHERE_COMPONENT` VARCHAR(500) NULL ,
  `ORDER_BY_COMPONENT` VARCHAR(100) NULL ,
  `EXEC_QUERY` VARCHAR(3000) NULL,
  `ROW_TYPE` VARCHAR(12) NOT NULL,
  `DATA_TYPE` VARCHAR(20) NOT NULL,
  `MAPPING_TYPE` VARCHAR(15) NOT NULL,
  `CREATED_BY` CHAR(36) NOT NULL, 
  `CREATED_ON` BIGINT NOT NULL,
  `LAST_UPDATED_BY` CHAR(36) NULL, 
  `LAST_UPDATED_ON` BIGINT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- -----------------------------------------------------
-- Table `SYND_DATA_QUERY_INPUTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_INPUTS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_INPUTS` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `SYNDICATE_DATA_QUERY_ID` CHAR(36) NOT NULL ,
  `NAME` VARCHAR(50) NULL ,
  `DATA_TYPE` VARCHAR(25) NOT NULL ,
  `SAMPLE_VALUE` VARCHAR(50) NULL ,
  `MANDATORY` TINYINT NOT NULL,
  `CREATED_BY` CHAR(36) NOT NULL, 
  `CREATED_ON` BIGINT NOT NULL,
  `LAST_UPDATED_BY` CHAR(36) NULL, 
  `LAST_UPDATED_ON` BIGINT NULL,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT FK_INPUTS_QUERYS FOREIGN KEY (SYNDICATE_DATA_QUERY_ID) REFERENCES SYNDICATE_DATA_QUERY(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY_OUTPUTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_OUTPUTS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_OUTPUTS` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `SYNDICATE_DATA_QUERY_ID` CHAR(36) NOT NULL ,
  `NAME` VARCHAR(50) NULL ,
  `DATA_TYPE` VARCHAR(25) NOT NULL ,
  `MANDATORY` TINYINT NOT NULL,
  `SEQUENCE` INT NOT NULL,
  `CREATED_BY` CHAR(36) NOT NULL, 
  `CREATED_ON` BIGINT NOT NULL,
  `LAST_UPDATED_BY` CHAR(36) NULL, 
  `LAST_UPDATED_ON` BIGINT NULL,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT FK_OUTPUTS_QUERYS FOREIGN KEY (SYNDICATE_DATA_QUERY_ID) REFERENCES SYNDICATE_DATA_QUERY(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION )
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

