

CREATE TABLE `PMI_INSURANCE_COMPANY_FILES` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`UPLOADED_FILE_NAME` VARCHAR(100) NOT NULL,
	`ACTIVE` TINYINT(1) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;


CREATE TABLE `PMI_INSURANCE_COMPANIES` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`PMI_INSURANCE_COMPANY_FILE_ID` CHAR(36) NOT NULL DEFAULT '',
	`COMPANY_CODE` VARCHAR(20) NOT NULL,
	`INSURANCE_COMPANY` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `PMI_INSURANCE_COMPANY_FILE_ID_FK` FOREIGN KEY (`PMI_INSURANCE_COMPANY_FILE_ID`) REFERENCES `PMI_INSURANCE_COMPANY_FILES` (`ID`)
)ENGINE=InnoDB;

