
ALTER TABLE MODEL_LIBRARY
ADD COLUMN `CHECKSUM_TYPE` VARCHAR(45) NOT NULL AFTER `JAR_NAME`,
ADD COLUMN `CHECKSUM_VALUE` VARCHAR(100) NOT NULL AFTER `CHECKSUM_TYPE`;

ALTER TABLE MODEL_LIBRARY_AUDIT 
ADD COLUMN `CHECKSUM_TYPE` VARCHAR(45) NULL DEFAULT NULL AFTER `JAR_NAME`,
ADD COLUMN `CHECKSUM_VALUE` VARCHAR(100) NULL DEFAULT NULL AFTER `CHECKSUM_TYPE`;
