
SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `RA_TNT_SYSTEM_PARAMETERS` (`ID`, `SYS_KEY`,`SYS_VALUE`,`DESCRIPTION`,`CREATED_BY`,`CREATED_ON`,`LAST_UPDATED_BY`,`LAST_UPDATED_ON`) 
VALUES (UUID(),'qa.sop.daily.report.schedule.status', 'TRUE','Daily QA SOP WeekN report enable or disable',@CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `SOP_WEEKN_DAILY_RUN_STATUS` (`ID`, `LAST_RUN_DATE`, `FETCH_START_DATE`, `FETCH_END_DATE`, `TOTAL_RECORD`, `REPORT_TYPE`, `START_TIME`, `END_TIME`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`)
    VALUES (UUID(), '2019-11-01 00:00:00', '2019-10-01', '2019-10-31', 1, 'QA-REPORT', 0, 0, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
	
SELECT ID from `RA_TNT_APPS` WHERE `NAME` = 'DPA' INTO @APP_ID;

SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`)
VALUES (UUID(), @APP_ID, 'sop.weekN.qa.report.email.body', 'Please find the summary of Dynamic Pricing Daily SOP QA report run on {0}.<br/><br/><table style="border: 1px solid #c1c7d0;text-align: center;border-spacing: 0px;"><tr style="background:aliceblue"><th style="border: 1px solid #c1c7d0"><b>Total Count</b></th><th style="border: 1px solid #c1c7d0"><b>Success Count</b></th><th style="border: 1px solid #c1c7d0"><b>Failure Count</b></th><th style="border: 1px solid #c1c7d0"><b>Run date</b></th></tr><tr><td style="border: 1px solid #c1c7d0;">{1}</td><td style="border: 1px solid #c1c7d0;">{2}</td><td style="border: 1px solid #c1c7d0;">{3}</td><td style="border: 1px solid #c1c7d0;">{4}</td></tr></table><br/>List of Failed Loan numbers:<br/>{5}<br/><br/>Thanks,<br/>REALAnalyticsSupport', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), @APP_ID, 'sop.weekn.qa.report.to.list', 'ramgopalvarma.sai@altisource.com; realanalyticssupport@altisource.com', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`)
VALUES (UUID(), @APP_ID, 'sop.weekn.qa.report.cc.list', '', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), @APP_ID, 'sop.weekN.dp.email.qa.report.file.subject', ' Dynamic Pricing Daily SOP QA Report - {0}', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
	
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), @APP_ID, 'sop.weekn.qa.report.from', 'realanalyticssupport@altisource.com', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
	
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), @APP_ID, 'sop.weekN.qa.report.error.email.body', 'Please find the error summary of Dynamic Pricing SOP QA report run on {0}.<br/><br/>{1}<br/><br/>Thanks,<br/>REALAnalyticsSupport', NULL, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);	
	
SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

SET @PROCESS = 'SOP_QA_REPORT';

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
(UUID(), 'weekNEmailIntegrationSOP', 'WEEKN_EMAIL_INTEGRATION_SOP', 13, 'SOP_WEEKN_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
(UUID(), 'weekNEmailIntegrationSOP', 'WEEKN_EMAIL_INTEGRATION_SOP', 13, 'SOP_WEEKN_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
(UUID(), 'weekNEmailIntegrationSOP', 'WEEKN_EMAIL_INTEGRATION_SOP', 13, 'SOP_WEEKN_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'sopQaReportFetchData', 'SOP QA Report Fetch Data', 1, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'sopQaReportAssignmentFilter', 'SOP QA Report assignment filter', 2, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'sopQaReportPast12CyclesFilter', 'SOP QA Report Past 12 cycle filter', 3, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'sopQaReportStateFilter', 'SOP QA Report State filter', 4, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'sopQaReportSSPmiFilter', 'SOP QA Report SS PMI filter', 5, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
