/*DB name*/
USE umg_admin;

/*alter script to increase KEY_TYPE size to 200*/
alter table SYSTEM_KEY modify KEY_TYPE varchar(200) COLLATE utf8_bin NOT NULL;

/*insert script to insert new system key COLUMN_IDENTIFIERS*/
INSERT INTO SYSTEM_KEY(ID,SYSTEM_KEY,KEY_TYPE,CREATED_BY,CREATED_ON,LAST_UPDATED_BY,LAST_UPDATED_ON)
VALUES ('74246ec4-fac3-11e3-801d-b2227cce2c54','COLUMN_IDENTIFIERS','STRING,VARCHAR,DECIMAL,DOUBLE,BIT,INTEGER, INT, SMALLINT, TINYINT, MEDIUMINT, BIGINT,TIMESTAMP,TIME,YEAR,DATETIME,DATE','SYSTEM',1401344421,'SYSTEM',1401344421);
