

CREATE TABLE IF NOT EXISTS `WEEKN_DAILY_RUN_STATUS` (
  `ID` varchar(255) NOT NULL,
  `LAST_RUN_DATE` varchar(55) DEFAULT NULL,
  `TOTAL_RECORD` INT(11) DEFAULT NULL,
  `SUCCESS_COUNT` INT(11) DEFAULT NULL,
  `FAIL_COUNT` INT(11) DEFAULT NULL,
  `REPORT_TYPE` varchar(55) DEFAULT NULL,
  `START_TIME` bigint(20) DEFAULT NULL,
  `END_TIME` bigint(20) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `WEEKN_DAILY_QA_REPORT` (
	`ID` varchar(255) NOT NULL,
	`RUN_STATUS_ID` varchar(255) NOT NULL,
	`SELR_PROP_ID_VC_NN` varchar(55) DEFAULT NULL,
	`RBID_PROP_ID_VC_PK` varchar(55) DEFAULT NULL,
	`REO_PROP_STTS_VC` varchar(55) DEFAULT NULL,
	`PROP_SOLD_DATE_DT` varchar(55) DEFAULT NULL,
	`PROP_STTS_ID_VC_FK` varchar(55) DEFAULT NULL,
	`RBID_PROP_LIST_ID_VC_PK` varchar(55) DEFAULT NULL,
	`LIST_TYPE_ID_VC_FK` varchar(55) DEFAULT NULL,
	`PREVIOUS_LIST_STRT_DATE` varchar(55) DEFAULT NULL,
	`PREVIOUS_LIST_END_DATE` varchar(55) DEFAULT NULL,
	`PREVIOUS_LIST_PRICE` varchar(55) DEFAULT NULL,
	`CURRENT_LIST_STRT_DATE` varchar(55) DEFAULT NULL,
	`CURRENT_LIST_END_DATE` varchar(55) DEFAULT NULL,
	`LIST_PRCE_NT` varchar(55) DEFAULT NULL,
	`LIST_STTS_DTLS_VC` varchar(55) DEFAULT NULL,
	`OCCPNCY_STTS_AT_LST_CREATN` varchar(15) DEFAULT NULL,
	`ACTUAL_LIST_CYCLE` varchar(15) DEFAULT NULL,
	`WEEKN_RECOMMENDED_LIST_PRICE_REDUCTION` varchar(55) DEFAULT NULL,
	`WEEKN_RECOMMENDED_DATE` varchar(55) DEFAULT NULL,
	`WEEKN_EXCLUSION_REASON` varchar(255) DEFAULT NULL,
	`PCT_PRICE_CHANGE_FRM_LAST_LIST` varchar(255) DEFAULT NULL,
	`RULE_VIOLATION` varchar(15) DEFAULT NULL,
	`WEEKN_MISSINGREPORT` varchar(15) DEFAULT NULL,
	`CLASSIFICATION` varchar(15) DEFAULT NULL,
	`STATUS` varchar(15) DEFAULT NULL,
	`CREATED_BY` varchar(255) NOT NULL,
	`CREATED_ON` bigint(20) NOT NULL,
	`LAST_UPDATED_BY` varchar(255) DEFAULT NULL,
	`LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `DAILY_RUN_STATUS_ID_FK` FOREIGN KEY (`RUN_STATUS_ID`) REFERENCES `WEEKN_DAILY_RUN_STATUS` (`ID`)	
) ENGINE=InnoDB;

SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `RA_TNT_SYSTEM_PARAMETERS` (`ID`, `SYS_KEY`,`SYS_VALUE`,`DESCRIPTION`,`CREATED_BY`,`CREATED_ON`,`LAST_UPDATED_BY`,`LAST_UPDATED_ON`) 
VALUES (UUID(),'qa.daily.report.schedule.status', 'TRUE','Daily QA report enable or disable',@CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `WEEKN_DAILY_RUN_STATUS` (`ID`, `LAST_RUN_DATE`, `TOTAL_RECORD`, `SUCCESS_COUNT`, `FAIL_COUNT`, `REPORT_TYPE`, `START_TIME`, `END_TIME`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES
	(UUID(), '31-May-19 00:00:00.000', 0, 0, 0, 'QA-REPORT', @CREATED_ON, @CREATED_ON, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
