

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST WHERE (RBID_PROP_ID_VC_FK, TO_DATE(LIST_STRT_DATE_DT_NN)) IN (SELECT RBID_PROP_ID_VC_FK, MAX(TO_DATE(LIST_STRT_DATE_DT_NN)) FROM RRRBPMTX_PROP_LIST WHERE TO_DATE(LIST_STRT_DATE_DT_NN) BETWEEN TO_DATE(?) AND TO_DATE(?) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) GROUP BY RBID_PROP_ID_VC_FK) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) AND LIST_TYPE_ID_VC_FK = \'AUCN\' AND OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND TO_DATE(LIST_END_DATE_DT_NN) < TO_DATE(?)' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY';


DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'SUCCESS_UNDERREVIEW_HUBZU_QUERY';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'SUCCESS_UNDERREVIEW_INITAL_HUBZU_QUERY';

SELECT ID from `RA_TNT_APPS` WHERE LOWER(code) = 'dpa' INTO @APP_ID;
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID,  'SUCCESS_UNDERREVIEW_HUBZU_QUERY', 'SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE OT1.SELR_PROP_ID_VC_NN = ? AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\') ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC', 'SYSTEM', NOW());

SELECT ID from `RA_TNT_APPS` WHERE LOWER(code) = 'dpa' INTO @APP_ID;
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'SUCCESS_UNDERREVIEW_INITAL_HUBZU_QUERY', 'SELECT SELR_PROP_ID_VC_NN, PROP_SOLD_DATE_DT FROM RRRBPMMS_PROP WHERE SELR_PROP_ID_VC_NN =? AND  PROP_SOLD_DATE_DT IS NOT NULL', 'SYSTEM', NOW());

ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `PROP_SOLD_DATE_DT` VARCHAR(50) NULL DEFAULT NULL AFTER `CLASSIFICATION`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_INTG_AUDITS`;
CREATE TABLE IF NOT EXISTS `DP_SOP_WEEKN_INTG_AUDITS` (
  `ID` char(36) NOT NULL,
  `EVENT_TYPE` varchar(100) DEFAULT NULL,
  `DP_SOP_WEEKN_FILE_ID` char(36) DEFAULT NULL,
  `RECORD_ID` char(36) NOT NULL,
  `STATUS` varchar(100) DEFAULT NULL,
  `ERROR_DESCRIPTION` varchar(100) DEFAULT NULL,
  `START_TIME` bigint(20) DEFAULT NULL,
  `END_TIME` bigint(20) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_ON` bigint(20) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(100) DEFAULT NULL,
  `LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DP_SOP_WEEKN_PARAMS_FK` (`RECORD_ID`),
  CONSTRAINT `DP_SOP_WEEKN_PARAMS_FK` FOREIGN KEY (`RECORD_ID`) REFERENCES `DP_SOP_WEEKN_PARAMS` (`ID`)
)ENGINE=InnoDB;