use ocwen;

ALTER TABLE UMG_RUNTIME_TRANSACTION ADD COLUMN TRANSACTION_MODE VARCHAR(50) DEFAULT 'Online';

ALTER TABLE UMG_RUNTIME_TRANSACTION_AUDIT ADD COLUMN TRANSACTION_MODE VARCHAR(50) DEFAULT 'Online';

commit;
