ALTER TABLE `PMI_INSURANCE_COMPANIES`
	CHANGE COLUMN `COMPANY_CODE` `COMPANY_CODE` VARCHAR(20) NOT NULL AFTER `PMI_INSURANCE_COMPANY_FILE_ID`,
	CHANGE COLUMN `INSURANCE_COMPANY` `INSURANCE_COMPANY` VARCHAR(100) NOT NULL AFTER `COMPANY_CODE`;