
Delete FROM `umg_admin`.`SYSTEM_PARAMETER` where SYS_KEY = 'TRAN_DSHBRD_SELECTN_RECRD_CNT_LIMIT';

Delete FROM `umg_admin`.`SYSTEM_PARAMETER` where SYS_KEY = 'BATCH_DSHBRD_SELECTN_RECRD_CNT_LIMIT';

