CREATE TABLE `model_support_package` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(50) NOT NULL COMMENT 'Group Name of the model library support package, given by user as TAG.' COLLATE 'utf8_bin',
	`ENVIRONMENT` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(30) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(100) NOT NULL COMMENT 'The name of the SUPPORT PACKAGE FILE uploaded' COLLATE 'utf8_bin',
	`CHECKSUM_TYPE` VARCHAR(45) NOT NULL COLLATE 'utf8_bin',
	`CHECKSUM_VALUE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(50) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `MODEL_SUPP_PKG_PACKAGE_NAME` (`PACKAGE_NAME`)
)
COMMENT='The table which contains the individual model library suppport package definitions'
COLLATE='utf8_bin'
ENGINE=InnoDB;

CREATE TABLE `model_support_package_audit` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`PACKAGE_FOLDER` VARCHAR(50) NOT NULL COMMENT 'Group Name of the model library support package, given by user as TAG.' COLLATE 'utf8_bin',
	`ENVIRONMENT` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ENVIRONMENT_VERSION` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`PACKAGE_NAME` VARCHAR(100) NOT NULL COMMENT 'The name of the SUPPORT PACKAGE FILE uploaded' COLLATE 'utf8_bin',
	`CHECKSUM_TYPE` VARCHAR(64) NOT NULL COLLATE 'utf8_bin',
	`CHECKSUM_VALUE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_BY` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`, `REV`),
	INDEX `IDX_MODEL_SUPPORT_PACKAGE_AUDIT_REVINFO` (`REV`),
	CONSTRAINT `FK_MODEL_SUPPORT_PACKAGE_AUDIT_REVINFO` FOREIGN KEY (`REV`) REFERENCES `revinfo` (`REV`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;
