ALTER TABLE `umg_runtime_transaction`
CHANGE COLUMN `TENANT_INPUT` `TENANT_INPUT` MEDIUMBLOB NULL AFTER `STATUS`,
CHANGE COLUMN `TENANT_OUTPUT` `TENANT_OUTPUT` MEDIUMBLOB NULL COMMENT 'The actual tenant output.' AFTER `TENANT_INPUT`,
CHANGE COLUMN `MODEL_INPUT` `MODEL_INPUT` MEDIUMBLOB NULL AFTER `TENANT_OUTPUT`,
CHANGE COLUMN `MODEL_OUTPUT` `MODEL_OUTPUT` MEDIUMBLOB NULL COMMENT 'The actual output from the model.' AFTER `MODEL_INPUT`;

