

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'INITIAL_HUBZU_QUERY';

SELECT ID from `RA_TNT_APPS` WHERE LOWER(code) = 'dpa' INTO @APP_ID;
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'INITIAL_HUBZU_QUERY', 'SELECT SELR_PROP_ID_VC_NN,PROP_STAT_ID_VC_FK,PROP_ZIP_VC_FK, SELR_ACNT_ID_VC_FK, RBID_PROP_ID_VC_PK FROM RRRBPMMS_PROP WHERE RBID_PROP_ID_VC_PK IN (SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST WHERE LIST_TYPE_ID_VC_FK IN (\'AUCN\') AND LIST_END_DATE_DT_NN BETWEEN TO_DATE(?) AND TO_DATE(?)) ORDER by SELR_ACNT_ID_VC_FK, SELR_PROP_ID_VC_NN', 'SYSTEM', NOW());


