UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT c.PROP_TEMP AS loan_id, a.client_code FROM ENT_REPOS.er_invs a, ENT_REPOS.er_loan_invs b, ENT_REPOS.ER_PROPS c WHERE a.inv_id = b.inv_id AND b.active_flag=1 AND b.loan_id = c.LOAN_TEMP AND c.PROP_TEMP IN (:idList)' WHERE  `ATTR_KEY`='SS_RR_QUERY';

DROP TABLE IF EXISTS `DP_WEEKN_AUDIT_REPORTS`;
CREATE TABLE IF NOT EXISTS `DP_WEEKN_AUDIT_REPORTS` (
  `ID` char(36) NOT NULL,
  `RUN_DATE` bigint(20) NOT NULL,
  `DELIVERY_DATE`  bigint(20) DEFAULT NULL,
  `LOAN_NUMBER` char(36) NOT NULL,
  `CLASSIFICATION` varchar(100) DEFAULT NULL,
  `ACTION` varchar(100) DEFAULT NULL,
  `PERMANENT_EXCLUSION`  BOOL,
  `CREATED_BY` varchar(100) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `LAST_UPDATED_BY` varchar(100) DEFAULT NULL,
  `LAST_UPDATED_ON` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY RUNDATE_LOANNUMBER (RUN_DATE , LOAN_NUMBER)
  ) ENGINE=InnoDB;
  
DROP INDEX RUNDATE_LOANNUMBER ON DP_WEEKN_AUDIT_REPORTS;