

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE` = 'SELECT SELR_PROP_ID_VC_NN, CLNT_CODE_VC, IS_SPCL_HNDL_PROP_VC FROM RRRBPMMS_PROP WHERE SELR_PROP_ID_VC_NN IN (:idList)' WHERE `ATTR_KEY` = 'SS_PMI_HUBZU_QUERY';
