-- -----------------------------------------------------
-- Table `BATCH_TRANSACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BATCH_TRANSACTION` (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(50) NOT NULL,
  BATCH_FILE_NAME VARCHAR(100) NOT NULL,
  STATUS VARCHAR(25) NOT NULL,
  START_TIME BIGINT(20) NULL, 
  END_TIME BIGINT(20) NULL, 
  TOTAL_RECORDS BIGINT NULL,
  SUCCESS_COUNT BIGINT NULL,
  FAIL_COUNT BIGINT NULL,
  CREATED_BY CHAR(36) NOT NULL COMMENT 'User created the record.',
  CREATED_ON BIGINT(20) NOT NULL COMMENT 'Record created time.',
  LAST_UPDATED_BY CHAR(36) NULL COMMENT 'User last updated the record.',
  LAST_UPDATED_ON BIGINT(20) NULL COMMENT 'Record last updated time.',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BATCH_TXN_RUNTIME_TXN_MAPPING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BATCH_TXN_RUNTIME_TXN_MAPPING` (
  ID CHAR(36) NOT NULL,
  BATCH_ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(50) NOT NULL,
  TRANSACTION_ID CHAR(36) NOT NULL,
  CREATED_BY CHAR(36) NOT NULL COMMENT 'User created the record.',
  CREATED_ON BIGINT(20) NOT NULL COMMENT 'Record created time.',
  LAST_UPDATED_BY CHAR(36) NULL COMMENT 'User last updated the record.',
  LAST_UPDATED_ON BIGINT(20) NULL COMMENT 'Record last updated time.',
  CONSTRAINT `FK_BATCH_RUNTIME_TXN_MAPPING_BATCH` FOREIGN KEY (`BATCH_ID`) REFERENCES `BATCH_TRANSACTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_BATCH_RUNTIME_TXN_MAPPING_TRANSACTION` FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `UMG_RUNTIME_TRANSACTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `TRANSPORT_PARAMETER_VALUES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TRANSPORT_PARAMETER_VALUES` (
  ID CHAR(36) NOT NULL,
  TENANT_ID VARCHAR(45) NOT NULL,
  TRANSPORT_NAME VARCHAR(45) NOT NULL,
  PARAMETER_NAME VARCHAR(45) NULL,
  PARAMETER_VALUE VARCHAR(45) NULL,
  CREATED_BY CHAR(36) NOT NULL COMMENT 'User created the record.',
  CREATED_ON BIGINT(20) NOT NULL COMMENT 'Record created time.',
  LAST_UPDATED_BY CHAR(36) NULL COMMENT 'User last updated the record.',
  LAST_UPDATED_ON BIGINT(20) NULL COMMENT 'Record last updated time.',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
