ALTER TABLE `BATCH_TRANSACTION`
CHANGE COLUMN `BATCH_FILE_NAME` `BATCH_INPUT_FILE` VARCHAR(100) NOT NULL COLLATE 'utf8_bin' AFTER `TENANT_ID`,
ADD COLUMN `BATCH_OUTPUT_FILE` VARCHAR(100) NULL AFTER `BATCH_INPUT_FILE`,
ADD COLUMN `IS_TEST` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'Indicates whether the upload is from test bed' AFTER `STATUS`;
