-- Rollback Commands to exclude NRZ, OCN AND PHH Loans --
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'sop.weekn.top.rows.hubzu.query';
DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'sop.weekn.all.rows.hubzu.query';

ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	DROP COLUMN `LIST_STRT_DATE_DT_NN`,
	DROP COLUMN `LIST_END_DATE_DT_NN`,
	DROP COLUMN `MOST_RECENT_LIST_END_DATE`,
	DROP COLUMN `MOST_RECENT_LIST_STATUS`,
	DROP COLUMN `PROP_SOLD_DATE_DT`,
	DROP COLUMN `PRIOR_RECOMMENDED`,
	DROP COLUMN `DATE_OF_LAST_REDUCTION`,
	DROP COLUMN `MOST_RECENT_PROPERTY_STATUS`,
	DROP COLUMN `MOST_RECENT_LIST_PRICE`;
