

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE` = 'SELECT LOAN_NUM, INSURANCE_COMPANY_ID, AS_OF_DT, FC_INVENTORY_FLAG,  NRZ_ACQUISITION_DT, SPECIAL_SERVICING_FLAG, PMI_FLAG, PROP_TEMP, OLD_RR_LOAN_NUM, CLIENT_ID FROM SHAHMAYU.REO_PORTFOLIO_MASTER WHERE PROP_TEMP = ? ORDER BY AS_OF_DT DESC FETCH FIRST 1 ROW ONLY' WHERE `ATTR_KEY` = 'RR_CLASSIFICATION_QUERY';
