USE umg_admin;

Delete from SYSTEM_PARAMETER where sys_key = 'BATCH_MODELET_POLLING_INTERVAL';

commit;

USE `Ocwen`;

ALTER TABLE `BATCH_TRANSACTION`  DROP COLUMN `BATCH_MODELET_POLLING_INTERVAL`;

commit;