

ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	ADD COLUMN `ASSIGNMENT` VARCHAR(100) NULL AFTER `CLASSIFICATION`;
	
ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	ADD COLUMN `ASSIGNMENT_DATE` BIGINT(20) NULL DEFAULT NULL AFTER `ASSIGNMENT`;
	
ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	ADD COLUMN `UPLOAD_FLAG` CHAR(15) NULL AFTER `DP_SOP_WEEK0_FILE_ID`;
	
ALTER TABLE `DP_SOP_WEEK0_PARAMS_ORIGINAL`
	ADD COLUMN `ASSIGNMENT` VARCHAR(100) NULL DEFAULT NULL AFTER `CLASSIFICATION`;
	

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`)
VALUES (UUID(), 'sopWeek0DuplicateFilter', 'DUPLICATE_FILTERING', 1, 'SOP_WEEK0_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeek0DuplicateFilter', 'DUPLICATE_FILTERING', 1, 'SOP_WEEK0_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeek0AssetValueFilter', 'ASSETVALUE_FILTERING', 2, 'SOP_WEEK0_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeek0AssetValueFilter', 'ASSETVALUE_FILTERING', 2, 'SOP_WEEK0_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopweek0ModeledBenchmarkCriteria', 'RULE_80_20', 3, 'SOP_WEEK0_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopweek0ModeledBenchmarkCriteria', 'RULE_80_20', 3, 'SOP_WEEK0_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW()));
