ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `BATCH_OUTPUT_FILE_TEMP` VARCHAR(200) NULL AFTER `BATCH_OUTPUT_FILE`;

update `BATCH_TRANSACTION` set BATCH_OUTPUT_FILE_TEMP = BATCH_OUTPUT_FILE ;

ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `BATCH_OUTPUT_FILE`;

ALTER TABLE `BATCH_TRANSACTION` 
CHANGE COLUMN `BATCH_OUTPUT_FILE_TEMP` `BATCH_OUTPUT_FILE` VARCHAR(200) DEFAULT NULL ;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `BATCH_INPUT_FILE_TEMP` VARCHAR(200) NULL AFTER `BATCH_INPUT_FILE`;

update `BATCH_TRANSACTION` set BATCH_INPUT_FILE_TEMP = BATCH_INPUT_FILE ;

ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `BATCH_INPUT_FILE`;

ALTER TABLE `BATCH_TRANSACTION` 
CHANGE COLUMN `BATCH_INPUT_FILE_TEMP` `BATCH_INPUT_FILE` VARCHAR(200) DEFAULT NULL ;