

ALTER TABLE `DP_WEEKN_PARAMS`
	ADD COLUMN `STATE` VARCHAR(2) NULL DEFAULT NULL AFTER `SELR_PROP_ID_VC_NN`,
	ADD COLUMN `ZIPCODE` VARCHAR(20) NULL DEFAULT NULL AFTER `STATE`,
	ADD COLUMN `CLIENT_CODE` VARCHAR(20) NULL DEFAULT NULL AFTER `ZIPCODE`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL`
	ADD COLUMN `STATE` VARCHAR(2) NULL DEFAULT NULL AFTER `SELR_PROP_ID_VC_NN`,
	ADD COLUMN `ZIPCODE` VARCHAR(20) NULL DEFAULT NULL AFTER `STATE`,
	ADD COLUMN `CLIENT_CODE` VARCHAR(20) NULL DEFAULT NULL AFTER `ZIPCODE`;
