ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	ADD COLUMN `UPLOAD_FLAG` CHAR(15) NULL DEFAULT NULL AFTER `DP_SOP_WEEK0_FILE_ID`;

ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	ADD COLUMN `DELIVERY_DATE` BIGINT(20) NULL DEFAULT NULL AFTER `FAILED_STEP_COMMAND_NAME`;