

DELETE FROM `COMMAND` WHERE `NAME` = 'week0ProcessFilter';

UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=5 WHERE  `NAME`='week0RRRtngAggregator';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=7 WHERE  `NAME`='week0CAIntegration';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=8 WHERE  `NAME`='week0ModeledBenchmarkCriteria';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=9 WHERE  `NAME`='week0RAInputPayload';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=10 WHERE  `NAME`='week0OutputFileCreate';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=11 WHERE  `NAME`='week0EmailIntegration';

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES 
(UUID(), 'week0AssetValueFilter', 'ASSET_VALUE_FILTERING', 4, 'WEEK0_OCN', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL),
(UUID(), 'week0AssetValueFilter', 'ASSET_VALUE_FILTERING', 4, 'WEEK0_NRZ', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL),
(UUID(), 'week0PropertyTypeFilter', 'PROPERTY_TYPE_FILTERING', 6, 'WEEK0_OCN', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL),
(UUID(), 'week0PropertyTypeFilter', 'PROPERTY_TYPE_FILTERING', 6, 'WEEK0_NRZ', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL);



ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` ALTER `UPLOAD_TIMESTAMP` DROP DEFAULT;
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` CHANGE COLUMN `UPLOAD_TIMESTAMP` `UPLOAD_TIMESTAMP` BIGINT(20) NOT NULL AFTER `PROCESS`;
