

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES 
(UUID(), 'week0ProcessFilter', 'AV_PT_FILTERING', 5, 'WEEK0_OCN', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL),
(UUID(), 'week0ProcessFilter', 'AV_PT_FILTERING', 5, 'WEEK0_NRZ', TRUE, 'SYSTEM', UNIX_TIMESTAMP(NOW()), NULL, NULL);

UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=4 WHERE  `NAME`='week0RRRtngAggregator';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=6 WHERE  `NAME`='week0CAIntegration';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=7 WHERE  `NAME`='week0ModeledBenchmarkCriteria';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=8 WHERE  `NAME`='week0RAInputPayload';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=9 WHERE  `NAME`='week0OutputFileCreate';
UPDATE `COMMAND` SET `EXECUTION_SEQUENCE`=10 WHERE  `NAME`='week0EmailIntegration';

DELETE FROM `COMMAND` WHERE `NAME` = 'week0AssetValueFilter';
DELETE FROM `COMMAND` WHERE `NAME` = 'week0PropertyTypeFilter';

ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS` CHANGE COLUMN `UPLOAD_TIMESTAMP` `UPLOAD_TIMESTAMP` varchar(50) DEFAULT NULL AFTER `PROCESS`;
