use `Ocwen`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` DROP COLUMN `ACCEPTABLEVALUES_VALIDATION`;

ALTER TABLE `MODEL_LIBRARY` DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `MODEL_LIBRARY_AUDIT`  DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `BATCH_TRANSACTION`  DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `BATCH_TRANSACTION`  DROP COLUMN `MODELLING_ENVIRONMENT`;

commit;
