use `umg_admin`;

UPDATE POOL_CRITERIA set CRITERIA_NAME = 'ENVIRONMENT' WHERE CRITERIA_NAME = 'EXECUTION_LANGUAGE';

UPDATE POOL_CRITERIA set CRITERIA_NAME = 'ENVIRONMENT_VERSION' WHERE CRITERIA_NAME = 'EXECUTION_LANGUAGE_VERSION';

UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 3 WHERE CRITERIA_NAME = 'MODEL';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 4 WHERE CRITERIA_NAME = 'MODEL_VERSION';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 5 WHERE CRITERIA_NAME = 'TENANT';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 6 WHERE CRITERIA_NAME = 'TRANSACTION_MODE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 7 WHERE CRITERIA_NAME = 'TRANSACTION_TYPE';
UPDATE POOL_CRITERIA set CRITERIA_PRIORITY = 8 WHERE CRITERIA_NAME = 'CHANNEL';

DELETE FROM POOL_CRITERIA WHERE  CRITERIA_NAME='EXECUTION_ENVIRONMENT';

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_VALUE = replace(POOL_CRITERIA_VALUE,'EXECUTION_LANGUAGE','ENVIRONMENT');

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = TRIM(REPLACE(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE,' & #EXECUTION_ENVIRONMENT# = Linux', ''));

UPDATE POOL SET `POOL_NAME`='R-Default' WHERE  `POOL_NAME`='R-Linux-Default';

UPDATE POOL SET `POOL_DESCRIPTION`='POOL OF R-Default' WHERE  `POOL_NAME`='R-Default';

UPDATE POOL SET `POOL_NAME`='Matlab-Default' WHERE  `POOL_NAME`='Matlab-Linux-Default';

UPDATE POOL SET `POOL_DESCRIPTION`='POOL OF Matlab-Default' WHERE  `POOL_NAME`='Matlab-Default';

DELETE FROM SYSTEM_PARAMETER WHERE SYS_KEY='R_MODELET_STARTUP_SCRIPT_WINDOWS';

DELETE FROM `POOL_USAGE_ORDER` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default');

DELETE FROM `POOL_CRITERIA_DEF_MAPPING` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default');

DELETE FROM `POOL` WHERE `POOL_NAME` = 'R-Windows-Default';

DELETE FROM `POOL_USAGE_ORDER` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default');

DELETE FROM `POOL_CRITERIA_DEF_MAPPING` WHERE  `POOL_ID`= (SELECT `ID` FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default');

DELETE FROM `POOL` WHERE `POOL_NAME` = 'Excel-Windows-Default';

DELETE FROM TENANT_CONFIG WHERE `SYSTEM_KEY_ID`=(SELECT `ID` FROM `SYSTEM_KEY` WHERE `SYSTEM_KEY` = 'AcceptableValues');	

DELETE FROM `SYSTEM_PARAMETER` WHERE SYS_KEY='MAX_DISPLAY_RECORDS_SIZE';

DELETE FROM `SYSTEM_PARAMETER` WHERE SYS_KEY='DEFAULT_SEARCH_PAGE_SIZE';

DELETE FROM `SYSTEM_PARAMETER` WHERE SYS_KEY = 'R_MODELET_RESTART_ERROR_CODES';

DELETE FROM `SYSTEM_KEY` WHERE SYSTEM_KEY='AcceptableValues';

DELETE FROM `MODEL_EXECUTION_ENVIRONMENTS` WHERE `EXECUTION_ENVIRONMENT` = 'Excel';
commit;