use `Ocwen`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` DROP COLUMN `ACCEPTABLEVALUES_VALIDATION`;

ALTER TABLE `MODEL_LIBRARY` DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `MODEL_LIBRARY_AUDIT`  DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `BATCH_TRANSACTION`  DROP COLUMN `EXECUTION_ENVIRONMENT`;

ALTER TABLE `BATCH_TRANSACTION`  DROP COLUMN `MODELLING_ENVIRONMENT`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` CHANGE COLUMN `CLIENT_TRANSACTION_ID` `CLIENT_TRANSACTION_ID` VARCHAR(50) NOT NULL COMMENT 'Transaction Number' COLLATE 'utf8_bin' AFTER `TENANT_ID`;

commit;
