DROP TABLE TENANT_CONFIG IF EXISTS;
DROP TABLE ADDRESS IF EXISTS;
DROP TABLE TENANT IF EXISTS;
DROP TABLE SYSTEM_KEY IF EXISTS;
DROP TABLE SYSTEM_PARAMETER IF EXISTS;
DROP TABLE SYSTEM_PARAMETER_AUD IF EXISTS;

CREATE TABLE ADDRESS (
	ID CHARACTER(36) NOT NULL,
	TENANT_ID CHARACTER(36) NOT NULL,
	ADDRESS_1 VARCHAR(45) NOT NULL,
	ADDRESS_2 VARCHAR(45),
	CITY VARCHAR(45) NOT NULL,
	STATE VARCHAR(45) NOT NULL,
	ZIP VARCHAR(45) NOT NULL,
	COUNTRY VARCHAR(45) NOT NULL,
	CREATED_BY CHARACTER(36) NOT NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHARACTER(36),
	LAST_UPDATED_ON BIGINT,
	PRIMARY KEY (ID)
);
CREATE TABLE SYSTEM_KEY (
	ID CHARACTER(36) NOT NULL,
	SYSTEM_KEY VARCHAR(45) NOT NULL,
	KEY_TYPE VARCHAR(45) NOT NULL,
	CREATED_BY CHARACTER(36) NOT NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHARACTER(36),
	LAST_UPDATED_ON BIGINT,
	PRIMARY KEY (ID)
);
CREATE TABLE TENANT (
	ID CHARACTER(36) NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	DESCRIPTION VARCHAR(255),
	CODE VARCHAR(45) NOT NULL,
	TENANT_TYPE VARCHAR(45) NOT NULL,
	AUTH_TOKEN VARCHAR(64),
	CREATED_BY CHARACTER(36) NOT NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHARACTER(36),
	LAST_UPDATED_ON BIGINT,
	PRIMARY KEY (ID)
);
CREATE TABLE TENANT_CONFIG (
	ID CHARACTER(36) NOT NULL,
	TENANT_ID CHARACTER(36) NOT NULL,
	SYSTEM_KEY_ID CHARACTER(36) NOT NULL,
	CONFIG_VALUE VARCHAR(45),
	CREATED_BY CHARACTER(36) NOT NULL,
	ROLE CHARACTER(20) NULL,
	CREATED_ON BIGINT NOT NULL,
	LAST_UPDATED_BY CHARACTER(36),
	LAST_UPDATED_ON BIGINT,
	PRIMARY KEY (ID)
);
ALTER TABLE ADDRESS
	ADD FOREIGN KEY (TENANT_ID) 
	REFERENCES TENANT (ID);


ALTER TABLE TENANT_CONFIG
	ADD FOREIGN KEY (TENANT_ID) 
	REFERENCES TENANT (ID);

ALTER TABLE TENANT_CONFIG
	ADD FOREIGN KEY (SYSTEM_KEY_ID) 
	REFERENCES SYSTEM_KEY (ID);

CREATE TABLE SYSTEM_PARAMETER(
			ID CHARACTER(36),
			SYS_KEY VARCHAR(100) ,
			SYS_VALUE VARCHAR(100),
			IS_ACTIVE CHARACTER(1),
			CREATED_BY VARCHAR(100),
			CREATED_ON BIGINT,
			LAST_UPDATED_BY VARCHAR(100),
			LAST_UPDATED_ON BIGINT,
			PRIMARY KEY(ID)
);
CREATE TABLE SYSTEM_PARAMETER_AUD(
			ID CHARACTER(36),
			SYS_KEY VARCHAR(100) ,
			SYS_VALUE VARCHAR(100),
			IS_ACTIVE CHARACTER(1),
			CREATED_BY VARCHAR(100),
			CREATED_ON BIGINT,
			LAST_UPDATED_BY VARCHAR(100),
			LAST_UPDATED_ON BIGINT,
			REV BIGINT,
			REVTYPE BIGINT,
			PRIMARY KEY(ID,REV)
);

