SELECT ID from RA_TNT_APPS WHERE LOWER(code) = 'dpa' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'sop.weekn.success.underreview.top.rows.hubzu.query', 'SELECT SELR_PROP_ID_VC_NN, PROP_SOLD_DATE_DT FROM RRRBPMMS_PROP WHERE SELR_PROP_ID_VC_NN IN (:idList) AND  PROP_SOLD_DATE_DT IS NULL', 'SYSTEM', NOW());

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'sop.weekn.success.underreview.all.rows.hubzu.query', 'SELECT T1.RBID_PROP_ID_VC_FK, T1.AUTO_RLST_VC, T1.OCCPNCY_STTS_AT_LST_CREATN, T1.RBID_PROP_LIST_ID_VC_PK, T1.LIST_STTS_DTLS_VC, T1.LIST_PRCE_NT, T1.LIST_STRT_DATE_DT_NN, T1.LIST_END_DATE_DT_NN, OT1.SELR_PROP_ID_VC_NN, OT1.PROP_STAT_ID_VC_FK, OT1.PROP_ZIP_VC_FK FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE OT1.SELR_PROP_ID_VC_NN IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'N\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') ORDER BY TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC', 'SYSTEM', NOW());

ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	ADD COLUMN `INITIAL_VALUATION` DECIMAL(20,0) NULL DEFAULT NULL AFTER `DELIVERY_DATE`,
	ADD COLUMN `LP_DOLLAR_ADJUSTMENT_REC` DECIMAL(10,0) NULL DEFAULT NULL AFTER `INITIAL_VALUATION`,
	ADD COLUMN `MODEL_VERSION` VARCHAR(50) NULL DEFAULT NULL AFTER `LP_DOLLAR_ADJUSTMENT_REC`,
	ADD COLUMN `CLIENT_CODE` VARCHAR(20) NULL DEFAULT NULL AFTER `MODEL_VERSION`,
	ADD COLUMN `LP_PERCENT_ADJUSTMENT_REC` DECIMAL(10,0) NULL DEFAULT NULL AFTER `CLIENT_CODE`;