/* set delimiter */
DELIMITER $$

/* remove procedure insert_authToken... */
DROP PROCEDURE IF EXISTS insert_supportpackages_r332 $$

/* create procedure insert_default_privileges*/ 
CREATE PROCEDURE insert_supportpackages_r332 ()
BEGIN
DECLARE exec_packages_length INT;
DECLARE x INT DEFAULT 0;
DECLARE ID_TEMP varchar(36);

/* drop temp table  TEMP_TABLE_TENANT */ 
DROP TABLE IF EXISTS TEMP_TABLE_SUPPORTPACKAGES_R332;
/* create temp table  TEMP_TABLE_TENANT */
create temporary table if not exists TEMP_TABLE_SUPPORTPACKAGES_R332
select ID AS ID,EXEC_PACKAGES.PACKAGE_NAME  AS PACKAGE_NAME,EXEC_PACKAGES.PACKAGE_FOLDER AS PACKAGE_FOLDER,EXEC_PACKAGES.PACKAGE_TYPE AS PACKAGE_TYPE,EXEC_PACKAGES.PACKAGE_VERSION AS PACKAGE_VERSION,EXEC_PACKAGES.COMPILED_OS AS COMPILED_OS,
EXEC_PACKAGES.CREATED_BY AS CREATED_BY,EXEC_PACKAGES.CREATED_ON AS CREATED_ON,EXEC_PACKAGES.LAST_UPDATED_BY AS LAST_UPDATED_BY,EXEC_PACKAGES.LAST_UPDATED_ON AS LAST_UPDATED_ON,EXEC_PACKAGES.EXECUTION_ENVIRONMENT AS EXECUTION_ENVIRONMENT,EXEC_PACKAGES.MODEL_EXEC_ENV_NAME AS MODEL_EXEC_ENV_NAME
from MODEL_EXEC_PACKAGES EXEC_PACKAGES WHERE PACKAGE_TYPE='ADDON';

UPDATE TEMP_TABLE_SUPPORTPACKAGES_R332 SET MODEL_EXEC_ENV_NAME='R-3.3.2';

SELECT COUNT(*) FROM TEMP_TABLE_SUPPORTPACKAGES_R332 INTO exec_packages_length;

SELECT exec_packages_length;

WHILE x < exec_packages_length DO

SELECT ID FROM TEMP_TABLE_SUPPORTPACKAGES_R332 LIMIT x,1 INTO ID_TEMP;
UPDATE TEMP_TABLE_SUPPORTPACKAGES_R332 SET ID=uuid() where ID=ID_TEMP;

SET x = x+1;
END WHILE;

INSERT INTO model_exec_packages SELECT * FROM TEMP_TABLE_SUPPORTPACKAGES_R332;


DROP TABLE TEMP_TABLE_SUPPORTPACKAGES_R332;

END $$

DELIMITER ;

CALL insert_supportpackages_r332();

DROP PROCEDURE insert_supportpackages_r332;






