CREATE TABLE MAPPING_INPUT_AUDIT (
  ID CHAR(36) NOT NULL,
  REV int(11) NOT NULL,
  REVTYPE tinyint(4) DEFAULT NULL,
  TENANT_ID CHAR(36) NULL COMMENT 'Tenant code for the record',
  MAPPING_ID CHAR(36) COMMENT 'Model used for this mapping',
  MAPPING_DATA BLOB COMMENT 'Complete mapping definition.',
  TENANT_INTERFACE_DEFINITION BLOB COMMENT 'Complete mapping definition.',
  CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_MAPPING_INPUT_AUDIT_REVINFO (REV),
  CONSTRAINT FK_MAPPING_INPUT_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;