USE UMG_ADMIN;

DELETE FROM POOL_CRITERIA WHERE  CRITERIA_NAME='CHANNEL';

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = TRIM(REPLACE(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE, '& #CHANNEL# = Any', ''));
		
COMMIT;
