use umg_admin;

INSERT INTO `SYSTEM_KEY` (`ID`, `SYSTEM_KEY`, `KEY_TYPE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(),'ModelOutput_Validation','TENANT','SYSTEM',UNIX_TIMESTAMP(),'SYSTEM',UNIX_TIMESTAMP());

commit;