USE UMG_ADMIN;

INSERT INTO POOL_CRITERIA VALUES (8, 'CHANNEL', 8);

UPDATE POOL_CRITERIA_DEF_MAPPING SET POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE = CONCAT(POOL_CRITERIA_DEF_MAPPING.POOL_CRITERIA_VALUE, ' & #CHANNEL# = Any');

COMMIT;
