
-- SOP WEEK0 TABLE STRUCTURE

DROP TABLE IF EXISTS `DP_SOP_WEEK0_PARAMS`;

DROP TABLE IF EXISTS `DP_SOP_WEEK0_PARAMS_ORIGINAL`;

DROP TABLE IF EXISTS `DP_SOP_WEEK0_PRCS_STATUS`;


CREATE TABLE `DP_SOP_WEEK0_PRCS_STATUS` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '',
	`STATUS` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEK0_PARAMS` (
	`ID` CHAR(36) NOT NULL,
	`DP_SOP_WEEK0_FILE_ID` CHAR(36) NOT NULL,
	`ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`OLD_ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`PROP_TEMP` VARCHAR(100) NOT NULL,
	`STATE` VARCHAR(2) NOT NULL,
	`PROPERTY_TYPE` VARCHAR(10) NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	`ASSET_VALUE` DECIMAL(10,0) NOT NULL,
	`AV_SET_DATE` VARCHAR(10) NOT NULL,
	`REO_DATE` VARCHAR(10) NOT NULL,
	`LIST_PRICE` DECIMAL(10,0) NOT NULL,
	`CLASSIFICATION` VARCHAR(10) NOT NULL,
	`ELIGIBLE` VARCHAR(100) NULL DEFAULT NULL,
	`ASSIGNMENT` VARCHAR(100) NULL DEFAULT NULL,
	`ASSIGNMENT_DATE` BIGINT(20) NULL DEFAULT NULL,
	`NOTES` VARCHAR(500) NULL DEFAULT NULL,
	`ERROR_DETAIL` VARCHAR(1000) NULL DEFAULT NULL,
	`FAILED_STEP_COMMAND_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `DP_SOP_INPUT_FILE_ID_FK` (`DP_SOP_WEEK0_FILE_ID`),
	CONSTRAINT `DP_SOP_INPUT_FILE_ID_FK` FOREIGN KEY (`DP_SOP_WEEK0_FILE_ID`) REFERENCES `DP_SOP_WEEK0_PRCS_STATUS` (`id`)
)ENGINE=InnoDB;


-- SOP WEEKN STRUCTURE

DROP TABLE IF EXISTS `DP_SOP_WEEKN_INTG_AUDITS`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PARAMS`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PARAMS_ORIGINAL`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PRCS_STATUS`;

CREATE TABLE `DP_SOP_WEEKN_PRCS_STATUS` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '',
	`STATUS` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEKN_PARAMS` (
	`ID` CHAR(36) NOT NULL,
	`DP_SOP_WEEKN_FILE_ID` CHAR(36) NULL DEFAULT NULL,
	`ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`OLD_ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`PROP_TEMP` VARCHAR(100) NOT NULL,
	`CLASSIFICATION` VARCHAR(15) NULL DEFAULT NULL,
	`ELIGIBLE` VARCHAR(15) NULL DEFAULT NULL,
	`ASSIGNMENT` VARCHAR(15) NULL DEFAULT NULL,
	`EXCLUSION_REASON` VARCHAR(100) NULL DEFAULT NULL,
	`RBID_PROP_ID_VC_PK` VARCHAR(100) NULL DEFAULT NULL,
	`STATE` VARCHAR(2) NULL DEFAULT NULL,
	`ZIPCODE` VARCHAR(20) NULL DEFAULT NULL,
	`PRIVATE_MORTGAGE_INSURANCE` VARCHAR(20) NULL DEFAULT NULL,
	`SELLER_OCCUPIED_PROPERTY` VARCHAR(50) NULL DEFAULT NULL,
	`FAILED_STEP_COMMAND_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `DP_SOP_WEEKN_FILE_ID_FK` (`DP_SOP_WEEKN_FILE_ID`),
	CONSTRAINT `DP_SOP_WEEKN_FILE_ID_FK` FOREIGN KEY (`DP_SOP_WEEKN_FILE_ID`) REFERENCES `DP_SOP_WEEKN_PRCS_STATUS` (`id`)
)ENGINE=InnoDB;


DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_OCN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_NRZ';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_OCN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_NRZ';