use `Ocwen`;

ALTER TABLE SYNDICATE_DATA_QUERY_INPUTS DROP COLUMN DATATYPE_FORMAT;
ALTER TABLE SYNDICATE_DATA_QUERY_INPUTS_AUDIT DROP COLUMN DATATYPE_FORMAT;
ALTER TABLE SYNDICATE_DATA_QUERY_OUTPUTS DROP COLUMN DATATYPE_FORMAT;
ALTER TABLE SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT DROP COLUMN DATATYPE_FORMAT;

ALTER TABLE BATCH_TXN_RUNTIME_TXN_MAPPING DROP INDEX batch_txn_runtime_txn_mapping_index_2
ALTER TABLE UMG_VERSION DROP INDEX umg_version_index_1

DROP TABLE MODEL_SUPPORT_PACKAGE_AUDIT;
DROP TABLE MODEL_SUPPORT_PACKAGE;