use umg_admin;

DELETE FROM `POOL_USAGE_ORDER`;

DELETE FROM `POOL_CRITERIA_DEF_MAPPING`;

DELETE FROM `POOL`;

INSERT INTO `POOL` (`ID`, `POOL_NAME`, `POOL_DESCRIPTION`, `IS_DEFAULT_POOL`, `ENVIRONMENT`, `POOL_STATUS`, `MODELET_COUNT`, `MODELET_CAPACITY`, `PRIORITY`) VALUES
	('1', 'Matlab-Default', 'POOL OF Matlab-Default ', 1, 'Matlab', NULL, 11, '1GB - Linux 64 bit', 1),
	('2', 'R-Default', 'POOL OF R-Default', 1, 'R', NULL, 10, '4GB - Linux 64 bit', 1);


INSERT INTO `POOL_CRITERIA_DEF_MAPPING` (`ID`, `POOL_ID`, `POOL_CRITERIA_VALUE`) VALUES
	('1', '1', '#TENANT# = Any & #ENVIRONMENT# = Matlab & #ENVIRONMENT_VERSION# = 7.16 & #TRANSACTION_TYPE# = Any & #MODEL# = Any & #MODEL_VERSION# = Any & #TRANSACTION_MODE# = Any'),
	('2', '2', '#TENANT# = Any & #ENVIRONMENT# = R & #ENVIRONMENT_VERSION# = 3.2.1 & #TRANSACTION_TYPE# = Any & #MODEL# = Any & #MODEL_VERSION# = Any & #TRANSACTION_MODE# = Any');


INSERT INTO `POOL_USAGE_ORDER` (`ID`, `POOL_ID`, `POOL_USAGE_ID`, `POOL_TRY_ORDER`, `CAN_USE_INPROGRES`) VALUES
	('1', '1', '1', 1, 0),
	('2', '2', '2', 1, 0);

commit;