ALTER TABLE UMG_RUNTIME_TRANSACTION ADD COLUMN ERROR_CODE CHAR(10) COMMENT 'Error code received while execution Model.';
ALTER TABLE UMG_RUNTIME_TRANSACTION ADD COLUMN ERROR_DESCRIPTION  VARCHAR(500) COLLATE utf8_bin DEFAULT NULL COMMENT 'Error description while Model execution.';

ALTER TABLE UMG_RUNTIME_TRANSACTION_AUDIT ADD COLUMN ERROR_CODE CHAR(10) COMMENT 'Error code received while execution Model.';
ALTER TABLE UMG_RUNTIME_TRANSACTION_AUDIT ADD COLUMN ERROR_DESCRIPTION  VARCHAR(500) COLLATE utf8_bin DEFAULT NULL COMMENT 'Error description while Model execution.';