-- Rollback Commands to exclude NRZ, OCN AND PHH Loans --
DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_PHH';
DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_OCN';
DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_NRZ';
