SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

SET @PROCESS = 'QA_REPORT';

-- Insert Commands to include and process  PHH Loans --
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'qaReportFetchData', 'QA Report Fetch Data', 1, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'qaReportAssignmentFilter', 'QA Report assignment filter', 2, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'qaReportPast12CyclesFilter', 'QA Report Past 12 cycle filter', 3, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'qaReportStateFilter', 'QA Report State filter', 4, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'qaReportSSPmiFilter', 'QA Report SS PMI filter', 5, @PROCESS, TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);


