ALTER TABLE  SYNDICATED_DATA_AUDIT
ADD COLUMN `CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL;