use ocwen;

ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `REQUESTED_BY`;
ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `REQUESTED_ON`;
ALTER TABLE UMG_VERSION_AUDIT DROP COLUMN `EMAIL_APPRROVAL`;

ALTER TABLE UMG_VERSION DROP COLUMN `REQUESTED_BY`;
ALTER TABLE UMG_VERSION DROP COLUMN `REQUESTED_ON`;
ALTER TABLE UMG_VERSION DROP COLUMN `EMAIL_APPRROVAL`;


ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `USER`;
ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `MODEL_NAME`;
ALTER TABLE `BATCH_TRANSACTION` DROP COLUMN `MODEL_VERSION`;


ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `CPU_USAGE`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `FREE_MEMORY`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `FREE_MEMORY_AT_START`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `CPU_USAGE_AT_START`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `IP_AND_PORT`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `POOL_NAME`;
ALTER TABLE UMG_RUNTIME_TRANSACTION DROP COLUMN `NO_OF_ATTEMPTS`;

COMMIT;