USE `umg_admin`;

set SQL_SAFE_UPDATES = 0;

DROP TABLE IF EXISTS AUTHTOKEN;

DROP TABLE IF EXISTS NOTIFICATION_EVENT_TEMPLATE_MAPPING;

DROP TABLE IF EXISTS NOTIFICATION_EMAIL_TEMPLATE;

DROP TABLE IF EXISTS NOTIFICATION_SMS_TEMPLATE;

DROP TABLE IF EXISTS NOTIFICATION_TYPE;

DROP TABLE IF EXISTS NOTIFICATION_EVENT;

DROP TABLE IF EXISTS SYSTEM_MODELETS;

DROP TABLE if exists `PERMISSION_ROLES_MAPPING`;

DROP TABLE if exists `PERMISSIONS`;

DROP TABLE if exists `TENANT_USER_TENANT_ROLE_MAPPING`;

DROP TABLE if exists  `TENANT_ROLES_MAPPING`;

DROP TABLE if exists  `TENANT_USER_MAPPING`;

DROP TABLE if exists `ROLES`;

DROP TABLE if exists `USERS_LOGIN_AUDIT`;

DROP TABLE if exists `USERS`;

DELETE FROM SYSTEM_PARAMETER WHERE SYS_KEY="MODELET_EXEC_TIME_LIMIT";

DELETE FROM SYSTEM_PARAMETER_AUDIT WHERE SYS_KEY="MODELET_EXEC_TIME_LIMIT";

COMMIT;
