use umg_admin;

set SQL_SAFE_UPDATES = 0;

DELETE FROM SYSTEM_PARAMETER WHERE SYS_KEY in ('SMTP_HOST_NAME', 'SMTP_SERVER', 'NOTIFICATION_TEMPLATE_DIR', 'UMG_ADMIN_URL', 'umgAdminUrl', 'FROM_ADDRESS', 'fromAddress', 'toAddress');

DELETE FROM SYSTEM_PARAMETER_AUDIT WHERE SYS_KEY in ('SMTP_HOST_NAME', 'SMTP_SERVER', 'NOTIFICATION_TEMPLATE_DIR', 'UMG_ADMIN_URL', 'umgAdminUrl', 'FROM_ADDRESS', 'fromAddress', 'toAddress');

DELETE FROM TENANT_CONFIG WHERE SYSTEM_KEY_ID = ( SELECT ID FROM SYSTEM_KEY WHERE SYSTEM_KEY in ("BULK_ENABLED", "EMAIL_NOTIFICATIONS_ENABLED"));

DELETE FROM SYSTEM_KEY WHERE SYSTEM_KEY in ("BULK_ENABLED", "EMAIL_NOTIFICATIONS_ENABLED");

	
COMMIT;

