use Ocwen;

ALTER TABLE UMG_VERSION CHANGE COLUMN `PUBLISHED_BY` `PUBLISHED_BY` VARCHAR(516) NULL DEFAULT NULL COMMENT 'User who published the umg version';

ALTER TABLE UMG_VERSION_AUDIT CHANGE COLUMN `PUBLISHED_BY` `PUBLISHED_BY` VARCHAR(516) NULL DEFAULT NULL COMMENT 'User who published the umg version';

ALTER TABLE UMG_VERSION 
ADD COLUMN `REQUESTED_BY` VARCHAR(512) NULL DEFAULT NULL,
ADD COLUMN `REQUESTED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `EMAIL_APPRROVAL` SMALLINT NULL DEFAULT 0;

ALTER TABLE UMG_VERSION_AUDIT 
ADD COLUMN `REQUESTED_BY` VARCHAR(512) NULL DEFAULT NULL,
ADD COLUMN `REQUESTED_ON` BIGINT(20) NULL DEFAULT NULL,
ADD COLUMN `EMAIL_APPRROVAL` SMALLINT NULL DEFAULT 0;


ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `USER` VARCHAR(200) NULL DEFAULT null COMMENT 'user name ' COLLATE 'utf8_bin' AFTER `TRANSACTION_MODE`;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `MODEL_NAME` VARCHAR(200) NULL DEFAULT null COMMENT 'model name' COLLATE 'utf8_bin' AFTER `USER`;

ALTER TABLE `BATCH_TRANSACTION`
ADD COLUMN `MODEL_VERSION` DOUBLE NULL DEFAULT null COMMENT 'model version' AFTER `MODEL_NAME`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` CHANGE COLUMN `STATUS` `STATUS` VARCHAR(20) NOT NULL COMMENT 'Transaction Status' COLLATE 'utf8_bin' AFTER `MINOR_VERSION`;


ALTER TABLE UMG_RUNTIME_TRANSACTION
ADD COLUMN `CPU_USAGE` DOUBLE NULL DEFAULT '1',
ADD COLUMN `FREE_MEMOREY` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin',
ADD COLUMN `FREE_MEMOREY_AT_START` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin',
ADD COLUMN `CPU_USAGE_AT_START` DOUBLE NULL DEFAULT '0',
ADD COLUMN `IP_AND_PORT` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
ADD COLUMN `POOL_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin';

ALTER TABLE `UMG_RUNTIME_TRANSACTION`
CHANGE COLUMN `FREE_MEMOREY` `FREE_MEMORY` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin' AFTER `CPU_USAGE`,
CHANGE COLUMN `FREE_MEMOREY_AT_START` `FREE_MEMORY_AT_START` VARCHAR(50) NULL DEFAULT '0' COLLATE 'utf8_bin' AFTER `FREE_MEMORY`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION`
ADD COLUMN `NO_OF_ATTEMPTS` INT(2) NULL DEFAULT NULL AFTER `POOL_NAME`;

ALTER TABLE `UMG_RUNTIME_TRANSACTION` CHANGE COLUMN `ERROR_DESCRIPTION` `ERROR_DESCRIPTION` BLOB NULL DEFAULT NULL AFTER `ERROR_CODE`;


COMMIT;