USE localhost;

CREATE TABLE `MODEL_LIB_EXEC_PKG_MAPPING` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NOT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_LIBRARY_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_PKG_ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`EXEC_SEQUENCE` INT(11) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_MODEL_EXEC_PKG_ID` (`MODEL_EXEC_PKG_ID`),
	INDEX `FK_MODEL_LIBRARY_ID` (`MODEL_LIBRARY_ID`),
	CONSTRAINT `FK_MODEL_EXEC_PKG_ID` FOREIGN KEY (`MODEL_EXEC_PKG_ID`) REFERENCES `MODEL_EXEC_PACKAGES` (`ID`),
	CONSTRAINT `FK_MODEL_LIBRARY_ID` FOREIGN KEY (`MODEL_LIBRARY_ID`) REFERENCES `MODEL_LIBRARY` (`ID`)
)
COMMENT='Mapping table to hold model library and execution package'
COLLATE='utf8_bin'
ENGINE=InnoDB;



CREATE TABLE `MODEL_LIB_EXEC_PKG_MAPPING_AUDIT` (
	`ID` CHAR(36) NOT NULL COLLATE 'utf8_bin',
	`TENANT_ID` CHAR(36) NULL DEFAULT NULL COMMENT 'Tenant code for the record' COLLATE 'utf8_bin',
	`MODEL_LIBRARY_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`MODEL_EXEC_PKG_ID` CHAR(36) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`EXEC_SEQUENCE` INT(11) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CREATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	`REV` INT(11) NOT NULL,
	`REVTYPE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_MODEL_LIB_EXEC_PKG_REV` (`REV`),
	CONSTRAINT `FK_MODEL_LIB_EXEC_PKG_REV` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`)
)
COMMENT='Mapping table to hold model library and execution package'
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;

ALTER TABLE `MODEL_LIBRARY`
ADD COLUMN `MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL AFTER `LAST_UPDATED_ON`,
ADD CONSTRAINT `FKMODEL_EXEC_ENV_ID` FOREIGN KEY (`MODEL_EXEC_ENV_ID`) REFERENCES `MODEL_EXECUTION_ENVIRONMENTS` (`ID`);

UPDATE `MODEL_LIBRARY` SET MODEL_EXEC_ENV_ID = (SELECT ID FROM MODEL_EXECUTION_ENVIRONMENTS WHERE EXECUTION_ENVIRONMENT = 'MATLAB' AND ENVIRONMENT_VERSION = '7.16') WHERE EXECUTION_LANGUAGE = 'Matlab';
UPDATE `MODEL_LIBRARY` SET MODEL_EXEC_ENV_ID = (SELECT ID FROM MODEL_EXECUTION_ENVIRONMENTS WHERE EXECUTION_ENVIRONMENT = 'R' AND ENVIRONMENT_VERSION = '3.1.2') WHERE EXECUTION_LANGUAGE = 'R';

ALTER TABLE `MODEL_LIBRARY_AUDIT`
ADD COLUMN `MODEL_EXEC_ENV_ID` CHAR(36) NULL DEFAULT NULL AFTER `REVTYPE`;