USE localhost;

SET SQL_SAFE_UPDATES = 0;

UPDATE `MODEL_LIBRARY` SET MODEL_EXEC_ENV_ID = 
(SELECT ID FROM MODEL_EXECUTION_ENVIRONMENTS WHERE EXECUTION_ENVIRONMENT = 'Matlab' AND 
ENVIRONMENT_VERSION = '7.16') WHERE lower(EXECUTION_LANGUAGE) = 'matlab';

COMMIT;