SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT` (
  `ID` CHAR(36),
  `TENANT_ID` CHAR(36),
  `TYPE_NAME` VARCHAR(50),
  CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  `REV` INT(11) NOT NULL,
  `REVTYPE` TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT_REVINFO (REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_RESULT_TYPES_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY_AUDIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_AUDIT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_AUDIT` (
  `ID` CHAR(36) NOT NULL,
  `TENANT_ID` CHAR(36) NULL,
  `MAPPING_ID` CHAR(36) NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL ,
  `EXEC_SEQUENCE` INT NOT NULL ,
  `SELECT_COMPONENT` VARCHAR(500) NULL,
  `FROM_COMPONENT` VARCHAR(200) NULL,
  `WHERE_COMPONENT` VARCHAR(500) NULL,
  `ORDER_BY_COMPONENT` VARCHAR(100) NULL,
  `EXEC_QUERY` VARCHAR(3000) NULL,
  `ROW_TYPE` VARCHAR(12) NULL,
  `DATA_TYPE` VARCHAR(20) NULL,
  `MAPPING_TYPE` VARCHAR(15) NULL,
    CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  `REV` INT(11) NOT NULL,
  `REVTYPE` TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_SYNDICATE_DATA_QUERY_AUDIT_REVINFO (REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- -----------------------------------------------------
-- Table `SYND_DATA_QUERY_INPUTS_AUDIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_INPUTS_AUDIT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_INPUTS_AUDIT` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `SYNDICATE_DATA_QUERY_ID` CHAR(36) NULL ,
  `NAME` VARCHAR(50) NULL ,
  `DATA_TYPE` VARCHAR(25) NULL ,
  `SAMPLE_VALUE` VARCHAR(50) NULL ,
  `MANDATORY` TINYINT NULL,
    CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  `REV` INT(11) NOT NULL,
  `REVTYPE` TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_SYNDICATE_DATA_QUERY_INPUTS_AUDIT_REVINFO (REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_INPUTS_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT` (
  `ID` CHAR(36) NOT NULL ,
  `TENANT_ID` CHAR(36) NULL ,
  `SYNDICATE_DATA_QUERY_ID` CHAR(36) NULL ,
  `NAME` VARCHAR(50) NULL ,
  `DATA_TYPE` VARCHAR(25) NULL ,
  `MANDATORY` TINYINT NULL,
  `SEQUENCE`INT,
    CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  `REV` INT(11) NOT NULL,
  `REVTYPE` TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT_REVINFO (REV),
  CONSTRAINT FK_SYNDICATE_DATA_QUERY_OUTPUTS_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

