use `Ocwen`;

ALTER TABLE UMG_RUNTIME_TRANSACTION	 ADD COLUMN `MODEL_EXEC_ENV_NAME` VARCHAR(50) NULL DEFAULT 'R-3.2.1' COLLATE 'utf8_bin';

ALTER TABLE UMG_RUNTIME_TRANSACTION ADD COLUMN `R_SERVE_PORT` INT(10) NULL DEFAULT '0' AFTER `MODEL_EXEC_ENV_NAME`;

commit;
