use umg_admin;

set @CREATED_BY = 'SYSTEM';

set @CREATED_ON = '1401344421';

set @FROM_ADDRESS = 'REALAnalytics-QE@altisource.com';	
	
	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb401', 1, 1, 1, 'rentrange', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb402', 2, 2, 1, 'rentrange', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);

	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb403', 3, 3, 1, 'rentrange', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);
	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb404', 1, 1, 1, 'ocwen', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb405', 2, 2, 1, 'ocwen', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);

	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb406', 3, 3, 1, 'ocwen', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);
	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb407', 1, 1, 1, 'equator', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb408', 2, 2, 1, 'equator', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);

	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb409', 3, 3, 1, 'equator','umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);
	
	INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb410', 1, 1, 1, 'hubzu', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb411', 2, 2, 1, 'hubzu', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);

	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb412', 3, 3, 1, 'hubzu','umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);
	
	INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb413', 1, 1, 1, 'realtrans','umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb414', 2, 2, 1, 'realtrans', 'umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);

	
INSERT INTO NOTIFICATION_EVENT_TEMPLATE_MAPPING (ID, NOTIFICATION_EVENT_ID, NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TENANT_ID, TO_ADDRESS, FROM_ADDRESS, CC_ADDRESS, BCC_ADDRESS, CREATED_BY, CREATED_ON)
	VALUES ('9245ecf2-cd13-4e7a-9c25-b5afb45bb415', 3, 3, 1, 'realtrans','umgqe@altisource.com', @FROM_ADDRESS, '', '', @CREATED_BY, @CREATED_ON);


commit;