CREATE TABLE MAPPING (
  ID CHAR(36) NOT NULL,
  TENANT_ID CHAR(36) NOT NULL COMMENT 'Tenant code for the record',
  NAME VARCHAR(100) NOT NULL COMMENT 'Derived name of the mapping.Includes version date',
  DESCRIPTION VARCHAR(200) NULL COMMENT 'Description of the mapping.',
  MODEL_ID CHAR(36) NOT NULL COMMENT 'Model used for this mapping',
  MODEL_IO_DATA BLOB NOT NULL COMMENT 'Extracted MID definition as json for model.',
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UN_MAPPING_NAME (NAME),
  INDEX FK_MAPPING_MODEL (MODEL_ID),
  CONSTRAINT FK_MAPPING_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODEL(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;