CREATE TABLE MAPPING_AUDIT (
  ID CHAR(36) NOT NULL,
  REV int(11) NOT NULL,
  REVTYPE tinyint(4) DEFAULT NULL,
  TENANT_ID CHAR(36) NULL COMMENT 'Tenant code for the record',
  NAME VARCHAR(100) NULL COMMENT 'Derived name of the mapping.Includes version date',
  DESCRIPTION VARCHAR(200) NULL COMMENT 'Description of the mapping.',
  MODEL_ID CHAR(36) NULL COMMENT 'Model used for this mapping',
  MODEL_IO_DATA BLOB NULL COMMENT 'Extracted MID definition as json for model.',
  CREATED_BY CHAR(100) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(100) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID,REV),
  KEY IDX_MAPPING_AUDIT_REVINFO (REV),
  CONSTRAINT FK_MAPPING_AUDIT_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;