
UPDATE WEEKN_DAILY_RUN_STATUS set LAST_RUN_DATE = DATE_FORMAT(STR_TO_DATE(SUBSTR(LAST_RUN_DATE, 1, 9), "%d-%M-%Y"),"%Y-%m-%d");

ALTER TABLE `WEEKN_DAILY_RUN_STATUS`
	CHANGE COLUMN `LAST_RUN_DATE` `LAST_RUN_DATE` DATETIME NULL DEFAULT NULL;