

ALTER TABLE `DYNAMIC_PRICING_INTG_AUDITS`
	CHANGE COLUMN `ERROR_DESCRIPTION` `ERROR_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL AFTER `STATUS`;
	
ALTER TABLE `DP_WEEKN_INTG_AUDITS`
	CHANGE COLUMN `ERROR_DESCRIPTION` `ERROR_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL AFTER `STATUS`;