CREATE TABLE MAPPING_INPUT (
  ID CHAR(36) NOT NULL,
  TENANT_ID CHAR(36) NOT NULL COMMENT 'Tenant code for the record',
  MAPPING_ID CHAR(36) NOT NULL COMMENT 'Model used for this mapping',
  MAPPING_DATA BLOB NOT NULL COMMENT 'Complete mapping definition.',
  TENANT_INTERFACE_DEFINITION BLOB NOT NULL COMMENT 'Complete mapping definition.',
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UN_MAPPING_INPUT (MAPPING_ID),
  CONSTRAINT FK_MAPPING_INPUT_MAPPING FOREIGN KEY (MAPPING_ID) REFERENCES MAPPING(ID)  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;