


ALTER TABLE `WEEKN_DAILY_RUN_STATUS`
	CHANGE COLUMN `LAST_RUN_DATE` `LAST_RUN_DATE` VARCHAR(55) NULL DEFAULT NULL;
	
UPDATE WEEKN_DAILY_RUN_STATUS a set  a.LAST_RUN_DATE = CONCAT(DATE_FORMAT(CAST(a.LAST_RUN_DATE AS DATE),"%d-%b-%y"), " 00:00:00:000");