use `Ocwen`;

ALTER TABLE UMG_RUNTIME_TRANSACTION ADD COLUMN TRANSACTION_MODE VARCHAR(50) DEFAULT 'Online';
ALTER TABLE UMG_RUNTIME_TRANSACTION_AUDIT ADD COLUMN TRANSACTION_MODE VARCHAR(50) DEFAULT 'Online';

ALTER TABLE UMG_VERSION ADD COLUMN MODEL_TYPE VARCHAR(10) NOT NULL DEFAULT 'Online';
ALTER TABLE UMG_VERSION_AUDIT ADD COLUMN MODEL_TYPE VARCHAR(10) NOT NULL DEFAULT 'Bulk';

ALTER TABLE BATCH_TRANSACTION ADD COLUMN TRANSACTION_MODE VARCHAR(10) NOT NULL DEFAULT 'Batch';

commit;
