

ALTER TABLE `DP_SOP_WEEKN_PRCS_STATUS`
	ADD COLUMN `OCN_OUTPUT_FILE_NAME` VARCHAR(500) NOT NULL AFTER `CC_LIST`,
	ADD COLUMN `NRZ_OUTPUT_FILE_NAME` VARCHAR(500) NOT NULL AFTER `OCN_OUTPUT_FILE_NAME`;
	
ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	ADD COLUMN `SELLER_OCCUPIED_PROPERTY` VARCHAR(50) NULL DEFAULT NULL AFTER `RBID_PROP_ID_VC_PK`;
	
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`)
VALUES (UUID(), 'sopWeekNFetchData', 'Data Fetch Failure', 1, 'SOP_WEEKN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNAssignmentFilter', 'Benchmark', 2, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNAssignmentFilter', 'Benchmark', 2, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 3, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNSuccessfulUnderreviewFilter', 'Successful / Underreview', 3, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNActiveListingsFilter', 'Active Listing', 4, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNActiveListingsFilter', 'Active Listing', 4, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNPast12CyclesFilter', 'Past 12 Cycles', 5, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNPast12CyclesFilter', 'Past 12 Cycles', 5, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNOddListingsFilter', 'Odd Listing', 6, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNOddListingsFilter', 'Odd Listing', 6, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNSSPmiFilter', 'SS & PMI', 8, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNSSPmiFilter', 'SS & PMI', 8, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNVacantFilter', 'Vacant', 9, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNVacantFilter', 'Vacant', 9, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNRAIntegrarion', 'Model Failure', 10, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNRAIntegrarion', 'Model Failure', 10, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),

(UUID(), 'sopWeekNStateFilter', 'Unsupported State', 7, 'SOP_WEEKN_OCN', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW())),
(UUID(), 'sopWeekNStateFilter', 'Unsupported State', 7, 'SOP_WEEKN_NRZ', 1, 'SYSTEM', UNIX_TIMESTAMP(NOW()));

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST WHERE (RBID_PROP_ID_VC_FK, TO_DATE(LIST_STRT_DATE_DT_NN)) IN (SELECT RBID_PROP_ID_VC_FK, MAX(TO_DATE(LIST_STRT_DATE_DT_NN)) FROM RRRBPMTX_PROP_LIST WHERE TO_DATE(LIST_STRT_DATE_DT_NN) BETWEEN TO_DATE(?) AND TO_DATE(?) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) GROUP BY RBID_PROP_ID_VC_FK) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') AND  LIST_STTS_DTLS_VC IS NULL) AND LIST_TYPE_ID_VC_FK = \'AUCN\' AND OCCPNCY_STTS_AT_LST_CREATN <> \'N\' AND TO_DATE(LIST_END_DATE_DT_NN) < TO_DATE(?)' WHERE  `ATTR_KEY`='INITIAL_SOP_WEEKN_HUBZU_QUERY';
