use umg_admin;

DELETE FROM `NOTIFICATION_EMAIL_TEMPLATE` WHERE `NAME`='MODELET POOL MISMATCH TEMPLATE';

DELETE FROM `NOTIFICATION_EVENT` WHERE `NAME`='Modelet Pool Mismatch';

DELETE FROM `NOTIFICATION_EVENT_TEMPLATE_MAPPING` WHERE `NAME`='Modelet Pool Mismatch';

COMMIT;