
SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0DuplicateFilter', 'Duplicate Asset', 2, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0InvestorCodeFilter', 'SS Investor', 3, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0AssetValueFilter', 'Unsupported Asset Value', 4, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0RRRtngAggregator', 'Failed Data Fetch', 5, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0PropertyTypeFilter', 'Unsupported Property Type', 6, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0CAIntegration', 'CA_INTEGRATION', 7, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0ModeledBenchmarkCriteria', 'RULE_80_20', 8, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0RAInputPayload', 'Model Failure', 9, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0OutputFileCreate', 'WEEK0_OUTPUT_FILE', 10, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) 
VALUES (UUID(), 'week0EmailIntegration', 'WEEK0_EMAIL_INTEGRATION', 11, 'WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

SELECT ID from `RA_TNT_APPS` WHERE `NAME` = 'DPA' INTO @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.model.name', 'HUBZU_WEEK_0', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.tenant.code', 'hubzu', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.major.version', '24', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.week0Vacant.minor.version', '', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.pricemode.input', NULL, 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.dp.auth.token', 'k+oRDQ7tYuD5oyq6HubRAbFrReewznGAzQFfQwPxZdMarkkvK5mO5sobLwRsW4H4', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.maximum.asset.value', '750000', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);
INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CLASSIFICATION`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), @APP_ID, 'phh.minimum.asset.value', '10000', 'PHH', @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

-- Adding Column into DYNAMIC_PRICING_FILE_PRCS_STATUS  Table for PHH Loan Output File --
ALTER TABLE `DYNAMIC_PRICING_FILE_PRCS_STATUS`	ADD COLUMN `PHH_OUTPUT_FILE_NAME` VARCHAR(200) NULL DEFAULT NULL AFTER `NRZ_OUTPUT_FILE_NAME`;
