

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'RR_MIGRATION_PROP_TEMP_QUERY';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'RR_MIGRATION_LOAN_NUM_QUERY';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'RR_MIGRATION_OLD_RR_LOAN_NUM_QUERY';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'RR_MIGRATION_LOAN_NUM_WHERE_OLD_RR_LOAN_NULL_QUERY';

DROP TABLE IF EXISTS `DP_MIGRATION_MAP`;

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT RBID_PROP_ID_VC_FK FROM RRRBPMTX_PROP_LIST, RRRBPMMS_PROP OT WHERE (RBID_PROP_ID_VC_FK, TO_DATE(LIST_STRT_DATE_DT_NN)) IN (SELECT RBID_PROP_ID_VC_FK, MAX(TO_DATE(LIST_STRT_DATE_DT_NN)) FROM RRRBPMTX_PROP_LIST WHERE TO_DATE(LIST_STRT_DATE_DT_NN) BETWEEN TO_DATE(?) AND TO_DATE(?) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) GROUP BY RBID_PROP_ID_VC_FK) AND (LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR LIST_STTS_DTLS_VC IS NULL) AND LIST_TYPE_ID_VC_FK = \'AUCN\' AND OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND TO_DATE(LIST_END_DATE_DT_NN) < TO_DATE(?) AND RBID_PROP_ID_VC_FK = OT.RBID_PROP_ID_VC_PK AND OT.PROP_STTS_ID_VC_FK != \'DELETED\'' WHERE  `ATTR_KEY`='INITIAL_HUBZU_QUERY';