

ALTER TABLE `DP_WEEKN_PARAMS` ADD COLUMN `INITIAL_VALUATION` DECIMAL(20,0) NULL DEFAULT NULL AFTER `MOST_RECENT_LIST_PRICE`;

UPDATE DP_WEEKN_PARAMS K JOIN (SELECT k1.ASSET_NUMBER, k1.ASSET_VALUE FROM DP_WEEK0_PARAMS k1 JOIN (SELECT P.ASSET_NUMBER, MAX(P.UPDATE_TIMESTAMP) AS UPDATE_TIMESTAMP FROM DP_WEEK0_PARAMS P WHERE (P.NOTES != 'Previously Assigned' OR P.NOTES IS NULL) GROUP BY P.ASSET_NUMBER) k2 ON k1.ASSET_NUMBER = k2.ASSET_NUMBER AND k1.UPDATE_TIMESTAMP = k2.UPDATE_TIMESTAMP limit 1000000) S ON K.ASSET_NUMBER = S.ASSET_NUMBER SET K.INITIAL_VALUATION = S.ASSET_VALUE;