

UPDATE `RA_TNT_APP_PARAMS` SET `ATTR_VALUE`='SELECT LOANNUMBER, REVIEWDT,APPRTYP,ASISLOWMKTVAL,ASISMIDMKTVAL,CONDITIONCDE,LIVINGAREA,TOTREPAIRAMT FROM ST_MORTAPRQ WHERE LOANNUMBER =? ORDER BY REVIEWDT DESC' WHERE  `ATTR_KEY`='STAGE5_QUERY';
