use umg_admin;

ALTER TABLE `MODEL_EXECUTION_ENVIRONMENTS`	DROP COLUMN `IS_ACTIVE`;

ALTER TABLE `MODEL_EXEC_PACKAGES` 
DROP INDEX  `UNIQUE_PACKAGE_NAME`,	
ADD UNIQUE INDEX `UNIQUE_PACKAGE_NAME` (`PACKAGE_NAME`);

ALTER TABLE `MODEL_EXEC_PACKAGES`	
DROP INDEX `PACKAGE_FOLDER_VERSION_ENV_CONSTRAINT`,
ADD UNIQUE INDEX `PACKAGE_FOLDER_VERSION_ENV_CONSTRAINT` (`PACKAGE_FOLDER`, `PACKAGE_VERSION`, `EXECUTION_ENVIRONMENT`);

ALTER TABLE `SYSTEM_MODELETS` DROP COLUMN `R_SERVE_PORT`;

ALTER TABLE `SYSTEM_MODELETS` DROP COLUMN `R_MODE`;

commit;

