

ALTER TABLE `DP_WEEKN_PARAMS` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_PARAMS_ORIGINAL` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEK0_PARAMS_ORIGINAL` DROP COLUMN `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_WEEKN_AUDIT_REPORTS` DROP COLUMN `OLD_LOAN_NUMBER`;