ALTER TABLE `DP_WEEK0_PARAMS`
    CHANGE COLUMN `WEEK0_ID` `WEEK0_ID` VARCHAR(50) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
    DROP INDEX `WEEK0_ID_FK`,
    DROP FOREIGN KEY `WEEK0_ID_FK`;

ALTER TABLE `DP_WEEKN_PARAMS`
	CHANGE COLUMN `WEEKN_ID` `WEEKN_ID` VARCHAR(50) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
	DROP INDEX `WEEKN_ID_FK`,
	DROP FOREIGN KEY `WEEKN_ID_FK`;
