ALTER TABLE `DP_WEEK0_PARAMS`
    CHANGE COLUMN `WEEK0_ID` `WEEK0_ID` CHAR(36) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
    ADD INDEX `WEEK0_ID_FK` (`WEEK0_ID`),
    ADD CONSTRAINT `WEEK0_ID_FK` FOREIGN KEY (`WEEK0_ID`) REFERENCES `DP_WEEK0_PARAMS_ORIGINAL` (`ID`);

ALTER TABLE `DP_WEEKN_PARAMS`
	CHANGE COLUMN `WEEKN_ID` `WEEKN_ID` CHAR(36) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
	ADD INDEX `WEEKN_ID_FK` (`WEEKN_ID`),
	ADD CONSTRAINT `WEEKN_ID_FK` FOREIGN KEY (`WEEKN_ID`) REFERENCES `DP_WEEKN_PARAMS` (`ID`);
