DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.error.email.body';

ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	CHANGE COLUMN `PREVIOUS_LIST_START_DATE` `PREVIOUS_LIST_STRT_DATE` VARCHAR(55) NULL DEFAULT NULL AFTER `LIST_TYPE_ID_VC_FK`,
	CHANGE COLUMN `PREVIOUS_LIST_END_DATE` `PREVIOUS_LIST_END_DATE` VARCHAR(55) NULL DEFAULT NULL AFTER `PREVIOUS_LIST_STRT_DATE`,
	CHANGE COLUMN `CURRENT_LIST_START_DATE` `CURRENT_LIST_STRT_DATE` VARCHAR(55) NULL DEFAULT NULL AFTER `PREVIOUS_LIST_PRICE`,
	CHANGE COLUMN `CURRENT_LIST_END_DATE` `CURRENT_LIST_END_DATE` VARCHAR(55) NULL DEFAULT NULL AFTER `CURRENT_LIST_STRT_DATE`;

ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	DROP COLUMN `OLD_PROP_ID`;

ALTER TABLE `WEEKN_DAILY_QA_REPORT`
	DROP COLUMN `OLD_LOAN_NUMBER`;

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.email.from';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.email.subject';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.email.cclist';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.email.tolist';

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` = 'qa.report.email.body';

DELETE FROM `RA_TNT_SYSTEM_PARAMETERS` WHERE `SYS_KEY` = 'qa.daily.report.schedule.status';

DROP TABLE `WEEKN_DAILY_QA_REPORT`;

DROP TABLE `WEEKN_DAILY_RUN_STATUS`;