use umg_admin;

DELETE FROM PERMISSION_ROLES_MAPPING WHERE tenant_roles_map_id IN(SELECT trm.Id FROM TENANT_ROLES_MAPPING trm ,ROLES r WHERE r.ROLE IN('ROLE_ADMIN','ROLE_MODELER','ROLE_TENANT_USER') AND trm.roles_id=r.Id);
DELETE FROM TENANT_ROLES_MAPPING WHERE roles_id IN (SELECT Id from ROLES WHERE ROLE IN('ROLE_ADMIN','ROLE_MODELER','ROLE_TENANT_USER') ) ;
DELETE from ROLES where (ROLE='ROLE_TENANT_USER' OR ROLE='ROLE_MODELER');
commit;
