use umg_admin;

DROP TABLE IF EXISTS NOTIFICATION_EVENT_TEMPLATE_MAPPING;

DROP TABLE IF EXISTS NOTIFICATION_EMAIL_TEMPLATE;

DROP TABLE IF EXISTS NOTIFICATION_SMS_TEMPLATE;

DROP TABLE IF EXISTS NOTIFICATION_TYPE;

DROP TABLE IF EXISTS NOTIFICATION_EVENT;

COMMIT;