use umg_admin;

set SQL_SAFE_UPDATES = 0;

TRUNCATE TABLE NOTIFICATION_TYPE;

TRUNCATE TABLE NOTIFICATION_EVENT;

TRUNCATE TABLE NOTIFICATION_EMAIL_TEMPLATE;

TRUNCATE TABLE NOTIFICATION_SMS_TEMPLATE;

TRUNCATE TABLE NOTIFICATION_EVENT_TEMPLATE_MAPPING;

DELETE FROM SYSTEM_PARAMETER WHERE SYS_KEY in ('SMTP_HOST_NAME', 'SMTP_SERVER', 'NOTIFICATION_TEMPLATE_DIR', 'UMG_ADMIN_URL', 'umgAdminUrl');

DELETE FROM SYSTEM_PARAMETER_AUDIT WHERE SYS_KEY in ('SMTP_HOST_NAME', 'SMTP_SERVER', 'NOTIFICATION_TEMPLATE_DIR', 'UMG_ADMIN_URL', 'umgAdminUrl');

COMMIT;