USE umg_admin;

ALTER TABLE `SYSTEM_KEY` ADD UNIQUE INDEX `SYSTEM_KEY` (`SYSTEM_KEY`, `KEY_TYPE`);

INSERT INTO `SYSTEM_KEY` (`ID`, `SYSTEM_KEY`, `KEY_TYPE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(),'BULK_ENABLED','TENANT','SYSTEM',UNIX_TIMESTAMP(),'SYSTEM',UNIX_TIMESTAMP());

INSERT INTO `SYSTEM_KEY` (`ID`, `SYSTEM_KEY`, `KEY_TYPE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(),'EMAIL_NOTIFICATIONS_ENABLED','TENANT','SYSTEM',UNIX_TIMESTAMP(),'SYSTEM',UNIX_TIMESTAMP());

DELETE FROM TENANT_CONFIG WHERE SYSTEM_KEY_ID = ( SELECT ID FROM SYSTEM_KEY WHERE SYSTEM_KEY = "SOME");

DELETE FROM SYSTEM_KEY WHERE SYSTEM_KEY = "SOME" ;

COMMIT;