CREATE TABLE MIGRATION_LOG (
  ID CHAR(36) NOT NULL,
  TENANT_ID CHAR(36) NOT NULL COMMENT 'Tenant code for the record',
  VERSION_ID CHAR(36) COMMENT 'Version ID which is imported / exported',
  MIGRATION_TYPE VARCHAR(10) NOT NULL COMMENT 'Specifies whether it was an import / export entry',
  VERSION_DATA BLOB COMMENT 'Version Details',
  STATUS VARCHAR(20) NOT NULL COMMENT 'Migration Status',
  CREATED_BY CHAR(36) NOT NULL ,
  CREATED_ON BIGINT(20) NOT NULL,
  LAST_UPDATED_BY CHAR(36) NULL,
  LAST_UPDATED_ON BIGINT(20) NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_VERSION FOREIGN KEY (VERSION_ID) REFERENCES UMG_VERSION(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;