DROP TABLE IF EXISTS `DP_SOP_WEEK0_PARAMS`;

DROP TABLE IF EXISTS `DP_SOP_WEEK0_PARAMS_ORIGINAL`;

DROP TABLE IF EXISTS `DP_SOP_WEEK0_PRCS_STATUS`;

CREATE TABLE `DP_SOP_WEEK0_PRCS_STATUS` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '',
	`STATUS` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEK0_PARAMS` (
	`ID` CHAR(36) NOT NULL,
	`DP_SOP_WEEK0_FILE_ID` CHAR(36) NOT NULL,
	`ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`OLD_ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`PROP_TEMP` VARCHAR(100) NOT NULL,
	`STATE` VARCHAR(2) NOT NULL,
	`PROPERTY_TYPE` VARCHAR(10) NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	`ASSET_VALUE` DECIMAL(10,0) NOT NULL,
	`AV_SET_DATE` VARCHAR(10) NOT NULL,
	`REO_DATE` VARCHAR(10) NOT NULL,
	`LIST_PRICE` DECIMAL(10,0) NOT NULL,
	`CLASSIFICATION` VARCHAR(10) NOT NULL,
	`ELIGIBLE` VARCHAR(100) NULL DEFAULT NULL,
	`ASSIGNMENT` VARCHAR(100) NULL DEFAULT NULL,
	`ASSIGNMENT_DATE` BIGINT(20) NULL DEFAULT NULL,
	`NOTES` VARCHAR(500) NULL DEFAULT NULL,
	`ERROR_DETAIL` VARCHAR(1000) NULL DEFAULT NULL,
	`FAILED_STEP_COMMAND_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `DP_SOP_INPUT_FILE_ID_FK` (`DP_SOP_WEEK0_FILE_ID`),
	CONSTRAINT `DP_SOP_INPUT_FILE_ID_FK` FOREIGN KEY (`DP_SOP_WEEK0_FILE_ID`) REFERENCES `DP_SOP_WEEK0_PRCS_STATUS` (`id`)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_INTG_AUDITS`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PARAMS`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PARAMS_ORIGINAL`;

DROP TABLE IF EXISTS `DP_SOP_WEEKN_PRCS_STATUS`;

CREATE TABLE `DP_SOP_WEEKN_PRCS_STATUS` (
	`ID` CHAR(36) NOT NULL DEFAULT '',
	`INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '',
	`STATUS` VARCHAR(100) NOT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DP_SOP_WEEKN_PARAMS` (
	`ID` CHAR(36) NOT NULL,
	`DP_SOP_WEEKN_FILE_ID` CHAR(36) NULL DEFAULT NULL,
	`ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`OLD_ASSET_NUMBER` VARCHAR(100) NOT NULL,
	`PROP_TEMP` VARCHAR(100) NOT NULL,
	`CLASSIFICATION` VARCHAR(15) NULL DEFAULT NULL,
	`ELIGIBLE` VARCHAR(15) NULL DEFAULT NULL,
	`ASSIGNMENT` VARCHAR(15) NULL DEFAULT NULL,
	`EXCLUSION_REASON` VARCHAR(100) NULL DEFAULT NULL,
	`RBID_PROP_ID_VC_PK` VARCHAR(100) NULL DEFAULT NULL,
	`STATE` VARCHAR(2) NULL DEFAULT NULL,
	`ZIPCODE` VARCHAR(20) NULL DEFAULT NULL,
	`PRIVATE_MORTGAGE_INSURANCE` VARCHAR(20) NULL DEFAULT NULL,
	`SELLER_OCCUPIED_PROPERTY` VARCHAR(50) NULL DEFAULT NULL,
	`FAILED_STEP_COMMAND_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `DP_SOP_WEEKN_FILE_ID_FK` (`DP_SOP_WEEKN_FILE_ID`),
	CONSTRAINT `DP_SOP_WEEKN_FILE_ID_FK` FOREIGN KEY (`DP_SOP_WEEKN_FILE_ID`) REFERENCES `DP_SOP_WEEKN_PRCS_STATUS` (`id`)
)ENGINE=InnoDB;

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_OCN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEK0_NRZ';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_OCN';

DELETE FROM `COMMAND` WHERE `PROCESS` = 'SOP_WEEKN_NRZ';

ALTER TABLE `DP_WEEK0_PARAMS`
    CHANGE COLUMN `WEEK0_ID` `WEEK0_ID` VARCHAR(50) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
    DROP INDEX `WEEK0_ID_FK`,
    DROP FOREIGN KEY `WEEK0_ID_FK`;

ALTER TABLE `DP_WEEKN_PARAMS`
	CHANGE COLUMN `WEEKN_ID` `WEEKN_ID` VARCHAR(50) NULL DEFAULT NULL AFTER `UPDATE_TIMESTAMP`,
	DROP INDEX `WEEKN_ID_FK`,
	DROP FOREIGN KEY `WEEKN_ID_FK`;

CREATE INDEX `WEEKN_DAILY_QA_REPORT_CRRNT_LSTENDT_CLSF` ON `WEEKN_DAILY_QA_REPORT`(`CURRENT_LIST_END_DATE`, `CLASSIFICATION`) USING BTREE;

SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'phhSopWeek0DuplicateFilter', 'Duplicate Asset', 1, 'SOP_WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'phhSopweek0AssetValueFilter', 'Unsupported Asset Value', 2, 'SOP_WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'phhSopweek0ModeledBenchmarkCriteria', 'RULE_80_20', 3, 'SOP_WEEK0_PHH', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'nrzSopWeek0DuplicateFilter', 'Duplicate Asset', 1, 'SOP_WEEK0_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'nrzSopWeek0AssetValueFilter', 'Unsupported Asset Value', 2, 'SOP_WEEK0_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'nrzSopWeek0ModeledBenchmarkCriteria', 'RULE_80_20', 3, 'SOP_WEEK0_NRZ', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'ocnSopWeek0DuplicateFilter', 'Duplicate Asset', 1, 'SOP_WEEK0_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'ocnSopWeek0AssetValueFilter', 'Unsupported Asset Value', 2, 'SOP_WEEK0_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

INSERT INTO `COMMAND` (`ID`, `NAME`, `DESCRIPTION`, `EXECUTION_SEQUENCE`, `PROCESS`, `ACTIVE`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES (UUID(), 'ocnSopWeek0ModeledBenchmarkCriteria', 'RULE_80_20', 3, 'SOP_WEEK0_OCN', TRUE, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);

ALTER TABLE `DP_SOP_WEEK0_PARAMS`
	CHANGE COLUMN `OLD_ASSET_NUMBER` `OLD_ASSET_NUMBER` VARCHAR(100) NULL DEFAULT NULL AFTER `ASSET_NUMBER`,
	CHANGE COLUMN `PROP_TEMP` `PROP_TEMP` VARCHAR(100) NULL DEFAULT NULL AFTER `OLD_ASSET_NUMBER`;

ALTER TABLE `DP_SOP_WEEKN_PARAMS`
	CHANGE COLUMN `OLD_ASSET_NUMBER` `OLD_ASSET_NUMBER` VARCHAR(100) NULL DEFAULT NULL AFTER `ASSET_NUMBER`,
	CHANGE COLUMN `PROP_TEMP` `PROP_TEMP` VARCHAR(100) NULL DEFAULT NULL AFTER `OLD_ASSET_NUMBER`;

SELECT ID from RA_TNT_APPS WHERE LOWER(code) = 'dpa' INTO @APP_ID;

DELETE FROM `RA_TNT_APP_PARAMS` WHERE `ATTR_KEY` IN ('phh.av.upper.slab','phh.av.lower.slab') AND `RA_TNT_APP_ID` = @APP_ID;

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'phh.av.upper.slab', '4', 'SYSTEM', NOW());

INSERT INTO `RA_TNT_APP_PARAMS` (`ID`, `RA_TNT_APP_ID`, `ATTR_KEY`, `ATTR_VALUE`, `CREATED_BY`, `CREATED_ON`) VALUES (UUID(), @APP_ID, 'phh.av.lower.slab', '1', 'SYSTEM', NOW());

ALTER TABLE `DP_SOP_WEEK0_PRCS_STATUS`
	ADD COLUMN `SYS_GNRTD_INPUT_FILE_NAME` VARCHAR(200) NOT NULL DEFAULT '' AFTER `INPUT_FILE_NAME`;

SET @CREATED_BY = 'SYSTEM';

SET @CREATED_ON =  UNIX_TIMESTAMP() * 1000;

SET @HUBZU_ALL_ROOWS_QUERY = 'SELECT OT1.SELR_PROP_ID_VC_NN,OT1.RBID_PROP_ID_VC_PK,t1.RBID_PROP_ID_VC_FK,OT1.REO_PROP_STTS_VC ,OT1.PROP_SOLD_DATE_DT,OT1.PROP_STTS_ID_VC_FK,T1.RBID_PROP_ID_VC_FK,T1.RBID_PROP_LIST_ID_VC_PK,T1.LIST_TYPE_ID_VC_FK,T1.LIST_PRCE_NT,T1.LIST_STRT_DATE_DT_NN,T1.LIST_END_DATE_DT_NN,T1.LIST_STTS_DTLS_VC,T1.OCCPNCY_STTS_AT_LST_CREATN FROM RRRBPMTX_PROP_LIST T1, RRRBPMMS_PROP OT1 WHERE T1.RBID_PROP_ID_VC_FK  IN (:idList) AND T1.RBID_PROP_ID_VC_FK = OT1.RBID_PROP_ID_VC_PK AND T1.LIST_TYPE_ID_VC_FK = \'AUCN\' AND T1.OCCPNCY_STTS_AT_LST_CREATN <> \'Y\' AND (T1.LIST_STTS_DTLS_VC NOT IN (\'CANCELLED\',\'DISAPPROVED\') OR T1.LIST_STTS_DTLS_VC IS NULL) AND OT1.SELR_ACNT_ID_VC_FK IN (\'000\',\'900\',\'891\') AND (SELECT COUNT(*) FROM RRRBPMMS_PROP OT2 WHERE OT2.SELR_PROP_ID_VC_NN = OT1.SELR_PROP_ID_VC_NN AND OT1.PROP_SOLD_DATE_DT IS NULL AND OT2.PROP_SOLD_DATE_DT IS NOT NULL)=0 ORDER BY OT1.SELR_PROP_ID_VC_NN DESC, TO_DATE(LIST_STRT_DATE_DT_NN) DESC, T1.LIST_END_DATE_DT_NN DESC';

UPDATE `RA_TNT_APP_PARAMS` SET ATTR_VALUE = @HUBZU_ALL_ROOWS_QUERY WHERE ATTR_KEY = 'hubzu.daily.qa.report.all.rows';

ALTER TABLE `WEEKN_DAILY_RUN_STATUS`
	ADD COLUMN `FETCH_START_DATE` DATE NULL DEFAULT NULL AFTER `LAST_RUN_DATE`,
	ADD COLUMN `FETCH_END_DATE` DATE NULL DEFAULT NULL AFTER `FETCH_START_DATE`;

DELETE FROM `WEEKN_DAILY_QA_REPORT`;

DELETE FROM `WEEKN_DAILY_RUN_STATUS`;

INSERT INTO `WEEKN_DAILY_RUN_STATUS` (`ID`, `LAST_RUN_DATE`, `FETCH_START_DATE`, `FETCH_END_DATE`, `TOTAL_RECORD`, `REPORT_TYPE`, `START_TIME`, `END_TIME`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`)
    VALUES (UUID(), '2019-07-17 00:00:00', '2019-06-01', '2019-06-30', 1, 'QA-REPORT', 0, 0, @CREATED_BY, @CREATED_ON, @CREATED_BY, @CREATED_ON);